// Mock data layer for LLL Draft Analyzer
// Teams, players, experts, picks, grades — multi-year

const TEAMS = [
  {id: 'DET', name: 'Lions', city: 'Detroit', primary: '#0076B6', secondary: '#B0B7BC', record: '15-2'},
  {id: 'PHI', name: 'Eagles', city: 'Philadelphia', primary: '#004C54', secondary: '#A5ACAF', record: '14-3'},
  {id: 'KC', name: 'Chiefs', city: 'Kansas City', primary: '#E31837', secondary: '#FFB81C', record: '13-4'},
  {id: 'BUF', name: 'Bills', city: 'Buffalo', primary: '#00338D', secondary: '#C60C30', record: '13-4'},
  {id: 'SF', name: 'Niners', city: 'San Francisco', primary: '#AA0000', secondary: '#B3995D', record: '12-5'},
  {id: 'BAL', name: 'Ravens', city: 'Baltimore', primary: '#241773', secondary: '#9E7C0C', record: '12-5'},
  {id: 'NYJ', name: 'Jets', city: 'New York', primary: '#125740', secondary: '#000000', record: '4-13'},
  {id: 'CAR', name: 'Panthers', city: 'Carolina', primary: '#0085CA', secondary: '#101820', record: '5-12'},
];

const EXPERTS = [
  {id: 'mk', name: 'Mel Kipling', outlet: 'NSPN', avatar: 'MK', accuracy: 78.4, trend: 'up', years: 18, calls: 1240},
  {id: 'tj', name: 'Todd Jeremiad', outlet: 'NSPN', avatar: 'TJ', accuracy: 74.1, trend: 'up', years: 12, calls: 980},
  {
    id: 'db',
    name: 'Daniel Brughler',
    outlet: 'The Athletico',
    avatar: 'DB',
    accuracy: 81.2,
    trend: 'up',
    years: 14,
    calls: 1080,
  },
  {
    id: 'ms',
    name: 'Matt Schumann',
    outlet: 'PFF Insider',
    avatar: 'MS',
    accuracy: 79.6,
    trend: 'flat',
    years: 9,
    calls: 720,
  },
  {
    id: 'pz',
    name: 'Peter Zimmerline',
    outlet: 'BR Draft',
    avatar: 'PZ',
    accuracy: 68.9,
    trend: 'down',
    years: 22,
    calls: 1640,
  },
  {
    id: 'lk',
    name: 'Lance Klimkowski',
    outlet: 'Drafttek',
    avatar: 'LK',
    accuracy: 72.3,
    trend: 'flat',
    years: 16,
    calls: 1320,
  },
  {
    id: 'cs',
    name: 'Charlie Sandover',
    outlet: 'Pro Daft',
    avatar: 'CS',
    accuracy: 65.4,
    trend: 'down',
    years: 11,
    calls: 870,
  },
  {
    id: 'rt',
    name: 'Rachel Tannen',
    outlet: 'The Ringer Up',
    avatar: 'RT',
    accuracy: 76.8,
    trend: 'up',
    years: 7,
    calls: 540,
  },
];

// LLL grade is 0–100; "fit" 0–100; "value" is value over expected pick (positive = steal)
const PLAYERS = [
  // Lions recent drafts — the showcase
  {
    id: 'p1',
    name: 'Aidan Hutchinson',
    team: 'DET',
    pos: 'EDGE',
    year: 2022,
    round: 1,
    pick: 2,
    age: 24,
    lll: 92,
    fit: 96,
    value: +14,
    retained: true,
    status: 'star',
    college: 'Michigan',
  },
  {
    id: 'p2',
    name: 'Jameson Williams',
    team: 'DET',
    pos: 'WR',
    year: 2022,
    round: 1,
    pick: 12,
    age: 23,
    lll: 71,
    fit: 78,
    value: -4,
    retained: true,
    status: 'starter',
    college: 'Alabama',
  },
  {
    id: 'p3',
    name: 'Jahmyr Gibbs',
    team: 'DET',
    pos: 'RB',
    year: 2023,
    round: 1,
    pick: 12,
    age: 22,
    lll: 89,
    fit: 94,
    value: +6,
    retained: true,
    status: 'star',
    college: 'Alabama',
  },
  {
    id: 'p4',
    name: 'Jack Campbell',
    team: 'DET',
    pos: 'LB',
    year: 2023,
    round: 1,
    pick: 18,
    age: 23,
    lll: 77,
    fit: 88,
    value: +2,
    retained: true,
    status: 'starter',
    college: 'Iowa',
  },
  {
    id: 'p5',
    name: 'Sam LaPorta',
    team: 'DET',
    pos: 'TE',
    year: 2023,
    round: 2,
    pick: 34,
    age: 23,
    lll: 91,
    fit: 95,
    value: +28,
    retained: true,
    status: 'star',
    college: 'Iowa',
  },
  {
    id: 'p6',
    name: 'Brian Branch',
    team: 'DET',
    pos: 'S',
    year: 2023,
    round: 2,
    pick: 45,
    age: 22,
    lll: 88,
    fit: 92,
    value: +22,
    retained: true,
    status: 'star',
    college: 'Alabama',
  },
  {
    id: 'p7',
    name: 'Terrion Arnold',
    team: 'DET',
    pos: 'CB',
    year: 2024,
    round: 1,
    pick: 24,
    age: 21,
    lll: 74,
    fit: 82,
    value: +1,
    retained: true,
    status: 'starter',
    college: 'Alabama',
  },
  {
    id: 'p8',
    name: 'Penei Sewell',
    team: 'DET',
    pos: 'OT',
    year: 2021,
    round: 1,
    pick: 7,
    age: 25,
    lll: 95,
    fit: 99,
    value: +18,
    retained: true,
    status: 'star',
    college: 'Oregon',
  },
  {
    id: 'p9',
    name: 'Levi Onwuzurike',
    team: 'DET',
    pos: 'DT',
    year: 2021,
    round: 2,
    pick: 41,
    age: 27,
    lll: 52,
    fit: 58,
    value: -12,
    retained: true,
    status: 'rotation',
    college: 'Washington',
  },
  {
    id: 'p10',
    name: 'Amon-Ra St. Brown',
    team: 'DET',
    pos: 'WR',
    year: 2021,
    round: 4,
    pick: 112,
    age: 26,
    lll: 96,
    fit: 98,
    value: +62,
    retained: true,
    status: 'star',
    college: 'USC',
  },
];

// Expert grades for picks at the time
const EXPERT_GRADES = {
  p1: {mk: 'A', tj: 'A', db: 'A+', ms: 'A', pz: 'B+', lk: 'A', cs: 'B+', rt: 'A'},
  p2: {mk: 'B', tj: 'C+', db: 'B-', ms: 'C', pz: 'B', lk: 'C+', cs: 'C', rt: 'B-'},
  p3: {mk: 'C+', tj: 'B-', db: 'B', ms: 'B+', pz: 'C', lk: 'B-', cs: 'C-', rt: 'B+'},
  p4: {mk: 'C', tj: 'C+', db: 'C', ms: 'C-', pz: 'D+', lk: 'C', cs: 'D', rt: 'C+'},
  p5: {mk: 'B+', tj: 'A-', db: 'B+', ms: 'A-', pz: 'B', lk: 'B+', cs: 'B-', rt: 'A-'},
  p6: {mk: 'A-', tj: 'A', db: 'A-', ms: 'A', pz: 'B+', lk: 'A-', cs: 'B+', rt: 'A'},
  p7: {mk: 'B', tj: 'B+', db: 'B', ms: 'B+', pz: 'B', lk: 'B', cs: 'B-', rt: 'B+'},
  p8: {mk: 'A', tj: 'A', db: 'A+', ms: 'A', pz: 'A-', lk: 'A', cs: 'A-', rt: 'A'},
  p9: {mk: 'B+', tj: 'B', db: 'B+', ms: 'B', pz: 'B+', lk: 'B+', cs: 'B', rt: 'B'},
  p10: {mk: 'C+', tj: 'C', db: 'C+', ms: 'C', pz: 'C-', lk: 'D+', cs: 'D', rt: 'C+'},
};

// Team draft scores by year — running aggregate
const TEAM_HISTORY = {
  DET: [
    {year: 2019, lll: 58, expertAvg: 71, picks: 8, hits: 2, busts: 3},
    {year: 2020, lll: 54, expertAvg: 68, picks: 9, hits: 2, busts: 4},
    {year: 2021, lll: 84, expertAvg: 73, picks: 8, hits: 4, busts: 1},
    {year: 2022, lll: 81, expertAvg: 78, picks: 8, hits: 4, busts: 1},
    {year: 2023, lll: 89, expertAvg: 82, picks: 8, hits: 5, busts: 0},
    {year: 2024, lll: 78, expertAvg: 80, picks: 7, hits: 3, busts: 0},
    {year: 2025, lll: 72, expertAvg: 76, picks: 7, hits: 0, busts: 0},
  ],
  PHI: [
    {year: 2019, lll: 71, expertAvg: 74, picks: 7, hits: 3, busts: 1},
    {year: 2020, lll: 64, expertAvg: 70, picks: 9, hits: 2, busts: 3},
    {year: 2021, lll: 78, expertAvg: 75, picks: 9, hits: 3, busts: 1},
    {year: 2022, lll: 86, expertAvg: 81, picks: 8, hits: 5, busts: 0},
    {year: 2023, lll: 82, expertAvg: 79, picks: 8, hits: 4, busts: 1},
    {year: 2024, lll: 84, expertAvg: 82, picks: 8, hits: 4, busts: 0},
    {year: 2025, lll: 79, expertAvg: 77, picks: 8, hits: 0, busts: 0},
  ],
  KC: [
    {year: 2019, lll: 75, expertAvg: 76, picks: 7, hits: 3, busts: 1},
    {year: 2020, lll: 72, expertAvg: 74, picks: 7, hits: 3, busts: 1},
    {year: 2021, lll: 68, expertAvg: 72, picks: 8, hits: 2, busts: 2},
    {year: 2022, lll: 81, expertAvg: 78, picks: 10, hits: 4, busts: 1},
    {year: 2023, lll: 76, expertAvg: 75, picks: 8, hits: 3, busts: 1},
    {year: 2024, lll: 73, expertAvg: 78, picks: 7, hits: 3, busts: 0},
    {year: 2025, lll: 70, expertAvg: 74, picks: 7, hits: 0, busts: 0},
  ],
  NYJ: [
    {year: 2019, lll: 48, expertAvg: 65, picks: 6, hits: 1, busts: 3},
    {year: 2020, lll: 52, expertAvg: 70, picks: 9, hits: 2, busts: 3},
    {year: 2021, lll: 44, expertAvg: 72, picks: 9, hits: 1, busts: 5},
    {year: 2022, lll: 68, expertAvg: 74, picks: 8, hits: 3, busts: 2},
    {year: 2023, lll: 56, expertAvg: 71, picks: 7, hits: 2, busts: 2},
    {year: 2024, lll: 51, expertAvg: 68, picks: 6, hits: 1, busts: 2},
    {year: 2025, lll: 62, expertAvg: 70, picks: 7, hits: 0, busts: 0},
  ],
};

// Live news feed
const NEWS_FEED = [
  {
    id: 'n1',
    when: '14m',
    tag: 'OTA',
    team: 'DET',
    headline: 'Hutchinson logs full team session, sources say snap count uncapped',
    delta: '+1.2 LLL',
  },
  {
    id: 'n2',
    when: '47m',
    tag: 'COMBINE',
    team: null,
    headline: 'OT prospect Cole Maddox runs 4.94 — vaults into top-15 LLL board',
    delta: 'New: 86',
  },
  {
    id: 'n3',
    when: '2h',
    tag: 'PRESEASON',
    team: 'PHI',
    headline: 'Eagles 2024 R3 LB earns first-team reps; LLL fit score climbs to 88',
    delta: '+0.8 LLL',
  },
  {
    id: 'n4',
    when: '5h',
    tag: 'NEWS',
    team: 'NYJ',
    headline: 'Jets 2021 first-rounder waived; counted as bust in retroactive grade',
    delta: '-3.1 team',
  },
  {
    id: 'n5',
    when: '8h',
    tag: 'GRADE',
    team: 'DET',
    headline: 'St. Brown class of 2021 redrafted: now goes #4 overall in LLL re-rank',
    delta: 'V/E +62',
  },
  {
    id: 'n6',
    when: '1d',
    tag: 'EXPERT',
    team: null,
    headline: 'Brughler corrects 2023 Gibbs grade C+ → B after 1,400 yard sophomore',
    delta: 'Brughler 81.2',
  },
];

// Year-over-year accuracy for one expert (line chart fodder)
const EXPERT_HISTORY = {
  mk: [62, 68, 71, 70, 74, 76, 78, 81, 79, 78],
  tj: [55, 60, 64, 68, 70, 72, 73, 74, 73, 74],
  db: [70, 72, 74, 76, 78, 80, 82, 83, 81, 81],
  ms: [60, 65, 70, 75, 78, 80, 79, 80, 80, 80],
  pz: [78, 76, 74, 72, 70, 70, 69, 68, 68, 69],
  lk: [70, 71, 72, 72, 73, 73, 73, 72, 72, 72],
  cs: [70, 70, 69, 68, 67, 66, 66, 65, 65, 65],
  rt: [60, 64, 68, 71, 73, 75, 76, 77, 77, 77],
};

window.LLL_DATA = {TEAMS, EXPERTS, PLAYERS, EXPERT_GRADES, TEAM_HISTORY, NEWS_FEED, EXPERT_HISTORY};
