/**
 * Alternative 2026 NFL Draft prospect rankings from PFF, ESPN, NFL.com, and Fox Sports.
 * Top 50 per source — ranks 51–200 fall back to the CBS list in draft-data.ts.
 * Last updated: April 2026 (final pre-draft rankings).
 */

export interface RankedPlayer {
  rank: number;
  playerName: string;
  school: string;
  position: string;
}

/** ESPN 2026 top-50 — final pre-draft board (April 2026). */
export const ESPN_PLAYERS_2026_TOP50: RankedPlayer[] = [
  {rank: 1, playerName: 'Arvell Reese', school: 'Ohio State', position: 'LB'},
  {rank: 2, playerName: 'Fernando Mendoza', school: 'Indiana', position: 'QB'},
  {rank: 3, playerName: 'David Bailey', school: 'Texas Tech', position: 'EDGE'},
  {rank: 4, playerName: 'Jeremiyah Love', school: 'Notre Dame', position: 'RB'},
  {rank: 5, playerName: 'Francis Mauigoa', school: 'Miami (FL)', position: 'OT'},
  {rank: 6, playerName: 'Caleb Downs', school: 'Ohio State', position: 'S'},
  {rank: 7, playerName: 'Sonny Styles', school: 'Ohio State', position: 'LB'},
  {rank: 8, playerName: 'Mansoor Delane', school: 'LSU', position: 'CB'},
  {rank: 9, playerName: 'Rueben Bain Jr.', school: 'Miami (FL)', position: 'EDGE'},
  {rank: 10, playerName: 'Makai Lemon', school: 'USC', position: 'WR'},
  {rank: 11, playerName: 'Kenyon Sadiq', school: 'Oregon', position: 'TE'},
  {rank: 12, playerName: 'Jordyn Tyson', school: 'Arizona State', position: 'WR'},
  {rank: 13, playerName: 'Carnell Tate', school: 'Ohio State', position: 'WR'},
  {rank: 14, playerName: 'Monroe Freeling', school: 'Georgia', position: 'OT'},
  {rank: 15, playerName: 'Olaivavega Ioane', school: 'Penn State', position: 'IOL'},
  {rank: 16, playerName: 'Jermod McCoy', school: 'Tennessee', position: 'CB'},
  {rank: 17, playerName: 'Kadyn Proctor', school: 'Alabama', position: 'OT'},
  {rank: 18, playerName: 'Akheem Mesidor', school: 'Miami (FL)', position: 'EDGE'},
  {rank: 19, playerName: 'Spencer Fano', school: 'Utah', position: 'OT'},
  {rank: 20, playerName: 'Dillon Thieneman', school: 'Oregon', position: 'S'},
  {rank: 21, playerName: 'Emmanuel McNeil-Warren', school: 'Toledo', position: 'S'},
  {rank: 22, playerName: 'Avieon Terrell', school: 'Clemson', position: 'CB'},
  {rank: 23, playerName: 'Denzel Boston', school: 'Washington', position: 'WR'},
  {rank: 24, playerName: 'Omar Cooper Jr.', school: 'Indiana', position: 'WR'},
  {rank: 25, playerName: 'Keldric Faulk', school: 'Auburn', position: 'EDGE'},
  {rank: 26, playerName: 'Kayden McDonald', school: 'Ohio State', position: 'DT'},
  {rank: 27, playerName: 'Peter Woods', school: 'Clemson', position: 'DT'},
  {rank: 28, playerName: 'Caleb Lomu', school: 'Utah', position: 'OT'},
  {rank: 29, playerName: 'Zion Young', school: 'Missouri', position: 'EDGE'},
  {rank: 30, playerName: 'Cashius Howell', school: 'Texas A&M', position: 'EDGE'},
  {rank: 31, playerName: 'Colton Hood', school: 'Tennessee', position: 'CB'},
  {rank: 32, playerName: 'KC Concepcion', school: 'Texas A&M', position: 'WR'},
  {rank: 33, playerName: 'Chase Bisontis', school: 'Texas A&M', position: 'IOL'},
  {rank: 34, playerName: 'Caleb Banks', school: 'Florida', position: 'DT'},
  {rank: 35, playerName: 'Anthony Hill Jr.', school: 'Texas', position: 'LB'},
  {rank: 36, playerName: 'Eli Stowers', school: 'Vanderbilt', position: 'TE'},
  {rank: 37, playerName: 'Ty Simpson', school: 'Alabama', position: 'QB'},
  {rank: 38, playerName: 'Brandon Cisse', school: 'South Carolina', position: 'CB'},
  {rank: 39, playerName: 'Chris Johnson', school: 'San Diego State', position: 'CB'},
  {rank: 40, playerName: 'Zachariah Branch', school: 'Georgia', position: 'WR'},
  {rank: 41, playerName: 'Max Iheanachor', school: 'Arizona State', position: 'OT'},
  {rank: 42, playerName: 'Chris Brazzell II', school: 'Tennessee', position: 'WR'},
  {rank: 43, playerName: 'Germie Bernard', school: 'Alabama', position: 'WR'},
  {rank: 44, playerName: 'Gabe Jacas', school: 'Illinois', position: 'EDGE'},
  {rank: 45, playerName: 'C.J. Allen', school: 'Georgia', position: 'LB'},
  {rank: 46, playerName: 'Jacob Rodriguez', school: 'Texas Tech', position: 'LB'},
  {rank: 47, playerName: 'Emmanuel Pregnon', school: 'Oregon', position: 'IOL'},
  {rank: 48, playerName: 'Keionte Scott', school: 'Miami (FL)', position: 'S'},
  {rank: 49, playerName: 'Christen Miller', school: 'Georgia', position: 'DT'},
  {rank: 50, playerName: 'Jadarian Price', school: 'Notre Dame', position: 'RB'},
];

/** NFL.com 2026 top-50 — Daniel Jeremiah 4.0 (April 2026). */
export const NFL_PLAYERS_2026_TOP50: RankedPlayer[] = [
  {rank: 1, playerName: 'Fernando Mendoza', school: 'Indiana', position: 'QB'},
  {rank: 2, playerName: 'Jeremiyah Love', school: 'Notre Dame', position: 'RB'},
  {rank: 3, playerName: 'Sonny Styles', school: 'Ohio State', position: 'LB'},
  {rank: 4, playerName: 'David Bailey', school: 'Texas Tech', position: 'EDGE'},
  {rank: 5, playerName: 'Arvell Reese', school: 'Ohio State', position: 'EDGE'},
  {rank: 6, playerName: 'Carnell Tate', school: 'Ohio State', position: 'WR'},
  {rank: 7, playerName: 'Rueben Bain Jr.', school: 'Miami (FL)', position: 'EDGE'},
  {rank: 8, playerName: 'Mansoor Delane', school: 'LSU', position: 'CB'},
  {rank: 9, playerName: 'Caleb Downs', school: 'Ohio State', position: 'S'},
  {rank: 10, playerName: 'Francis Mauigoa', school: 'Miami (FL)', position: 'OT'},
  {rank: 11, playerName: 'Olaivavega Ioane', school: 'Penn State', position: 'IOL'},
  {rank: 12, playerName: 'Makai Lemon', school: 'USC', position: 'WR'},
  {rank: 13, playerName: 'Spencer Fano', school: 'Utah', position: 'IOL'},
  {rank: 14, playerName: 'Kenyon Sadiq', school: 'Oregon', position: 'TE'},
  {rank: 15, playerName: 'Jermod McCoy', school: 'Tennessee', position: 'CB'},
  {rank: 16, playerName: 'Emmanuel McNeil-Warren', school: 'Toledo', position: 'S'},
  {rank: 17, playerName: 'Dillon Thieneman', school: 'Oregon', position: 'S'},
  {rank: 18, playerName: 'Omar Cooper Jr.', school: 'Indiana', position: 'WR'},
  {rank: 19, playerName: 'Blake Miller', school: 'Clemson', position: 'OT'},
  {rank: 20, playerName: 'Monroe Freeling', school: 'Georgia', position: 'OT'},
  {rank: 21, playerName: 'Jordyn Tyson', school: 'Arizona State', position: 'WR'},
  {rank: 22, playerName: 'Kadyn Proctor', school: 'Alabama', position: 'OT'},
  {rank: 23, playerName: 'Akheem Mesidor', school: 'Miami (FL)', position: 'EDGE'},
  {rank: 24, playerName: 'T.J. Parker', school: 'Clemson', position: 'EDGE'},
  {rank: 25, playerName: 'Colton Hood', school: 'Tennessee', position: 'CB'},
  {rank: 26, playerName: 'Caleb Lomu', school: 'Utah', position: 'OT'},
  {rank: 27, playerName: 'Denzel Boston', school: 'Washington', position: 'WR'},
  {rank: 28, playerName: 'Cashius Howell', school: 'Texas A&M', position: 'EDGE'},
  {rank: 29, playerName: 'KC Concepcion', school: 'Texas A&M', position: 'WR'},
  {rank: 30, playerName: 'C.J. Allen', school: 'Georgia', position: 'LB'},
  {rank: 31, playerName: 'Keldric Faulk', school: 'Auburn', position: 'EDGE'},
  {rank: 32, playerName: 'Anthony Hill Jr.', school: 'Texas', position: 'LB'},
  {rank: 33, playerName: 'Kayden McDonald', school: 'Ohio State', position: 'DT'},
  {rank: 34, playerName: 'Avieon Terrell', school: 'Clemson', position: 'CB'},
  {rank: 35, playerName: 'Max Iheanachor', school: 'Arizona State', position: 'OT'},
  {rank: 36, playerName: 'Lee Hunter', school: 'Texas Tech', position: 'DT'},
  {rank: 37, playerName: 'Peter Woods', school: 'Clemson', position: 'DT'},
  {rank: 38, playerName: 'Ty Simpson', school: 'Alabama', position: 'QB'},
  {rank: 39, playerName: 'Jadarian Price', school: 'Notre Dame', position: 'RB'},
  {rank: 40, playerName: 'Chris Johnson', school: 'San Diego State', position: 'CB'},
  {rank: 41, playerName: 'Jacob Rodriguez', school: 'Texas Tech', position: 'LB'},
  {rank: 42, playerName: 'Caleb Banks', school: 'Florida', position: 'DT'},
  {rank: 43, playerName: 'Brandon Cisse', school: 'South Carolina', position: 'CB'},
  {rank: 44, playerName: 'Keionte Scott', school: 'Miami (FL)', position: 'CB'},
  {rank: 45, playerName: 'Zion Young', school: 'Missouri', position: 'EDGE'},
  {rank: 46, playerName: 'Malachi Lawrence', school: 'UCF', position: 'EDGE'},
  {rank: 47, playerName: 'Keylan Rutledge', school: 'Georgia Tech', position: 'IOL'},
  {rank: 48, playerName: 'Antonio Williams', school: 'Clemson', position: 'WR'},
  {rank: 49, playerName: 'R Mason Thomas', school: 'Oklahoma', position: 'EDGE'},
  {rank: 50, playerName: 'Germie Bernard', school: 'Alabama', position: 'WR'},
];

/** PFF 2026 big board top-50 — final pre-draft (April 2026). */
export const PFF_PLAYERS_2026_TOP50: RankedPlayer[] = [
  {rank: 1, playerName: 'Fernando Mendoza', school: 'Indiana', position: 'QB'},
  {rank: 2, playerName: 'Arvell Reese', school: 'Ohio State', position: 'LB'},
  {rank: 3, playerName: 'Jeremiyah Love', school: 'Notre Dame', position: 'RB'},
  {rank: 4, playerName: 'Sonny Styles', school: 'Ohio State', position: 'LB'},
  {rank: 5, playerName: 'Rueben Bain Jr.', school: 'Miami (FL)', position: 'EDGE'},
  {rank: 6, playerName: 'David Bailey', school: 'Texas Tech', position: 'EDGE'},
  {rank: 7, playerName: 'Francis Mauigoa', school: 'Miami (FL)', position: 'OT'},
  {rank: 8, playerName: 'Caleb Downs', school: 'Ohio State', position: 'S'},
  {rank: 9, playerName: 'Mansoor Delane', school: 'LSU', position: 'CB'},
  {rank: 10, playerName: 'Carnell Tate', school: 'Ohio State', position: 'WR'},
  {rank: 11, playerName: 'Dillon Thieneman', school: 'Oregon', position: 'S'},
  {rank: 12, playerName: 'Spencer Fano', school: 'Utah', position: 'OT'},
  {rank: 13, playerName: 'Monroe Freeling', school: 'Georgia', position: 'OT'},
  {rank: 14, playerName: 'Kenyon Sadiq', school: 'Oregon', position: 'TE'},
  {rank: 15, playerName: 'Makai Lemon', school: 'USC', position: 'WR'},
  {rank: 16, playerName: 'Olaivavega Ioane', school: 'Penn State', position: 'IOL'},
  {rank: 17, playerName: 'Jermod McCoy', school: 'Tennessee', position: 'CB'},
  {rank: 18, playerName: 'C.J. Allen', school: 'Georgia', position: 'LB'},
  {rank: 19, playerName: 'Jordyn Tyson', school: 'Arizona State', position: 'WR'},
  {rank: 20, playerName: 'Akheem Mesidor', school: 'Miami (FL)', position: 'EDGE'},
  {rank: 21, playerName: 'Emmanuel McNeil-Warren', school: 'Toledo', position: 'S'},
  {rank: 22, playerName: 'Keldric Faulk', school: 'Auburn', position: 'EDGE'},
  {rank: 23, playerName: 'Avieon Terrell', school: 'Clemson', position: 'CB'},
  {rank: 24, playerName: 'Omar Cooper Jr.', school: 'Indiana', position: 'WR'},
  {rank: 25, playerName: 'Blake Miller', school: 'Clemson', position: 'OT'},
  {rank: 26, playerName: 'Cashius Howell', school: 'Texas A&M', position: 'EDGE'},
  {rank: 27, playerName: 'Kadyn Proctor', school: 'Alabama', position: 'OT'},
  {rank: 28, playerName: 'Kayden McDonald', school: 'Ohio State', position: 'DT'},
  {rank: 29, playerName: 'T.J. Parker', school: 'Clemson', position: 'EDGE'},
  {rank: 30, playerName: 'Max Iheanachor', school: 'Arizona State', position: 'OT'},
  {rank: 31, playerName: 'Denzel Boston', school: 'Washington', position: 'WR'},
  {rank: 32, playerName: 'Caleb Banks', school: 'Florida', position: 'DT'},
  {rank: 33, playerName: 'Peter Woods', school: 'Clemson', position: 'DT'},
  {rank: 34, playerName: 'Colton Hood', school: 'Tennessee', position: 'CB'},
  {rank: 35, playerName: 'KC Concepcion', school: 'Texas A&M', position: 'WR'},
  {rank: 36, playerName: 'Emmanuel Pregnon', school: 'Oregon', position: 'IOL'},
  {rank: 37, playerName: 'Christen Miller', school: 'Georgia', position: 'DT'},
  {rank: 38, playerName: 'Caleb Lomu', school: 'Utah', position: 'OT'},
  {rank: 39, playerName: 'Lee Hunter', school: 'Texas Tech', position: 'DT'},
  {rank: 40, playerName: 'Zion Young', school: 'Missouri', position: 'EDGE'},
  {rank: 41, playerName: 'Brandon Cisse', school: 'South Carolina', position: 'CB'},
  {rank: 42, playerName: 'Ty Simpson', school: 'Alabama', position: 'QB'},
  {rank: 43, playerName: "D'Angelo Ponds", school: 'Indiana', position: 'CB'},
  {rank: 44, playerName: 'Chris Bell', school: 'Louisville', position: 'WR'},
  {rank: 45, playerName: 'Jacob Rodriguez', school: 'Texas Tech', position: 'LB'},
  {rank: 46, playerName: 'Chris Johnson', school: 'San Diego State', position: 'CB'},
  {rank: 47, playerName: 'R Mason Thomas', school: 'Oklahoma', position: 'EDGE'},
  {rank: 48, playerName: 'Chase Bisontis', school: 'Texas A&M', position: 'IOL'},
  {rank: 49, playerName: 'Germie Bernard', school: 'Alabama', position: 'WR'},
  {rank: 50, playerName: 'Keith Abney II', school: 'Arizona State', position: 'CB'},
];

/** Fox Sports 2026 top-50 — final pre-draft board (April 2026). */
export const FOX_PLAYERS_2026_TOP50: RankedPlayer[] = [
  {rank: 1, playerName: 'Caleb Downs', school: 'Ohio State', position: 'S'},
  {rank: 2, playerName: 'Arvell Reese', school: 'Ohio State', position: 'LB'},
  {rank: 3, playerName: 'Jeremiyah Love', school: 'Notre Dame', position: 'RB'},
  {rank: 4, playerName: 'Fernando Mendoza', school: 'Indiana', position: 'QB'},
  {rank: 5, playerName: 'David Bailey', school: 'Texas Tech', position: 'EDGE'},
  {rank: 6, playerName: 'Francis Mauigoa', school: 'Miami (FL)', position: 'OT'},
  {rank: 7, playerName: 'Rueben Bain Jr.', school: 'Miami (FL)', position: 'EDGE'},
  {rank: 8, playerName: 'Sonny Styles', school: 'Ohio State', position: 'LB'},
  {rank: 9, playerName: 'Spencer Fano', school: 'Utah', position: 'OT'},
  {rank: 10, playerName: 'Mansoor Delane', school: 'LSU', position: 'CB'},
  {rank: 11, playerName: 'Carnell Tate', school: 'Ohio State', position: 'WR'},
  {rank: 12, playerName: 'Olaivavega Ioane', school: 'Penn State', position: 'IOL'},
  {rank: 13, playerName: 'Monroe Freeling', school: 'Georgia', position: 'OT'},
  {rank: 14, playerName: 'Jermod McCoy', school: 'Tennessee', position: 'CB'},
  {rank: 15, playerName: 'Keldric Faulk', school: 'Auburn', position: 'EDGE'},
  {rank: 16, playerName: 'Makai Lemon', school: 'USC', position: 'WR'},
  {rank: 17, playerName: 'Kenyon Sadiq', school: 'Oregon', position: 'TE'},
  {rank: 18, playerName: 'Jordyn Tyson', school: 'Arizona State', position: 'WR'},
  {rank: 19, playerName: 'Kadyn Proctor', school: 'Alabama', position: 'OT'},
  {rank: 20, playerName: 'KC Concepcion', school: 'Texas A&M', position: 'WR'},
  {rank: 21, playerName: 'Colton Hood', school: 'Tennessee', position: 'CB'},
  {rank: 22, playerName: 'Blake Miller', school: 'Clemson', position: 'OT'},
  {rank: 23, playerName: 'Dillon Thieneman', school: 'Oregon', position: 'S'},
  {rank: 24, playerName: 'Caleb Banks', school: 'Florida', position: 'DT'},
  {rank: 25, playerName: 'Cashius Howell', school: 'Texas A&M', position: 'EDGE'},
  {rank: 26, playerName: 'Denzel Boston', school: 'Washington', position: 'WR'},
  {rank: 27, playerName: 'T.J. Parker', school: 'Clemson', position: 'EDGE'},
  {rank: 28, playerName: 'Chris Johnson', school: 'San Diego State', position: 'CB'},
  {rank: 29, playerName: 'Kayden McDonald', school: 'Ohio State', position: 'DT'},
  {rank: 30, playerName: 'Emmanuel McNeil-Warren', school: 'Toledo', position: 'S'},
  {rank: 31, playerName: 'Max Iheanachor', school: 'Arizona State', position: 'OT'},
  {rank: 32, playerName: 'Gabe Jacas', school: 'Illinois', position: 'EDGE'},
  {rank: 33, playerName: 'Ty Simpson', school: 'Alabama', position: 'QB'},
  {rank: 34, playerName: 'Brandon Cisse', school: 'South Carolina', position: 'CB'},
  {rank: 35, playerName: 'Akheem Mesidor', school: 'Miami (FL)', position: 'EDGE'},
  {rank: 36, playerName: 'C.J. Allen', school: 'Georgia', position: 'LB'},
  {rank: 37, playerName: 'Zion Young', school: 'Missouri', position: 'EDGE'},
  {rank: 38, playerName: 'Jadarian Price', school: 'Notre Dame', position: 'RB'},
  {rank: 39, playerName: 'Peter Woods', school: 'Clemson', position: 'DT'},
  {rank: 40, playerName: 'Omar Cooper Jr.', school: 'Indiana', position: 'WR'},
  {rank: 41, playerName: 'Anthony Hill Jr.', school: 'Texas', position: 'LB'},
  {rank: 42, playerName: 'Chase Bisontis', school: 'Texas A&M', position: 'IOL'},
  {rank: 43, playerName: 'Caleb Lomu', school: 'Utah', position: 'OT'},
  {rank: 44, playerName: 'Christen Miller', school: 'Georgia', position: 'DT'},
  {rank: 45, playerName: "D'Angelo Ponds", school: 'Indiana', position: 'CB'},
  {rank: 46, playerName: 'A.J. Haulcy', school: 'LSU', position: 'S'},
  {rank: 47, playerName: 'R Mason Thomas', school: 'Oklahoma', position: 'EDGE'},
  {rank: 48, playerName: 'Keylan Rutledge', school: 'Georgia Tech', position: 'IOL'},
  {rank: 49, playerName: 'Keionte Scott', school: 'Miami (FL)', position: 'S'},
  {rank: 50, playerName: 'Malachi Lawrence', school: 'UCF', position: 'EDGE'},
];
