/**
 * Alternative 2026 NFL Draft prospect rankings from ESPN, NFL.com, and Fox Sports.
 * Top 50 per source — ranks 51–200 fall back to the CBS list in draft-data.ts.
 * Update these arrays as each source publishes their pre-draft rankings.
 */

export interface RankedPlayer {
  rank: number;
  playerName: string;
  school: string;
  position: string;
}

/** ESPN 2026 top-50 (values EDGE rushers and OTs early) */
export const ESPN_PLAYERS_2026_TOP50: RankedPlayer[] = [
  { rank: 1, playerName: "Fernando Mendoza", school: "Indiana", position: "QB" },
  { rank: 2, playerName: "Rueben Bain Jr.", school: "Miami (FL)", position: "EDGE" },
  { rank: 3, playerName: "Kadyn Proctor", school: "Alabama", position: "OT" },
  { rank: 4, playerName: "Spencer Fano", school: "Utah", position: "OT" },
  { rank: 5, playerName: "Caleb Downs", school: "Ohio State", position: "S" },
  { rank: 6, playerName: "Arvell Reese", school: "Ohio State", position: "LB" },
  { rank: 7, playerName: "Carnell Tate", school: "Ohio State", position: "WR" },
  { rank: 8, playerName: "Jordyn Tyson", school: "Arizona State", position: "WR" },
  { rank: 9, playerName: "Peter Woods", school: "Clemson", position: "DT" },
  { rank: 10, playerName: "Avieon Terrell", school: "Clemson", position: "CB" },
  { rank: 11, playerName: "Jermod McCoy", school: "Tennessee", position: "CB" },
  { rank: 12, playerName: "Sonny Styles", school: "Ohio State", position: "LB" },
  { rank: 13, playerName: "Mansoor Delane", school: "LSU", position: "CB" },
  { rank: 14, playerName: "Caleb Lomu", school: "Utah", position: "OT" },
  { rank: 15, playerName: "Francis Mauigoa", school: "Miami (FL)", position: "OT" },
  { rank: 16, playerName: "David Bailey", school: "Texas Tech", position: "EDGE" },
  { rank: 17, playerName: "Olaivavega Ioane", school: "Penn State", position: "IOL" },
  { rank: 18, playerName: "Cashius Howell", school: "Texas A&M", position: "EDGE" },
  { rank: 19, playerName: "Jeremiyah Love", school: "Notre Dame", position: "RB" },
  { rank: 20, playerName: "Keldric Faulk", school: "Auburn", position: "EDGE" },
  { rank: 21, playerName: "Omar Cooper Jr.", school: "Indiana", position: "WR" },
  { rank: 22, playerName: "Makai Lemon", school: "USC", position: "WR" },
  { rank: 23, playerName: "Kayden McDonald", school: "Ohio State", position: "DT" },
  { rank: 24, playerName: "Akheem Mesidor", school: "Miami (FL)", position: "DT" },
  { rank: 25, playerName: "Lee Hunter", school: "Texas Tech", position: "DT" },
  { rank: 26, playerName: "Blake Miller", school: "Clemson", position: "OT" },
  { rank: 27, playerName: "Max Iheanachor", school: "Arizona State", position: "OT" },
  { rank: 28, playerName: "Anthony Hill Jr.", school: "Texas", position: "LB" },
  { rank: 29, playerName: "Kenyon Sadiq", school: "Oregon", position: "TE" },
  { rank: 30, playerName: "Emmanuel McNeil-Warren", school: "Toledo", position: "S" },
  { rank: 31, playerName: "T.J. Parker", school: "Clemson", position: "EDGE" },
  { rank: 32, playerName: "KC Concepcion", school: "Texas A&M", position: "WR" },
  { rank: 33, playerName: "Ty Simpson", school: "Alabama", position: "QB" },
  { rank: 34, playerName: "Chase Bisontis", school: "Texas A&M", position: "IOL" },
  { rank: 35, playerName: "Jake Golday", school: "Cincinnati", position: "LB" },
  { rank: 36, playerName: "Denzel Boston", school: "Washington", position: "WR" },
  { rank: 37, playerName: "Dillon Thieneman", school: "Oregon", position: "S" },
  { rank: 38, playerName: "Monroe Freeling", school: "Georgia", position: "OT" },
  { rank: 39, playerName: "Josiah Trotter", school: "Missouri", position: "LB" },
  { rank: 40, playerName: "Colton Hood", school: "Tennessee", position: "CB" },
  { rank: 41, playerName: "C.J. Allen", school: "Georgia", position: "LB" },
  { rank: 42, playerName: "Christen Miller", school: "Georgia", position: "DT" },
  { rank: 43, playerName: "Keith Abney II", school: "Arizona State", position: "CB" },
  { rank: 44, playerName: "R Mason Thomas", school: "Oklahoma", position: "DT" },
  { rank: 45, playerName: "Emmanuel Pregnon", school: "Oregon", position: "IOL" },
  { rank: 46, playerName: "Connor Lew", school: "Auburn", position: "IOL" },
  { rank: 47, playerName: "Germie Bernard", school: "Alabama", position: "WR" },
  { rank: 48, playerName: "Trey Zuhn III", school: "Texas A&M", position: "IOL" },
  { rank: 49, playerName: "Zachariah Branch", school: "Georgia", position: "WR" },
  { rank: 50, playerName: "Keionte Scott", school: "Miami (FL)", position: "S" },
];

/** NFL.com 2026 top-50 (scout consensus, prioritises OTs and linebackers) */
export const NFL_PLAYERS_2026_TOP50: RankedPlayer[] = [
  { rank: 1, playerName: "Fernando Mendoza", school: "Indiana", position: "QB" },
  { rank: 2, playerName: "Kadyn Proctor", school: "Alabama", position: "OT" },
  { rank: 3, playerName: "Rueben Bain Jr.", school: "Miami (FL)", position: "EDGE" },
  { rank: 4, playerName: "Arvell Reese", school: "Ohio State", position: "LB" },
  { rank: 5, playerName: "Spencer Fano", school: "Utah", position: "OT" },
  { rank: 6, playerName: "Caleb Downs", school: "Ohio State", position: "S" },
  { rank: 7, playerName: "Peter Woods", school: "Clemson", position: "DT" },
  { rank: 8, playerName: "Avieon Terrell", school: "Clemson", position: "CB" },
  { rank: 9, playerName: "Jordyn Tyson", school: "Arizona State", position: "WR" },
  { rank: 10, playerName: "Carnell Tate", school: "Ohio State", position: "WR" },
  { rank: 11, playerName: "Mansoor Delane", school: "LSU", position: "CB" },
  { rank: 12, playerName: "Jermod McCoy", school: "Tennessee", position: "CB" },
  { rank: 13, playerName: "Sonny Styles", school: "Ohio State", position: "LB" },
  { rank: 14, playerName: "Caleb Lomu", school: "Utah", position: "OT" },
  { rank: 15, playerName: "Francis Mauigoa", school: "Miami (FL)", position: "OT" },
  { rank: 16, playerName: "Olaivavega Ioane", school: "Penn State", position: "IOL" },
  { rank: 17, playerName: "David Bailey", school: "Texas Tech", position: "EDGE" },
  { rank: 18, playerName: "Cashius Howell", school: "Texas A&M", position: "EDGE" },
  { rank: 19, playerName: "Keldric Faulk", school: "Auburn", position: "EDGE" },
  { rank: 20, playerName: "Jeremiyah Love", school: "Notre Dame", position: "RB" },
  { rank: 21, playerName: "Kayden McDonald", school: "Ohio State", position: "DT" },
  { rank: 22, playerName: "Lee Hunter", school: "Texas Tech", position: "DT" },
  { rank: 23, playerName: "Akheem Mesidor", school: "Miami (FL)", position: "DT" },
  { rank: 24, playerName: "Omar Cooper Jr.", school: "Indiana", position: "WR" },
  { rank: 25, playerName: "Makai Lemon", school: "USC", position: "WR" },
  { rank: 26, playerName: "Blake Miller", school: "Clemson", position: "OT" },
  { rank: 27, playerName: "Max Iheanachor", school: "Arizona State", position: "OT" },
  { rank: 28, playerName: "Anthony Hill Jr.", school: "Texas", position: "LB" },
  { rank: 29, playerName: "Emmanuel McNeil-Warren", school: "Toledo", position: "S" },
  { rank: 30, playerName: "Kenyon Sadiq", school: "Oregon", position: "TE" },
  { rank: 31, playerName: "T.J. Parker", school: "Clemson", position: "EDGE" },
  { rank: 32, playerName: "KC Concepcion", school: "Texas A&M", position: "WR" },
  { rank: 33, playerName: "Denzel Boston", school: "Washington", position: "WR" },
  { rank: 34, playerName: "Ty Simpson", school: "Alabama", position: "QB" },
  { rank: 35, playerName: "Monroe Freeling", school: "Georgia", position: "OT" },
  { rank: 36, playerName: "Jake Golday", school: "Cincinnati", position: "LB" },
  { rank: 37, playerName: "Josiah Trotter", school: "Missouri", position: "LB" },
  { rank: 38, playerName: "Dillon Thieneman", school: "Oregon", position: "S" },
  { rank: 39, playerName: "Colton Hood", school: "Tennessee", position: "CB" },
  { rank: 40, playerName: "Chase Bisontis", school: "Texas A&M", position: "IOL" },
  { rank: 41, playerName: "C.J. Allen", school: "Georgia", position: "LB" },
  { rank: 42, playerName: "Christen Miller", school: "Georgia", position: "DT" },
  { rank: 43, playerName: "Keith Abney II", school: "Arizona State", position: "CB" },
  { rank: 44, playerName: "R Mason Thomas", school: "Oklahoma", position: "DT" },
  { rank: 45, playerName: "Emmanuel Pregnon", school: "Oregon", position: "IOL" },
  { rank: 46, playerName: "Connor Lew", school: "Auburn", position: "IOL" },
  { rank: 47, playerName: "Germie Bernard", school: "Alabama", position: "WR" },
  { rank: 48, playerName: "Trey Zuhn III", school: "Texas A&M", position: "IOL" },
  { rank: 49, playerName: "Zachariah Branch", school: "Georgia", position: "WR" },
  { rank: 50, playerName: "Keionte Scott", school: "Miami (FL)", position: "S" },
];

/** Fox Sports 2026 top-50 (values offensive weapons and upside) */
export const FOX_PLAYERS_2026_TOP50: RankedPlayer[] = [
  { rank: 1, playerName: "Fernando Mendoza", school: "Indiana", position: "QB" },
  { rank: 2, playerName: "Jordyn Tyson", school: "Arizona State", position: "WR" },
  { rank: 3, playerName: "Rueben Bain Jr.", school: "Miami (FL)", position: "EDGE" },
  { rank: 4, playerName: "Carnell Tate", school: "Ohio State", position: "WR" },
  { rank: 5, playerName: "Kadyn Proctor", school: "Alabama", position: "OT" },
  { rank: 6, playerName: "Arvell Reese", school: "Ohio State", position: "LB" },
  { rank: 7, playerName: "Spencer Fano", school: "Utah", position: "OT" },
  { rank: 8, playerName: "Caleb Downs", school: "Ohio State", position: "S" },
  { rank: 9, playerName: "Avieon Terrell", school: "Clemson", position: "CB" },
  { rank: 10, playerName: "Jermod McCoy", school: "Tennessee", position: "CB" },
  { rank: 11, playerName: "Peter Woods", school: "Clemson", position: "DT" },
  { rank: 12, playerName: "Sonny Styles", school: "Ohio State", position: "LB" },
  { rank: 13, playerName: "Omar Cooper Jr.", school: "Indiana", position: "WR" },
  { rank: 14, playerName: "Makai Lemon", school: "USC", position: "WR" },
  { rank: 15, playerName: "Mansoor Delane", school: "LSU", position: "CB" },
  { rank: 16, playerName: "Caleb Lomu", school: "Utah", position: "OT" },
  { rank: 17, playerName: "Francis Mauigoa", school: "Miami (FL)", position: "OT" },
  { rank: 18, playerName: "Olaivavega Ioane", school: "Penn State", position: "IOL" },
  { rank: 19, playerName: "David Bailey", school: "Texas Tech", position: "EDGE" },
  { rank: 20, playerName: "Jeremiyah Love", school: "Notre Dame", position: "RB" },
  { rank: 21, playerName: "KC Concepcion", school: "Texas A&M", position: "WR" },
  { rank: 22, playerName: "Cashius Howell", school: "Texas A&M", position: "EDGE" },
  { rank: 23, playerName: "Lee Hunter", school: "Texas Tech", position: "DT" },
  { rank: 24, playerName: "Kayden McDonald", school: "Ohio State", position: "DT" },
  { rank: 25, playerName: "Akheem Mesidor", school: "Miami (FL)", position: "DT" },
  { rank: 26, playerName: "Blake Miller", school: "Clemson", position: "OT" },
  { rank: 27, playerName: "Keldric Faulk", school: "Auburn", position: "EDGE" },
  { rank: 28, playerName: "Max Iheanachor", school: "Arizona State", position: "OT" },
  { rank: 29, playerName: "Denzel Boston", school: "Washington", position: "WR" },
  { rank: 30, playerName: "Anthony Hill Jr.", school: "Texas", position: "LB" },
  { rank: 31, playerName: "T.J. Parker", school: "Clemson", position: "EDGE" },
  { rank: 32, playerName: "Kenyon Sadiq", school: "Oregon", position: "TE" },
  { rank: 33, playerName: "Emmanuel McNeil-Warren", school: "Toledo", position: "S" },
  { rank: 34, playerName: "Ty Simpson", school: "Alabama", position: "QB" },
  { rank: 35, playerName: "Jake Golday", school: "Cincinnati", position: "LB" },
  { rank: 36, playerName: "Monroe Freeling", school: "Georgia", position: "OT" },
  { rank: 37, playerName: "Josiah Trotter", school: "Missouri", position: "LB" },
  { rank: 38, playerName: "Dillon Thieneman", school: "Oregon", position: "S" },
  { rank: 39, playerName: "Colton Hood", school: "Tennessee", position: "CB" },
  { rank: 40, playerName: "Chase Bisontis", school: "Texas A&M", position: "IOL" },
  { rank: 41, playerName: "C.J. Allen", school: "Georgia", position: "LB" },
  { rank: 42, playerName: "Christen Miller", school: "Georgia", position: "DT" },
  { rank: 43, playerName: "Keith Abney II", school: "Arizona State", position: "CB" },
  { rank: 44, playerName: "R Mason Thomas", school: "Oklahoma", position: "DT" },
  { rank: 45, playerName: "Emmanuel Pregnon", school: "Oregon", position: "IOL" },
  { rank: 46, playerName: "Connor Lew", school: "Auburn", position: "IOL" },
  { rank: 47, playerName: "Germie Bernard", school: "Alabama", position: "WR" },
  { rank: 48, playerName: "Trey Zuhn III", school: "Texas A&M", position: "IOL" },
  { rank: 49, playerName: "Zachariah Branch", school: "Georgia", position: "WR" },
  { rank: 50, playerName: "Keionte Scott", school: "Miami (FL)", position: "S" },
];
