/**
 * Alternative 2026 NFL Draft prospect rankings from PFF, ESPN, NFL.com, and Fox Sports.
 * Top 50 per source — ranks 51–200 fall back to the CBS list in draft-data.ts.
 * Last updated: Post-2026 NFL Combine (Indianapolis, Feb 27–Mar 2 2026).
 *
 * Key combine movers:
 *  RISERS — Sonny Styles (10.00 RAS, top-3 lock), Arvell Reese (4.47, top-5 cement),
 *            David Bailey (4.51, possible #2 overall), Kenyon Sadiq (TE-record 4.39, top-20),
 *            Jeremiyah Love (4.36, top-3 overall buzz), Dillon Thieneman (4.35, 41" vert),
 *            Caleb Banks (first-round locked), Max Iheanachor (4.91, first-round buzz),
 *            Zachariah Branch (4.35), Zavion Thomas (4.28 — new addition).
 *  FALLERS — Cashius Howell (30¼" arms; first-round questions), Emmanuel McNeil-Warren (4.52, 35.5" vert).
 */

export interface RankedPlayer {
  rank: number;
  playerName: string;
  school: string;
  position: string;
}

/** ESPN 2026 top-50 — post-combine update (March 2026). Values EDGE rushers, OTs, and athleticism early. */
export const ESPN_PLAYERS_2026_TOP50: RankedPlayer[] = [
  { rank: 1, playerName: "Fernando Mendoza", school: "Indiana", position: "QB" },
  { rank: 2, playerName: "Sonny Styles", school: "Ohio State", position: "LB" },
  { rank: 3, playerName: "Arvell Reese", school: "Ohio State", position: "EDGE" },
  { rank: 4, playerName: "David Bailey", school: "Texas Tech", position: "EDGE" },
  { rank: 5, playerName: "Rueben Bain Jr.", school: "Miami (FL)", position: "EDGE" },
  { rank: 6, playerName: "Spencer Fano", school: "Utah", position: "OT" },
  { rank: 7, playerName: "Jeremiyah Love", school: "Notre Dame", position: "RB" },
  { rank: 8, playerName: "Caleb Downs", school: "Ohio State", position: "S" },
  { rank: 9, playerName: "Carnell Tate", school: "Ohio State", position: "WR" },
  { rank: 10, playerName: "Jordyn Tyson", school: "Arizona State", position: "WR" },
  { rank: 11, playerName: "Kenyon Sadiq", school: "Oregon", position: "TE" },
  { rank: 12, playerName: "Francis Mauigoa", school: "Miami (FL)", position: "OT" },
  { rank: 13, playerName: "Peter Woods", school: "Clemson", position: "DT" },
  { rank: 14, playerName: "Jermod McCoy", school: "Tennessee", position: "CB" },
  { rank: 15, playerName: "Mansoor Delane", school: "LSU", position: "CB" },
  { rank: 16, playerName: "Kadyn Proctor", school: "Alabama", position: "OT" },
  { rank: 17, playerName: "Caleb Lomu", school: "Utah", position: "OT" },
  { rank: 18, playerName: "Dillon Thieneman", school: "Oregon", position: "S" },
  { rank: 19, playerName: "Keldric Faulk", school: "Auburn", position: "EDGE" },
  { rank: 20, playerName: "Caleb Banks", school: "Florida", position: "DT" },
  { rank: 21, playerName: "Avieon Terrell", school: "Clemson", position: "CB" },
  { rank: 22, playerName: "Omar Cooper Jr.", school: "Indiana", position: "WR" },
  { rank: 23, playerName: "Olaivavega Ioane", school: "Penn State", position: "IOL" },
  { rank: 24, playerName: "Makai Lemon", school: "USC", position: "WR" },
  { rank: 25, playerName: "Zachariah Branch", school: "Georgia", position: "WR" },
  { rank: 26, playerName: "Zavion Thomas", school: "LSU", position: "WR" },
  { rank: 27, playerName: "Daylen Everette", school: "Georgia", position: "CB" },
  { rank: 28, playerName: "Kayden McDonald", school: "Ohio State", position: "DT" },
  { rank: 29, playerName: "T.J. Parker", school: "Clemson", position: "EDGE" },
  { rank: 30, playerName: "Akheem Mesidor", school: "Miami (FL)", position: "DT" },
  { rank: 31, playerName: "Max Iheanachor", school: "Arizona State", position: "OT" },
  { rank: 32, playerName: "Lee Hunter", school: "Texas Tech", position: "DT" },
  { rank: 33, playerName: "Ty Simpson", school: "Alabama", position: "QB" },
  { rank: 34, playerName: "Blake Miller", school: "Clemson", position: "OT" },
  { rank: 35, playerName: "Chris Brazzell II", school: "Tennessee", position: "WR" },
  { rank: 36, playerName: "Anthony Hill Jr.", school: "Texas", position: "LB" },
  { rank: 37, playerName: "Denzel Boston", school: "Washington", position: "WR" },
  { rank: 38, playerName: "Jake Golday", school: "Cincinnati", position: "LB" },
  { rank: 39, playerName: "Josiah Trotter", school: "Missouri", position: "LB" },
  { rank: 40, playerName: "Colton Hood", school: "Tennessee", position: "CB" },
  { rank: 41, playerName: "C.J. Allen", school: "Georgia", position: "LB" },
  { rank: 42, playerName: "Christen Miller", school: "Georgia", position: "DT" },
  { rank: 43, playerName: "Monroe Freeling", school: "Georgia", position: "OT" },
  { rank: 44, playerName: "Keith Abney II", school: "Arizona State", position: "CB" },
  { rank: 45, playerName: "Emmanuel Pregnon", school: "Oregon", position: "IOL" },
  { rank: 46, playerName: "Connor Lew", school: "Auburn", position: "IOL" },
  { rank: 47, playerName: "Germie Bernard", school: "Alabama", position: "WR" },
  { rank: 48, playerName: "Trey Zuhn III", school: "Texas A&M", position: "IOL" },
  { rank: 49, playerName: "Keionte Scott", school: "Miami (FL)", position: "S" },
  { rank: 50, playerName: "Cashius Howell", school: "Texas A&M", position: "EDGE" },
];

/** NFL.com 2026 top-50 — Daniel Jeremiah, post-combine update (March 2026). */
export const NFL_PLAYERS_2026_TOP50: RankedPlayer[] = [
  { rank: 1, playerName: "Fernando Mendoza", school: "Indiana", position: "QB" },
  { rank: 2, playerName: "Sonny Styles", school: "Ohio State", position: "LB" },
  { rank: 3, playerName: "Arvell Reese", school: "Ohio State", position: "EDGE" },
  { rank: 4, playerName: "David Bailey", school: "Texas Tech", position: "EDGE" },
  { rank: 5, playerName: "Jeremiyah Love", school: "Notre Dame", position: "RB" },
  { rank: 6, playerName: "Rueben Bain Jr.", school: "Miami (FL)", position: "EDGE" },
  { rank: 7, playerName: "Kenyon Sadiq", school: "Oregon", position: "TE" },
  { rank: 8, playerName: "Makai Lemon", school: "USC", position: "WR" },
  { rank: 9, playerName: "Mansoor Delane", school: "LSU", position: "CB" },
  { rank: 10, playerName: "Carnell Tate", school: "Ohio State", position: "WR" },
  { rank: 11, playerName: "Caleb Downs", school: "Ohio State", position: "S" },
  { rank: 12, playerName: "Spencer Fano", school: "Utah", position: "OT" },
  { rank: 13, playerName: "Francis Mauigoa", school: "Miami (FL)", position: "OT" },
  { rank: 14, playerName: "Jermod McCoy", school: "Tennessee", position: "CB" },
  { rank: 15, playerName: "Jordyn Tyson", school: "Arizona State", position: "WR" },
  { rank: 16, playerName: "Dillon Thieneman", school: "Oregon", position: "S" },
  { rank: 17, playerName: "Caleb Banks", school: "Florida", position: "DT" },
  { rank: 18, playerName: "Caleb Lomu", school: "Utah", position: "OT" },
  { rank: 19, playerName: "Colton Hood", school: "Tennessee", position: "CB" },
  { rank: 20, playerName: "Denzel Boston", school: "Washington", position: "WR" },
  { rank: 21, playerName: "C.J. Allen", school: "Georgia", position: "LB" },
  { rank: 22, playerName: "Blake Miller", school: "Clemson", position: "OT" },
  { rank: 23, playerName: "Monroe Freeling", school: "Georgia", position: "OT" },
  { rank: 24, playerName: "Keldric Faulk", school: "Auburn", position: "EDGE" },
  { rank: 25, playerName: "Lee Hunter", school: "Texas Tech", position: "DT" },
  { rank: 26, playerName: "Kadyn Proctor", school: "Alabama", position: "OT" },
  { rank: 27, playerName: "Avieon Terrell", school: "Clemson", position: "CB" },
  { rank: 28, playerName: "Brandon Cisse", school: "South Carolina", position: "CB" },
  { rank: 29, playerName: "Ty Simpson", school: "Alabama", position: "QB" },
  { rank: 30, playerName: "KC Concepcion", school: "Texas A&M", position: "WR" },
  { rank: 31, playerName: "Kayden McDonald", school: "Ohio State", position: "DT" },
  { rank: 32, playerName: "Peter Woods", school: "Clemson", position: "DT" },
  { rank: 33, playerName: "R Mason Thomas", school: "Oklahoma", position: "EDGE" },
  { rank: 34, playerName: "Antonio Williams", school: "Clemson", position: "WR" },
  { rank: 35, playerName: "Christen Miller", school: "Georgia", position: "DT" },
  { rank: 36, playerName: "T.J. Parker", school: "Clemson", position: "EDGE" },
  { rank: 37, playerName: "Max Iheanachor", school: "Arizona State", position: "OT" },
  { rank: 38, playerName: "Anthony Hill Jr.", school: "Texas", position: "LB" },
  { rank: 39, playerName: "Chris Brazzell II", school: "Tennessee", position: "WR" },
  { rank: 40, playerName: "Malachi Fields", school: "Notre Dame", position: "WR" },
  { rank: 41, playerName: "Deion Burks", school: "Oklahoma", position: "WR" },
  { rank: 42, playerName: "Jake Golday", school: "Cincinnati", position: "LB" },
  { rank: 43, playerName: "Zachariah Branch", school: "Georgia", position: "WR" },
  { rank: 44, playerName: "Chase Bisontis", school: "Texas A&M", position: "IOL" },
  { rank: 45, playerName: "Olaivavega Ioane", school: "Penn State", position: "IOL" },
  { rank: 46, playerName: "Akheem Mesidor", school: "Miami (FL)", position: "DT" },
  { rank: 47, playerName: "Jadarian Price", school: "Notre Dame", position: "RB" },
  { rank: 48, playerName: "Chris Bell", school: "Louisville", position: "WR" },
  { rank: 49, playerName: "Zavion Thomas", school: "LSU", position: "WR" },
  { rank: 50, playerName: "Cashius Howell", school: "Texas A&M", position: "EDGE" },
];

/** PFF 2026 big board top-50 — post-combine update (March 2026). Heavy defensive bias; values pass-rush, coverage grade, and athletic testing. */
export const PFF_PLAYERS_2026_TOP50: RankedPlayer[] = [
  { rank: 1, playerName: "Rueben Bain Jr.", school: "Miami (FL)", position: "EDGE" },
  { rank: 2, playerName: "Sonny Styles", school: "Ohio State", position: "LB" },
  { rank: 3, playerName: "Arvell Reese", school: "Ohio State", position: "EDGE" },
  { rank: 4, playerName: "David Bailey", school: "Texas Tech", position: "EDGE" },
  { rank: 5, playerName: "Caleb Downs", school: "Ohio State", position: "S" },
  { rank: 6, playerName: "Peter Woods", school: "Clemson", position: "DT" },
  { rank: 7, playerName: "Jordyn Tyson", school: "Arizona State", position: "WR" },
  { rank: 8, playerName: "Kenyon Sadiq", school: "Oregon", position: "TE" },
  { rank: 9, playerName: "Jeremiyah Love", school: "Notre Dame", position: "RB" },
  { rank: 10, playerName: "T.J. Parker", school: "Clemson", position: "EDGE" },
  { rank: 11, playerName: "Jermod McCoy", school: "Tennessee", position: "CB" },
  { rank: 12, playerName: "Keldric Faulk", school: "Auburn", position: "EDGE" },
  { rank: 13, playerName: "Carnell Tate", school: "Ohio State", position: "WR" },
  { rank: 14, playerName: "Caleb Banks", school: "Florida", position: "DT" },
  { rank: 15, playerName: "Mansoor Delane", school: "LSU", position: "CB" },
  { rank: 16, playerName: "Spencer Fano", school: "Utah", position: "OT" },
  { rank: 17, playerName: "Dillon Thieneman", school: "Oregon", position: "S" },
  { rank: 18, playerName: "Brandon Cisse", school: "South Carolina", position: "CB" },
  { rank: 19, playerName: "Christen Miller", school: "Georgia", position: "DT" },
  { rank: 20, playerName: "Ty Simpson", school: "Alabama", position: "QB" },
  { rank: 21, playerName: "Francis Mauigoa", school: "Miami (FL)", position: "OT" },
  { rank: 22, playerName: "Fernando Mendoza", school: "Indiana", position: "QB" },
  { rank: 23, playerName: "Denzel Boston", school: "Washington", position: "WR" },
  { rank: 24, playerName: "Gennings Dunker", school: "Iowa", position: "OT" },
  { rank: 25, playerName: "Romello Height", school: "Texas Tech", position: "EDGE" },
  { rank: 26, playerName: "Dante Moore", school: "Oregon", position: "QB" },
  { rank: 27, playerName: "Olaivavega Ioane", school: "Penn State", position: "IOL" },
  { rank: 28, playerName: "A.J. Harris", school: "Penn State", position: "CB" },
  { rank: 29, playerName: "R Mason Thomas", school: "Oklahoma", position: "EDGE" },
  { rank: 30, playerName: "Avieon Terrell", school: "Clemson", position: "CB" },
  { rank: 31, playerName: "Kadyn Proctor", school: "Alabama", position: "OT" },
  { rank: 32, playerName: "Connor Lew", school: "Auburn", position: "IOL" },
  { rank: 33, playerName: "Colton Hood", school: "Tennessee", position: "CB" },
  { rank: 34, playerName: "KC Concepcion", school: "Texas A&M", position: "WR" },
  { rank: 35, playerName: "A.J. Haulcy", school: "LSU", position: "S" },
  { rank: 36, playerName: "Joshua Josephs", school: "Tennessee", position: "EDGE" },
  { rank: 37, playerName: "Quincy Rhodes", school: "Arkansas", position: "EDGE" },
  { rank: 38, playerName: "A'Mauri Washington", school: "Oregon", position: "DT" },
  { rank: 39, playerName: "Charles Jagusah", school: "Notre Dame", position: "IOL" },
  { rank: 40, playerName: "Chris Brazzell II", school: "Tennessee", position: "WR" },
  { rank: 41, playerName: "Ian Strong", school: "Rutgers", position: "WR" },
  { rank: 42, playerName: "Caleb Lomu", school: "Utah", position: "OT" },
  { rank: 43, playerName: "Elijah Sarratt", school: "Indiana", position: "WR" },
  { rank: 44, playerName: "Chris Johnson", school: "San Diego State", position: "CB" },
  { rank: 45, playerName: "Austin Siereveld", school: "Ohio State", position: "OT" },
  { rank: 46, playerName: "Kayden McDonald", school: "Ohio State", position: "DT" },
  { rank: 47, playerName: "Matayo Uiagalelei", school: "Oregon", position: "EDGE" },
  { rank: 48, playerName: "Rod Moore", school: "Michigan", position: "S" },
  { rank: 49, playerName: "Max Klare", school: "Ohio State", position: "TE" },
  { rank: 50, playerName: "Cashius Howell", school: "Texas A&M", position: "EDGE" },
];

/** Fox Sports 2026 top-50 — post-combine update (March 2026). Values offensive weapons and upside. */
export const FOX_PLAYERS_2026_TOP50: RankedPlayer[] = [
  { rank: 1, playerName: "Fernando Mendoza", school: "Indiana", position: "QB" },
  { rank: 2, playerName: "Sonny Styles", school: "Ohio State", position: "LB" },
  { rank: 3, playerName: "Rueben Bain Jr.", school: "Miami (FL)", position: "EDGE" },
  { rank: 4, playerName: "Arvell Reese", school: "Ohio State", position: "EDGE" },
  { rank: 5, playerName: "David Bailey", school: "Texas Tech", position: "EDGE" },
  { rank: 6, playerName: "Carnell Tate", school: "Ohio State", position: "WR" },
  { rank: 7, playerName: "Jordyn Tyson", school: "Arizona State", position: "WR" },
  { rank: 8, playerName: "Spencer Fano", school: "Utah", position: "OT" },
  { rank: 9, playerName: "Jeremiyah Love", school: "Notre Dame", position: "RB" },
  { rank: 10, playerName: "Caleb Downs", school: "Ohio State", position: "S" },
  { rank: 11, playerName: "Jermod McCoy", school: "Tennessee", position: "CB" },
  { rank: 12, playerName: "Kenyon Sadiq", school: "Oregon", position: "TE" },
  { rank: 13, playerName: "Peter Woods", school: "Clemson", position: "DT" },
  { rank: 14, playerName: "Avieon Terrell", school: "Clemson", position: "CB" },
  { rank: 15, playerName: "Makai Lemon", school: "USC", position: "WR" },
  { rank: 16, playerName: "Caleb Lomu", school: "Utah", position: "OT" },
  { rank: 17, playerName: "Olaivavega Ioane", school: "Penn State", position: "IOL" },
  { rank: 18, playerName: "Francis Mauigoa", school: "Miami (FL)", position: "OT" },
  { rank: 19, playerName: "Mansoor Delane", school: "LSU", position: "CB" },
  { rank: 20, playerName: "Omar Cooper Jr.", school: "Indiana", position: "WR" },
  { rank: 21, playerName: "Dillon Thieneman", school: "Oregon", position: "S" },
  { rank: 22, playerName: "Caleb Banks", school: "Florida", position: "DT" },
  { rank: 23, playerName: "Lee Hunter", school: "Texas Tech", position: "DT" },
  { rank: 24, playerName: "Kayden McDonald", school: "Ohio State", position: "DT" },
  { rank: 25, playerName: "Akheem Mesidor", school: "Miami (FL)", position: "DT" },
  { rank: 26, playerName: "Blake Miller", school: "Clemson", position: "OT" },
  { rank: 27, playerName: "Keldric Faulk", school: "Auburn", position: "EDGE" },
  { rank: 28, playerName: "Max Iheanachor", school: "Arizona State", position: "OT" },
  { rank: 29, playerName: "Denzel Boston", school: "Washington", position: "WR" },
  { rank: 30, playerName: "Anthony Hill Jr.", school: "Texas", position: "LB" },
  { rank: 31, playerName: "T.J. Parker", school: "Clemson", position: "EDGE" },
  { rank: 32, playerName: "KC Concepcion", school: "Texas A&M", position: "WR" },
  { rank: 33, playerName: "Ty Simpson", school: "Alabama", position: "QB" },
  { rank: 34, playerName: "Jake Golday", school: "Cincinnati", position: "LB" },
  { rank: 35, playerName: "Monroe Freeling", school: "Georgia", position: "OT" },
  { rank: 36, playerName: "Josiah Trotter", school: "Missouri", position: "LB" },
  { rank: 37, playerName: "Zachariah Branch", school: "Georgia", position: "WR" },
  { rank: 38, playerName: "Colton Hood", school: "Tennessee", position: "CB" },
  { rank: 39, playerName: "Chase Bisontis", school: "Texas A&M", position: "IOL" },
  { rank: 40, playerName: "C.J. Allen", school: "Georgia", position: "LB" },
  { rank: 41, playerName: "Christen Miller", school: "Georgia", position: "DT" },
  { rank: 42, playerName: "Keith Abney II", school: "Arizona State", position: "CB" },
  { rank: 43, playerName: "R Mason Thomas", school: "Oklahoma", position: "DT" },
  { rank: 44, playerName: "Emmanuel Pregnon", school: "Oregon", position: "IOL" },
  { rank: 45, playerName: "Connor Lew", school: "Auburn", position: "IOL" },
  { rank: 46, playerName: "Germie Bernard", school: "Alabama", position: "WR" },
  { rank: 47, playerName: "Trey Zuhn III", school: "Texas A&M", position: "IOL" },
  { rank: 48, playerName: "Chris Brazzell II", school: "Tennessee", position: "WR" },
  { rank: 49, playerName: "Cashius Howell", school: "Texas A&M", position: "EDGE" },
  { rank: 50, playerName: "Keionte Scott", school: "Miami (FL)", position: "S" },
];
