/**
 * Historical NFL Draft Big Boards (and first-round mock drafts) sourced
 * via parallel research agents on 2026-05-01. Used by
 * scripts/ingest-expert-rankings-batch.ts to bulk-load expert_rankings.
 *
 * Confidence levels:
 *   - high: full board verified against primary publisher article or
 *     two independent reposts.
 *   - medium: assembled from search snippets (no full-article fetch
 *     possible, e.g. NFL.com SPA pages); each rank has at least one
 *     corroborating snippet but the list wasn't end-to-end verified.
 *   - low: top-N only; lower ranks paywalled / unavailable.
 *
 * Position strings are kept close to the source. The Oracle leaderboard
 * doesn't use position; the Scout leaderboard tolerates free-form pos.
 */

export interface BoardEntry {
  rank: number;
  player: string;
  pos?: string;
  school?: string;
}

export interface Board {
  expertSlug: string;
  year: number;
  source: string;
  confidence: 'high' | 'medium' | 'low';
  rankings: BoardEntry[];
  note?: string;
}

// ─────────────────────────────────────────────────────────────────
// Daniel Jeremiah (NFL Network)
// ─────────────────────────────────────────────────────────────────

const DJ_2019: Board = {
  expertSlug: 'dj',
  year: 2019,
  source: 'https://www.nfl.com/news/daniel-jeremiah-s-top-50-prospects-for-2019-nfl-draft-4-0-0ap3000001025221',
  confidence: 'medium',
  note: 'Final pre-draft top 50 (4.0). Assembled from search snippets — not end-to-end verified against the JS-rendered NFL.com article.',
  rankings: [
    {rank: 1, player: 'Nick Bosa', pos: 'DE', school: 'Ohio State'},
    {rank: 2, player: 'Quinnen Williams', pos: 'DT', school: 'Alabama'},
    {rank: 3, player: 'Josh Allen', pos: 'EDGE', school: 'Kentucky'},
    {rank: 4, player: 'Ed Oliver', pos: 'DT', school: 'Houston'},
    {rank: 5, player: 'T.J. Hockenson', pos: 'TE', school: 'Iowa'},
    {rank: 6, player: 'Devin White', pos: 'LB', school: 'LSU'},
    {rank: 7, player: 'Christian Wilkins', pos: 'DT', school: 'Clemson'},
    {rank: 8, player: 'Josh Jacobs', pos: 'RB', school: 'Alabama'},
    {rank: 9, player: 'Devin Bush', pos: 'LB', school: 'Michigan'},
    {rank: 10, player: 'Rashan Gary', pos: 'EDGE', school: 'Michigan'},
    {rank: 11, player: 'Kyler Murray', pos: 'QB', school: 'Oklahoma'},
    {rank: 12, player: 'Montez Sweat', pos: 'EDGE', school: 'Mississippi State'},
    {rank: 13, player: 'Andre Dillard', pos: 'OT', school: 'Washington State'},
    {rank: 14, player: 'Jawaan Taylor', pos: 'OT', school: 'Florida'},
    {rank: 15, player: 'Noah Fant', pos: 'TE', school: 'Iowa'},
    {rank: 16, player: 'Marquise Brown', pos: 'WR', school: 'Oklahoma'},
    {rank: 17, player: 'Jeffery Simmons', pos: 'DT', school: 'Mississippi State'},
    {rank: 18, player: 'Garrett Bradbury', pos: 'C', school: 'NC State'},
    {rank: 19, player: 'D.K. Metcalf', pos: 'WR', school: 'Mississippi'},
    {rank: 20, player: 'Jonah Williams', pos: 'OG', school: 'Alabama'},
    {rank: 21, player: 'Dwayne Haskins', pos: 'QB', school: 'Ohio State'},
    {rank: 22, player: 'Clelin Ferrell', pos: 'EDGE', school: 'Clemson'},
    {rank: 23, player: 'Johnathan Abram', pos: 'S', school: 'Mississippi State'},
    {rank: 24, player: 'Drew Lock', pos: 'QB', school: 'Missouri'},
    {rank: 25, player: 'Dexter Lawrence', pos: 'DT', school: 'Clemson'},
    {rank: 26, player: 'Byron Murphy', pos: 'CB', school: 'Washington'},
    {rank: 27, player: 'Brian Burns', pos: 'EDGE', school: 'Florida State'},
    {rank: 28, player: 'Irv Smith Jr.', pos: 'TE', school: 'Alabama'},
    {rank: 29, player: 'Rock Ya-Sin', pos: 'CB', school: 'Temple'},
    {rank: 30, player: 'Cody Ford', pos: 'OT', school: 'Oklahoma'},
    {rank: 31, player: 'DeAndre Baker', pos: 'CB', school: 'Georgia'},
    {rank: 32, player: 'Greedy Williams', pos: 'CB', school: 'LSU'},
    {rank: 33, player: 'Nasir Adderley', pos: 'S', school: 'Delaware'},
    {rank: 34, player: 'Daniel Jones', pos: 'QB', school: 'Duke'},
    {rank: 35, player: 'Jerry Tillery', pos: 'DT', school: 'Notre Dame'},
    {rank: 36, player: 'A.J. Brown', pos: 'WR', school: 'Mississippi'},
    {rank: 37, player: "N'Keal Harry", pos: 'WR', school: 'Arizona State'},
    {rank: 38, player: 'Riley Ridley', pos: 'WR', school: 'Georgia'},
    {rank: 39, player: 'Erik McCoy', pos: 'C', school: 'Texas A&M'},
    {rank: 40, player: 'Dalton Risner', pos: 'OT', school: 'Kansas State'},
    {rank: 41, player: 'Deebo Samuel', pos: 'WR', school: 'South Carolina'},
    {rank: 42, player: 'Taylor Rapp', pos: 'S', school: 'Washington'},
    {rank: 43, player: 'David Montgomery', pos: 'RB', school: 'Iowa State'},
    {rank: 44, player: 'Kaleb McGary', pos: 'OT', school: 'Washington'},
    {rank: 45, player: 'L.J. Collier', pos: 'EDGE', school: 'TCU'},
    {rank: 46, player: 'Miles Sanders', pos: 'RB', school: 'Penn State'},
    {rank: 47, player: 'Jaylon Ferguson', pos: 'EDGE', school: 'Louisiana Tech'},
    {rank: 48, player: 'Julian Love', pos: 'CB', school: 'Notre Dame'},
    {rank: 49, player: 'Trayvon Mullen', pos: 'CB', school: 'Clemson'},
    {rank: 50, player: 'Tytus Howard', pos: 'OT', school: 'Alabama State'},
  ],
};

const DJ_2020: Board = {
  expertSlug: 'dj',
  year: 2020,
  source: 'https://www.nfl.com/news/daniel-jeremiah-s-top-150-prospects-in-the-2020-nfl-draft-class-0ap3000001110012',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Chase Young', pos: 'EDGE', school: 'Ohio State'},
    {rank: 2, player: 'Joe Burrow', pos: 'QB', school: 'LSU'},
    {rank: 3, player: 'Isaiah Simmons', pos: 'LB', school: 'Clemson'},
    {rank: 4, player: 'Jeff Okudah', pos: 'CB', school: 'Ohio State'},
    {rank: 5, player: 'Derrick Brown', pos: 'DT', school: 'Auburn'},
    {rank: 6, player: 'Tua Tagovailoa', pos: 'QB', school: 'Alabama'},
    {rank: 7, player: 'Mekhi Becton', pos: 'OT', school: 'Louisville'},
    {rank: 8, player: 'Javon Kinlaw', pos: 'DT', school: 'South Carolina'},
    {rank: 9, player: 'CeeDee Lamb', pos: 'WR', school: 'Oklahoma'},
    {rank: 10, player: 'Jedrick Wills', pos: 'OT', school: 'Alabama'},
    {rank: 11, player: 'Jerry Jeudy', pos: 'WR', school: 'Alabama'},
    {rank: 12, player: 'Henry Ruggs III', pos: 'WR', school: 'Alabama'},
    {rank: 13, player: 'Tristan Wirfs', pos: 'OT', school: 'Iowa'},
    {rank: 14, player: 'Justin Jefferson', pos: 'WR', school: 'LSU'},
    {rank: 15, player: 'Patrick Queen', pos: 'LB', school: 'LSU'},
    {rank: 16, player: "D'Andre Swift", pos: 'RB', school: 'Georgia'},
    {rank: 17, player: 'Kenneth Murray', pos: 'LB', school: 'Oklahoma'},
    {rank: 18, player: 'Andrew Thomas', pos: 'OT', school: 'Georgia'},
    {rank: 19, player: 'Ross Blacklock', pos: 'DT', school: 'TCU'},
    {rank: 20, player: 'Justin Herbert', pos: 'QB', school: 'Oregon'},
    {rank: 21, player: 'C.J. Henderson', pos: 'CB', school: 'Florida'},
    {rank: 22, player: 'Xavier McKinney', pos: 'S', school: 'Alabama'},
    {rank: 23, player: 'Jordan Love', pos: 'QB', school: 'Utah State'},
    {rank: 24, player: 'Brandon Aiyuk', pos: 'WR', school: 'Arizona State'},
    {rank: 25, player: "K'Lavon Chaisson", pos: 'EDGE', school: 'LSU'},
    {rank: 26, player: 'A.J. Epenesa', pos: 'EDGE', school: 'Iowa'},
    {rank: 27, player: 'Tee Higgins', pos: 'WR', school: 'Clemson'},
    {rank: 28, player: 'Austin Jackson', pos: 'OT', school: 'USC'},
    {rank: 29, player: 'Jaylon Johnson', pos: 'CB', school: 'Utah'},
    {rank: 30, player: 'Yetur Gross-Matos', pos: 'EDGE', school: 'Penn State'},
    {rank: 31, player: 'A.J. Terrell', pos: 'CB', school: 'Clemson'},
    {rank: 32, player: 'Clyde Edwards-Helaire', pos: 'RB', school: 'LSU'},
    {rank: 33, player: 'Marlon Davidson', pos: 'EDGE', school: 'Auburn'},
    {rank: 34, player: 'Zack Baun', pos: 'LB', school: 'Wisconsin'},
    {rank: 35, player: 'Jonathan Taylor', pos: 'RB', school: 'Wisconsin'},
    {rank: 36, player: 'Laviska Shenault', pos: 'WR', school: 'Colorado'},
    {rank: 37, player: 'J.K. Dobbins', pos: 'RB', school: 'Ohio State'},
    {rank: 38, player: 'Cesar Ruiz', pos: 'C', school: 'Michigan'},
    {rank: 39, player: 'Joshua Jones', pos: 'OT', school: 'Houston'},
    {rank: 40, player: 'Grant Delpit', pos: 'S', school: 'LSU'},
    {rank: 41, player: 'Cole Kmet', pos: 'TE', school: 'Notre Dame'},
    {rank: 42, player: 'Jeff Gladney', pos: 'CB', school: 'TCU'},
    {rank: 43, player: 'Kristian Fulton', pos: 'CB', school: 'LSU'},
    {rank: 44, player: 'Jeremy Chinn', pos: 'LB', school: 'Southern Illinois'},
    {rank: 45, player: 'Justin Madubuike', pos: 'DT', school: 'Texas A&M'},
    {rank: 46, player: 'Denzel Mims', pos: 'WR', school: 'Baylor'},
    {rank: 47, player: 'Antoine Winfield Jr.', pos: 'S', school: 'Minnesota'},
    {rank: 48, player: 'Michael Pittman Jr.', pos: 'WR', school: 'USC'},
    {rank: 49, player: 'Trevon Diggs', pos: 'CB', school: 'Alabama'},
    {rank: 50, player: 'Jalen Hurts', pos: 'QB', school: 'Oklahoma'},
  ],
};

const DJ_2021: Board = {
  expertSlug: 'dj',
  year: 2021,
  source: 'https://www.nfl.com/news/daniel-jeremiah-s-top-150-prospects-in-the-2021-nfl-draft-class',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Trevor Lawrence', pos: 'QB', school: 'Clemson'},
    {rank: 2, player: 'Kyle Pitts', pos: 'TE', school: 'Florida'},
    {rank: 3, player: "Ja'Marr Chase", pos: 'WR', school: 'LSU'},
    {rank: 4, player: 'Zach Wilson', pos: 'QB', school: 'BYU'},
    {rank: 5, player: 'Jaylen Waddle', pos: 'WR', school: 'Alabama'},
    {rank: 6, player: 'DeVonta Smith', pos: 'WR', school: 'Alabama'},
    {rank: 7, player: 'Trey Lance', pos: 'QB', school: 'North Dakota State'},
    {rank: 8, player: 'Justin Fields', pos: 'QB', school: 'Ohio State'},
    {rank: 9, player: 'Patrick Surtain II', pos: 'CB', school: 'Alabama'},
    {rank: 10, player: 'Rashawn Slater', pos: 'OT', school: 'Northwestern'},
    {rank: 11, player: 'Penei Sewell', pos: 'OT', school: 'Oregon'},
    {rank: 12, player: 'Micah Parsons', pos: 'LB', school: 'Penn State'},
    {rank: 13, player: 'Alijah Vera-Tucker', pos: 'OG', school: 'USC'},
    {rank: 14, player: 'Jaycee Horn', pos: 'CB', school: 'South Carolina'},
    {rank: 15, player: 'Jeremiah Owusu-Koramoah', pos: 'LB', school: 'Notre Dame'},
    {rank: 16, player: 'Trevon Moehrig', pos: 'S', school: 'TCU'},
    {rank: 17, player: 'Kwity Paye', pos: 'EDGE', school: 'Michigan'},
    {rank: 18, player: 'Gregory Rousseau', pos: 'EDGE', school: 'Miami'},
    {rank: 19, player: 'Travis Etienne', pos: 'RB', school: 'Clemson'},
    {rank: 20, player: 'Najee Harris', pos: 'RB', school: 'Alabama'},
    {rank: 21, player: 'Jaelan Phillips', pos: 'EDGE', school: 'Miami'},
    {rank: 22, player: 'Caleb Farley', pos: 'CB', school: 'Virginia Tech'},
    {rank: 23, player: 'Jamin Davis', pos: 'LB', school: 'Kentucky'},
    {rank: 24, player: 'Zaven Collins', pos: 'LB', school: 'Tulsa'},
    {rank: 25, player: 'Javonte Williams', pos: 'RB', school: 'North Carolina'},
    {rank: 26, player: 'Elijah Moore', pos: 'WR', school: 'Mississippi'},
    {rank: 27, player: 'Greg Newsome II', pos: 'CB', school: 'Northwestern'},
    {rank: 28, player: 'Kadarius Toney', pos: 'WR', school: 'Florida'},
    {rank: 29, player: 'Levi Onwuzurike', pos: 'DT', school: 'Washington'},
    {rank: 30, player: 'Azeez Ojulari', pos: 'EDGE', school: 'Georgia'},
    {rank: 31, player: 'Jayson Oweh', pos: 'EDGE', school: 'Penn State'},
    {rank: 32, player: 'Mac Jones', pos: 'QB', school: 'Alabama'},
    {rank: 33, player: 'Joe Tryon', pos: 'EDGE', school: 'Washington'},
    {rank: 34, player: 'Nick Bolton', pos: 'LB', school: 'Missouri'},
    {rank: 35, player: 'Jalen Mayfield', pos: 'OG', school: 'Michigan'},
    {rank: 36, player: 'Teven Jenkins', pos: 'OT', school: 'Oklahoma State'},
    {rank: 37, player: 'Dillon Radunz', pos: 'OT', school: 'North Dakota State'},
    {rank: 38, player: 'Christian Darrisaw', pos: 'OT', school: 'Virginia Tech'},
    {rank: 39, player: 'Asante Samuel Jr.', pos: 'CB', school: 'Florida State'},
    {rank: 40, player: 'Landon Dickerson', pos: 'OG', school: 'Alabama'},
    {rank: 41, player: 'Rashod Bateman', pos: 'WR', school: 'Minnesota'},
    {rank: 42, player: 'Payton Turner', pos: 'EDGE', school: 'Houston'},
    {rank: 43, player: 'Christian Barmore', pos: 'DT', school: 'Alabama'},
    {rank: 44, player: 'Ronnie Perkins', pos: 'EDGE', school: 'Oklahoma'},
    {rank: 45, player: 'Quinn Meinerz', pos: 'C', school: 'Wisconsin-Whitewater'},
    {rank: 46, player: 'Pat Freiermuth', pos: 'TE', school: 'Penn State'},
    {rank: 47, player: 'Liam Eichenberg', pos: 'OT', school: 'Notre Dame'},
    {rank: 48, player: 'Terrace Marshall Jr.', pos: 'WR', school: 'LSU'},
    {rank: 49, player: 'Jevon Holland', pos: 'S', school: 'Oregon'},
    {rank: 50, player: 'Eric Stokes', pos: 'CB', school: 'Georgia'},
  ],
};

const DJ_2022: Board = {
  expertSlug: 'dj',
  year: 2022,
  source: 'https://www.nfl.com/news/daniel-jeremiah-s-top-150-prospects-in-the-2022-nfl-draft-class',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Aidan Hutchinson', pos: 'EDGE', school: 'Michigan'},
    {rank: 2, player: 'Sauce Gardner', pos: 'CB', school: 'Cincinnati'},
    {rank: 3, player: 'Ickey Ekwonu', pos: 'OT', school: 'NC State'},
    {rank: 4, player: 'Garrett Wilson', pos: 'WR', school: 'Ohio State'},
    {rank: 5, player: 'Kyle Hamilton', pos: 'S', school: 'Notre Dame'},
    {rank: 6, player: 'Travon Walker', pos: 'EDGE', school: 'Georgia'},
    {rank: 7, player: 'Drake London', pos: 'WR', school: 'USC'},
    {rank: 8, player: 'Evan Neal', pos: 'OT', school: 'Alabama'},
    {rank: 9, player: 'Jermaine Johnson II', pos: 'EDGE', school: 'Florida State'},
    {rank: 10, player: 'Kayvon Thibodeaux', pos: 'EDGE', school: 'Oregon'},
    {rank: 11, player: 'Jordan Davis', pos: 'DT', school: 'Georgia'},
    {rank: 12, player: 'Derek Stingley Jr.', pos: 'CB', school: 'LSU'},
    {rank: 13, player: 'Devin Lloyd', pos: 'LB', school: 'Utah'},
    {rank: 14, player: 'Trent McDuffie', pos: 'CB', school: 'Washington'},
    {rank: 15, player: 'Chris Olave', pos: 'WR', school: 'Ohio State'},
    {rank: 16, player: 'Jameson Williams', pos: 'WR', school: 'Alabama'},
    {rank: 17, player: 'Nakobe Dean', pos: 'LB', school: 'Georgia'},
    {rank: 18, player: 'George Karlaftis', pos: 'EDGE', school: 'Purdue'},
    {rank: 19, player: 'Treylon Burks', pos: 'WR', school: 'Arkansas'},
    {rank: 20, player: 'Trevor Penning', pos: 'OT', school: 'Northern Iowa'},
    {rank: 21, player: 'Dax Hill', pos: 'S', school: 'Michigan'},
    {rank: 22, player: 'Charles Cross', pos: 'OT', school: 'Mississippi State'},
    {rank: 23, player: 'Devonte Wyatt', pos: 'DT', school: 'Georgia'},
    {rank: 24, player: 'Kenny Pickett', pos: 'QB', school: 'Pittsburgh'},
    {rank: 25, player: 'Jahan Dotson', pos: 'WR', school: 'Penn State'},
    {rank: 26, player: 'Malik Willis', pos: 'QB', school: 'Liberty'},
    {rank: 27, player: 'Tyler Linderbaum', pos: 'C', school: 'Iowa'},
    {rank: 28, player: 'Breece Hall', pos: 'RB', school: 'Iowa State'},
    {rank: 29, player: 'Quay Walker', pos: 'LB', school: 'Georgia'},
    {rank: 30, player: 'Zion Johnson', pos: 'OG', school: 'Boston College'},
    {rank: 31, player: 'Boye Mafe', pos: 'EDGE', school: 'Minnesota'},
    {rank: 32, player: 'Andrew Booth', pos: 'CB', school: 'Clemson'},
    {rank: 33, player: 'Kenneth Walker III', pos: 'RB', school: 'Michigan State'},
    {rank: 34, player: 'Arnold Ebiketie', pos: 'EDGE', school: 'Penn State'},
    {rank: 35, player: 'Kyler Gordon', pos: 'CB', school: 'Washington'},
    {rank: 36, player: 'Kenyon Green', pos: 'OG', school: 'Texas A&M'},
    {rank: 37, player: 'Travis Jones', pos: 'DT', school: 'Connecticut'},
    {rank: 38, player: 'Christian Harris', pos: 'LB', school: 'Alabama'},
    {rank: 39, player: 'Lewis Cine', pos: 'S', school: 'Georgia'},
    {rank: 40, player: 'Matt Corral', pos: 'QB', school: 'Mississippi'},
    {rank: 41, player: 'Jalen Pitre', pos: 'S', school: 'Baylor'},
    {rank: 42, player: 'Tyler Smith', pos: 'OT', school: 'Tulsa'},
    {rank: 43, player: 'Bernhard Raimann', pos: 'OT', school: 'Central Michigan'},
    {rank: 44, player: 'Nik Bonitto', pos: 'EDGE', school: 'Oklahoma'},
    {rank: 45, player: 'Skyy Moore', pos: 'WR', school: 'Western Michigan'},
    {rank: 46, player: 'Christian Watson', pos: 'WR', school: 'North Dakota State'},
    {rank: 47, player: 'Kaiir Elam', pos: 'CB', school: 'Florida'},
    {rank: 48, player: 'Sam Howell', pos: 'QB', school: 'North Carolina'},
    {rank: 49, player: 'David Ojabo', pos: 'EDGE', school: 'Michigan'},
    {rank: 50, player: 'Logan Hall', pos: 'DT', school: 'Houston'},
  ],
};

// ─────────────────────────────────────────────────────────────────
// Mel Kiper Jr. (ESPN)
// ─────────────────────────────────────────────────────────────────

const KIPER_2020: Board = {
  expertSlug: 'kiper',
  year: 2020,
  source:
    'https://www.espn.com/nfl/draft2020/insider/story/_/id/29072730/2020-nfl-draft-rankings-final-top-300-position-rankings-big-board-mel-kiper',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Chase Young', pos: 'DE', school: 'Ohio State'},
    {rank: 2, player: 'Joe Burrow', pos: 'QB', school: 'LSU'},
    {rank: 3, player: 'Jeff Okudah', pos: 'CB', school: 'Ohio State'},
    {rank: 4, player: 'Isaiah Simmons', pos: 'OLB', school: 'Clemson'},
    {rank: 5, player: 'Tua Tagovailoa', pos: 'QB', school: 'Alabama'},
    {rank: 6, player: 'Derrick Brown', pos: 'DT', school: 'Auburn'},
    {rank: 7, player: 'Jedrick Wills Jr.', pos: 'OT', school: 'Alabama'},
    {rank: 8, player: 'Jerry Jeudy', pos: 'WR', school: 'Alabama'},
    {rank: 9, player: 'Justin Herbert', pos: 'QB', school: 'Oregon'},
    {rank: 10, player: 'Tristan Wirfs', pos: 'OT', school: 'Iowa'},
    {rank: 11, player: 'Javon Kinlaw', pos: 'DT', school: 'South Carolina'},
    {rank: 12, player: 'CeeDee Lamb', pos: 'WR', school: 'Oklahoma'},
    {rank: 13, player: 'C.J. Henderson', pos: 'CB', school: 'Florida'},
    {rank: 14, player: 'Andrew Thomas', pos: 'OT', school: 'Georgia'},
    {rank: 15, player: 'Xavier McKinney', pos: 'S', school: 'Alabama'},
    {rank: 16, player: 'Justin Jefferson', pos: 'WR', school: 'LSU'},
    {rank: 17, player: "K'Lavon Chaisson", pos: 'OLB', school: 'LSU'},
    {rank: 18, player: 'Kenneth Murray', pos: 'ILB', school: 'Oklahoma'},
    {rank: 19, player: 'Mekhi Becton', pos: 'OT', school: 'Louisville'},
    {rank: 20, player: 'Henry Ruggs III', pos: 'WR', school: 'Alabama'},
    {rank: 21, player: 'Jordan Love', pos: 'QB', school: 'Utah State'},
    {rank: 22, player: 'Patrick Queen', pos: 'ILB', school: 'LSU'},
    {rank: 23, player: 'Brandon Aiyuk', pos: 'WR', school: 'Arizona State'},
    {rank: 24, player: 'Antoine Winfield Jr.', pos: 'S', school: 'Minnesota'},
    {rank: 25, player: "D'Andre Swift", pos: 'RB', school: 'Georgia'},
  ],
};

const KIPER_2021: Board = {
  expertSlug: 'kiper',
  year: 2021,
  source:
    'https://www.espn.com/nfl/insider/draft2021/insider/story/_/id/31341281/2021-nfl-draft-rankings-top-150-prospects-best-500-position-mel-kiper-new-big-board',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Trevor Lawrence', pos: 'QB', school: 'Clemson'},
    {rank: 2, player: 'Kyle Pitts', pos: 'TE', school: 'Florida'},
    {rank: 3, player: 'DeVonta Smith', pos: 'WR', school: 'Alabama'},
    {rank: 4, player: "Ja'Marr Chase", pos: 'WR', school: 'LSU'},
    {rank: 5, player: 'Jaylen Waddle', pos: 'WR', school: 'Alabama'},
    {rank: 6, player: 'Penei Sewell', pos: 'OT', school: 'Oregon'},
    {rank: 7, player: 'Rashawn Slater', pos: 'OT', school: 'Northwestern'},
    {rank: 8, player: 'Justin Fields', pos: 'QB', school: 'Ohio State'},
    {rank: 9, player: 'Zach Wilson', pos: 'QB', school: 'BYU'},
    {rank: 10, player: 'Alijah Vera-Tucker', pos: 'OG', school: 'USC'},
    {rank: 11, player: 'Micah Parsons', pos: 'LB', school: 'Penn State'},
    {rank: 12, player: 'Mac Jones', pos: 'QB', school: 'Alabama'},
    {rank: 13, player: 'Trey Lance', pos: 'QB', school: 'North Dakota State'},
    {rank: 14, player: 'Jaycee Horn', pos: 'CB', school: 'South Carolina'},
    {rank: 15, player: 'Patrick Surtain II', pos: 'CB', school: 'Alabama'},
    {rank: 16, player: 'Elijah Moore', pos: 'WR', school: 'Mississippi'},
    {rank: 17, player: 'Jaelan Phillips', pos: 'DE', school: 'Miami'},
    {rank: 18, player: 'Christian Darrisaw', pos: 'OT', school: 'Virginia Tech'},
    {rank: 19, player: 'Jamin Davis', pos: 'LB', school: 'Kentucky'},
    {rank: 20, player: 'Kwity Paye', pos: 'DE', school: 'Michigan'},
    {rank: 21, player: 'Greg Newsome II', pos: 'CB', school: 'Northwestern'},
    {rank: 22, player: 'Christian Barmore', pos: 'DT', school: 'Alabama'},
    {rank: 23, player: 'Jeremiah Owusu-Koramoah', pos: 'ILB', school: 'Notre Dame'},
    {rank: 24, player: 'Trevon Moehrig', pos: 'S', school: 'TCU'},
    {rank: 25, player: 'Teven Jenkins', pos: 'OT', school: 'Oklahoma State'},
  ],
};

const KIPER_2022: Board = {
  expertSlug: 'kiper',
  year: 2022,
  source:
    'https://www.espn.com/nfl/insider/draft2022/insider/story/_/id/33805696/nfl-draft-2022-rankings-mel-kiper-top-225-prospects-best-every-position-big-board',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Aidan Hutchinson', pos: 'DE', school: 'Michigan'},
    {rank: 2, player: 'Ikem Ekwonu', pos: 'OT', school: 'NC State'},
    {rank: 3, player: 'Ahmad "Sauce" Gardner', pos: 'CB', school: 'Cincinnati'},
    {rank: 4, player: 'Kyle Hamilton', pos: 'S', school: 'Notre Dame'},
    {rank: 5, player: 'Evan Neal', pos: 'OT', school: 'Alabama'},
    {rank: 6, player: 'Derek Stingley Jr.', pos: 'CB', school: 'LSU'},
    {rank: 7, player: 'Kayvon Thibodeaux', pos: 'DE', school: 'Oregon'},
    {rank: 8, player: 'Garrett Wilson', pos: 'WR', school: 'Ohio State'},
    {rank: 9, player: 'Travon Walker', pos: 'DE', school: 'Georgia'},
    {rank: 10, player: 'Drake London', pos: 'WR', school: 'USC'},
    {rank: 11, player: 'Jermaine Johnson II', pos: 'DE', school: 'Florida State'},
    {rank: 12, player: 'Charles Cross', pos: 'OT', school: 'Mississippi State'},
    {rank: 13, player: 'Jameson Williams', pos: 'WR', school: 'Alabama'},
    {rank: 14, player: 'Daxton Hill', pos: 'S', school: 'Michigan'},
    {rank: 15, player: 'Chris Olave', pos: 'WR', school: 'Ohio State'},
    {rank: 16, player: 'Trent McDuffie', pos: 'CB', school: 'Washington'},
    {rank: 17, player: 'Malik Willis', pos: 'QB', school: 'Liberty'},
    {rank: 18, player: 'Kenny Pickett', pos: 'QB', school: 'Pitt'},
    {rank: 19, player: 'Trevor Penning', pos: 'OT', school: 'Northern Iowa'},
    {rank: 20, player: 'Arnold Ebiketie', pos: 'DE/OLB', school: 'Penn State'},
    {rank: 21, player: 'Tyler Linderbaum', pos: 'C', school: 'Iowa'},
    {rank: 22, player: 'Jahan Dotson', pos: 'WR', school: 'Penn State'},
    {rank: 23, player: 'Devin Lloyd', pos: 'LB', school: 'Utah'},
    {rank: 24, player: 'Zion Johnson', pos: 'OG', school: 'Boston College'},
    {rank: 25, player: 'Nakobe Dean', pos: 'LB', school: 'Georgia'},
  ],
};

// ─────────────────────────────────────────────────────────────────
// Matt Miller (Bleacher Report → ESPN)
// ─────────────────────────────────────────────────────────────────

const MILLER_2018: Board = {
  expertSlug: 'matt-miller',
  year: 2018,
  source:
    'https://web.archive.org/web/2018/https://bleacherreport.com/articles/2770843-2018-nfl-draft-big-board-matt-millers-top-overall-players',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Saquon Barkley', pos: 'RB', school: 'Penn State'},
    {rank: 2, player: 'Bradley Chubb', pos: 'EDGE', school: 'NC State'},
    {rank: 3, player: 'Quenton Nelson', pos: 'OG', school: 'Notre Dame'},
    {rank: 4, player: 'Tremaine Edmunds', pos: 'LB', school: 'Virginia Tech'},
    {rank: 5, player: 'Sam Darnold', pos: 'QB', school: 'USC'},
    {rank: 6, player: 'Minkah Fitzpatrick', pos: 'S', school: 'Alabama'},
    {rank: 7, player: 'Josh Allen', pos: 'QB', school: 'Wyoming'},
    {rank: 8, player: 'Josh Rosen', pos: 'QB', school: 'UCLA'},
    {rank: 9, player: 'Denzel Ward', pos: 'CB', school: 'Ohio State'},
    {rank: 10, player: 'Roquan Smith', pos: 'LB', school: 'Georgia'},
    {rank: 11, player: 'Derwin James', pos: 'S', school: 'Florida State'},
    {rank: 12, player: 'Baker Mayfield', pos: 'QB', school: 'Oklahoma'},
    {rank: 13, player: 'Connor Williams', pos: 'OT', school: 'Texas'},
    {rank: 14, player: 'Marcus Davenport', pos: 'EDGE', school: 'UTSA'},
    {rank: 15, player: 'Harold Landry', pos: 'EDGE', school: 'Boston College'},
    {rank: 16, player: 'Vita Vea', pos: 'DT', school: 'Washington'},
    {rank: 17, player: 'Josh Jackson', pos: 'CB', school: 'Iowa'},
    {rank: 18, player: 'Calvin Ridley', pos: 'WR', school: 'Alabama'},
    {rank: 19, player: 'Leighton Vander Esch', pos: 'LB', school: 'Boise State'},
    {rank: 20, player: 'Rashaan Evans', pos: 'LB', school: 'Alabama'},
    {rank: 21, player: 'Billy Price', pos: 'C', school: 'Ohio State'},
    {rank: 22, player: 'Mike McGlinchey', pos: 'OT', school: 'Notre Dame'},
    {rank: 23, player: 'James Daniels', pos: 'C', school: 'Iowa'},
    {rank: 24, player: 'Jaire Alexander', pos: 'CB', school: 'Louisville'},
    {rank: 25, player: 'Isaiah Oliver', pos: 'CB', school: 'Colorado'},
    {rank: 26, player: 'Mike Hughes', pos: 'CB', school: 'Central Florida'},
    {rank: 27, player: 'Isaiah Wynn', pos: 'OG', school: 'Georgia'},
    {rank: 28, player: 'Malik Jefferson', pos: 'LB', school: 'Texas'},
    {rank: 29, player: 'Derrius Guice', pos: 'RB', school: 'LSU'},
    {rank: 30, player: 'Taven Bryan', pos: 'DT', school: 'Florida'},
    {rank: 31, player: 'Sam Hubbard', pos: 'EDGE', school: 'Ohio State'},
    {rank: 32, player: 'Kolton Miller', pos: 'OT', school: 'UCLA'},
    {rank: 33, player: 'Sony Michel', pos: 'RB', school: 'Georgia'},
    {rank: 34, player: "Da'Ron Payne", pos: 'DT', school: 'Alabama'},
    {rank: 35, player: 'Courtland Sutton', pos: 'WR', school: 'SMU'},
    {rank: 36, player: 'Christian Kirk', pos: 'WR', school: 'Texas A&M'},
    {rank: 37, player: 'Mike Gesicki', pos: 'TE', school: 'Penn State'},
    {rank: 38, player: 'Maurice Hurst', pos: 'DT', school: 'Michigan'},
    {rank: 39, player: 'Dallas Goedert', pos: 'TE', school: 'South Dakota State'},
    {rank: 40, player: 'Ronnie Harrison', pos: 'S', school: 'Alabama'},
    {rank: 41, player: 'Will Hernandez', pos: 'OG', school: 'UTEP'},
    {rank: 42, player: 'Austin Corbett', pos: 'OG', school: 'Nevada'},
    {rank: 43, player: 'Ronald Jones', pos: 'RB', school: 'USC'},
    {rank: 44, player: 'Harrison Phillips', pos: 'DT', school: 'Stanford'},
    {rank: 45, player: 'Hayden Hurst', pos: 'TE', school: 'South Carolina'},
    {rank: 46, player: 'Jamarco Jones', pos: 'OT', school: 'Ohio State'},
    {rank: 47, player: 'Justin Reid', pos: 'S', school: 'Stanford'},
    {rank: 48, player: 'Carlton Davis', pos: 'CB', school: 'Auburn'},
    {rank: 49, player: 'Tyrell Crosby', pos: 'OT', school: 'Oregon'},
    {rank: 50, player: 'Anthony Averett', pos: 'CB', school: 'Alabama'},
  ],
};

const MILLER_2019: Board = {
  expertSlug: 'matt-miller',
  year: 2019,
  source:
    'https://web.archive.org/web/2019/https://bleacherreport.com/articles/2832566-matt-millers-final-2019-nfl-draft-big-board',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Quinnen Williams', pos: 'DT', school: 'Alabama'},
    {rank: 2, player: 'Nick Bosa', pos: 'EDGE', school: 'Ohio State'},
    {rank: 3, player: 'Josh Allen', pos: 'EDGE', school: 'Kentucky'},
    {rank: 4, player: 'Devin White', pos: 'LB', school: 'LSU'},
    {rank: 5, player: 'T.J. Hockenson', pos: 'TE', school: 'Iowa'},
    {rank: 6, player: 'Ed Oliver', pos: 'DT', school: 'Houston'},
    {rank: 7, player: 'Jeffery Simmons', pos: 'DT', school: 'Mississippi State'},
    {rank: 8, player: 'Jonah Williams', pos: 'OT', school: 'Alabama'},
    {rank: 9, player: 'Josh Jacobs', pos: 'RB', school: 'Alabama'},
    {rank: 10, player: 'Rashan Gary', pos: 'EDGE', school: 'Michigan'},
    {rank: 11, player: 'Devin Bush', pos: 'LB', school: 'Michigan'},
    {rank: 12, player: 'Montez Sweat', pos: 'EDGE', school: 'Mississippi State'},
    {rank: 13, player: 'Kyler Murray', pos: 'QB', school: 'Oklahoma'},
    {rank: 14, player: 'A.J. Brown', pos: 'WR', school: 'Mississippi'},
    {rank: 15, player: 'Greedy Williams', pos: 'CB', school: 'LSU'},
    {rank: 16, player: 'Noah Fant', pos: 'TE', school: 'Iowa'},
    {rank: 17, player: 'Brian Burns', pos: 'EDGE', school: 'Florida State'},
    {rank: 18, player: 'Byron Murphy', pos: 'CB', school: 'Washington'},
    {rank: 19, player: 'Dwayne Haskins', pos: 'QB', school: 'Ohio State'},
    {rank: 20, player: "N'Keal Harry", pos: 'WR', school: 'Arizona State'},
    {rank: 21, player: 'Garrett Bradbury', pos: 'C', school: 'NC State'},
    {rank: 22, player: 'Christian Wilkins', pos: 'DT', school: 'Clemson'},
    {rank: 23, player: 'Clelin Ferrell', pos: 'EDGE', school: 'Clemson'},
    {rank: 24, player: 'Taylor Rapp', pos: 'S', school: 'Washington'},
    {rank: 25, player: 'Jawaan Taylor', pos: 'OT', school: 'Florida'},
    {rank: 26, player: 'Cody Ford', pos: 'OG', school: 'Oklahoma'},
    {rank: 27, player: 'Johnathan Abram', pos: 'S', school: 'Mississippi State'},
    {rank: 28, player: 'Marquise Brown', pos: 'WR', school: 'Oklahoma'},
    {rank: 29, player: 'Trayvon Mullen', pos: 'CB', school: 'Clemson'},
    {rank: 30, player: 'David Montgomery', pos: 'RB', school: 'Iowa State'},
    {rank: 31, player: 'Rock Ya-Sin', pos: 'CB', school: 'Temple'},
    {rank: 32, player: 'D.K. Metcalf', pos: 'WR', school: 'Mississippi'},
    {rank: 33, player: 'Drew Lock', pos: 'QB', school: 'Missouri'},
    {rank: 34, player: 'Deebo Samuel', pos: 'WR', school: 'South Carolina'},
    {rank: 35, player: 'Parris Campbell', pos: 'WR', school: 'Ohio State'},
    {rank: 36, player: 'Deandre Baker', pos: 'CB', school: 'Georgia'},
    {rank: 37, player: 'Andre Dillard', pos: 'OT', school: 'Washington State'},
    {rank: 38, player: 'Jaylon Ferguson', pos: 'EDGE', school: 'Louisiana Tech'},
    {rank: 39, player: 'Chauncey Gardner-Johnson', pos: 'S', school: 'Florida'},
    {rank: 40, player: 'Elgton Jenkins', pos: 'C', school: 'Mississippi State'},
    {rank: 41, player: 'Chris Lindstrom', pos: 'OG', school: 'Boston College'},
    {rank: 42, player: 'Deionte Thompson', pos: 'S', school: 'Alabama'},
    {rank: 43, player: 'Nasir Adderley', pos: 'S', school: 'Delaware'},
    {rank: 44, player: 'L.J. Collier', pos: 'DT', school: 'TCU'},
    {rank: 45, player: 'Justin Layne', pos: 'CB', school: 'Michigan State'},
    {rank: 46, player: 'Dexter Lawrence', pos: 'DT', school: 'Clemson'},
    {rank: 47, player: 'Hakeem Butler', pos: 'WR', school: 'Iowa State'},
    {rank: 48, player: 'Dalton Risner', pos: 'OT', school: 'Kansas State'},
    {rank: 49, player: 'Erik McCoy', pos: 'C', school: 'Texas A&M'},
    {rank: 50, player: 'Lonnie Johnson', pos: 'CB', school: 'Kentucky'},
  ],
};

const MILLER_2020: Board = {
  expertSlug: 'matt-miller',
  year: 2020,
  source:
    'https://web.archive.org/web/2020/https://bleacherreport.com/articles/2887115-matt-millers-final-2020-nfl-draft-big-board',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Chase Young', pos: 'EDGE', school: 'Ohio State'},
    {rank: 2, player: 'Joe Burrow', pos: 'QB', school: 'LSU'},
    {rank: 3, player: 'Jeff Okudah', pos: 'CB', school: 'Ohio State'},
    {rank: 4, player: 'Isaiah Simmons', pos: 'LB', school: 'Clemson'},
    {rank: 5, player: 'Jerry Jeudy', pos: 'WR', school: 'Alabama'},
    {rank: 6, player: 'Tua Tagovailoa', pos: 'QB', school: 'Alabama'},
    {rank: 7, player: 'Jedrick Wills', pos: 'OT', school: 'Alabama'},
    {rank: 8, player: 'Derrick Brown', pos: 'DT', school: 'Auburn'},
    {rank: 9, player: "K'Lavon Chaisson", pos: 'EDGE', school: 'LSU'},
    {rank: 10, player: 'Tristan Wirfs', pos: 'OT', school: 'Iowa'},
    {rank: 11, player: 'Henry Ruggs III', pos: 'WR', school: 'Alabama'},
    {rank: 12, player: 'CeeDee Lamb', pos: 'WR', school: 'Oklahoma'},
    {rank: 13, player: 'C.J. Henderson', pos: 'CB', school: 'Florida'},
    {rank: 14, player: 'Javon Kinlaw', pos: 'DT', school: 'South Carolina'},
    {rank: 15, player: "D'Andre Swift", pos: 'RB', school: 'Georgia'},
    {rank: 16, player: 'Patrick Queen', pos: 'LB', school: 'LSU'},
    {rank: 17, player: 'Andrew Thomas', pos: 'OT', school: 'Georgia'},
    {rank: 18, player: 'Mekhi Becton', pos: 'OT', school: 'Louisville'},
    {rank: 19, player: 'Kenneth Murray', pos: 'LB', school: 'Oklahoma'},
    {rank: 20, player: 'Justin Jefferson', pos: 'WR', school: 'LSU'},
    {rank: 21, player: 'Yetur Gross-Matos', pos: 'EDGE', school: 'Penn State'},
    {rank: 22, player: 'Xavier McKinney', pos: 'S', school: 'Alabama'},
    {rank: 23, player: 'A.J. Epenesa', pos: 'DT', school: 'Iowa'},
    {rank: 24, player: 'Jeff Gladney', pos: 'CB', school: 'TCU'},
    {rank: 25, player: 'Clyde Edwards-Helaire', pos: 'RB', school: 'LSU'},
    {rank: 26, player: 'Cesar Ruiz', pos: 'C', school: 'Michigan'},
    {rank: 27, player: 'Justin Herbert', pos: 'QB', school: 'Oregon'},
    {rank: 28, player: 'Tee Higgins', pos: 'WR', school: 'Clemson'},
    {rank: 29, player: 'Antoine Winfield Jr.', pos: 'S', school: 'Minnesota'},
    {rank: 30, player: 'Jonathan Taylor', pos: 'RB', school: 'Wisconsin'},
    {rank: 31, player: 'Jordan Love', pos: 'QB', school: 'Utah State'},
    {rank: 32, player: 'Zack Baun', pos: 'LB', school: 'Wisconsin'},
    {rank: 33, player: 'Jordyn Brooks', pos: 'LB', school: 'Texas Tech'},
    {rank: 34, player: 'Josh Jones', pos: 'OT', school: 'Houston'},
    {rank: 35, player: 'Jaylon Johnson', pos: 'CB', school: 'Utah'},
    {rank: 36, player: 'A.J. Terrell', pos: 'CB', school: 'Clemson'},
    {rank: 37, player: 'Marlon Davidson', pos: 'DT', school: 'Auburn'},
    {rank: 38, player: 'Austin Jackson', pos: 'OT', school: 'USC'},
    {rank: 39, player: 'Ross Blacklock', pos: 'DT', school: 'TCU'},
    {rank: 40, player: 'Brandon Aiyuk', pos: 'WR', school: 'Arizona State'},
    {rank: 41, player: 'Kyle Dugger', pos: 'S', school: 'Lenoir Rhyne'},
    {rank: 42, player: 'Jeremy Chinn', pos: 'S', school: 'Southern Illinois'},
    {rank: 43, player: 'J.K. Dobbins', pos: 'RB', school: 'Ohio State'},
    {rank: 44, player: 'Denzel Mims', pos: 'WR', school: 'Baylor'},
    {rank: 45, player: 'Michael Pittman Jr.', pos: 'WR', school: 'USC'},
    {rank: 46, player: 'KJ Hamler', pos: 'WR', school: 'Penn State'},
    {rank: 47, player: 'Trevon Diggs', pos: 'CB', school: 'Alabama'},
    {rank: 48, player: 'Kristian Fulton', pos: 'CB', school: 'LSU'},
    {rank: 49, player: 'Cole Kmet', pos: 'TE', school: 'Notre Dame'},
    {rank: 50, player: 'Jalen Reagor', pos: 'WR', school: 'TCU'},
  ],
};

const MILLER_2022: Board = {
  expertSlug: 'matt-miller',
  year: 2022,
  source:
    'https://www.espn.com/nfl/draft2022/insider/story/_/id/33731626/nfl-draft-2022-rankings-matt-miller-top-300-prospects-best-every-position',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Aidan Hutchinson', pos: 'EDGE', school: 'Michigan'},
    {rank: 2, player: 'Evan Neal', pos: 'OT', school: 'Alabama'},
    {rank: 3, player: 'Ikem Ekwonu', pos: 'OT', school: 'NC State'},
    {rank: 4, player: 'Kyle Hamilton', pos: 'S', school: 'Notre Dame'},
    {rank: 5, player: 'Travon Walker', pos: 'EDGE', school: 'Georgia'},
    {rank: 6, player: 'Ahmad Gardner', pos: 'CB', school: 'Cincinnati'},
    {rank: 7, player: 'Drake London', pos: 'WR', school: 'USC'},
    {rank: 8, player: 'Jameson Williams', pos: 'WR', school: 'Alabama'},
    {rank: 9, player: 'Kayvon Thibodeaux', pos: 'EDGE', school: 'Oregon'},
    {rank: 10, player: 'Derek Stingley Jr.', pos: 'CB', school: 'LSU'},
    {rank: 11, player: 'Charles Cross', pos: 'OT', school: 'Mississippi State'},
    {rank: 12, player: 'Garrett Wilson', pos: 'WR', school: 'Ohio State'},
    {rank: 13, player: 'Jermaine Johnson II', pos: 'EDGE', school: 'Florida State'},
    {rank: 14, player: 'Devonte Wyatt', pos: 'DT', school: 'Georgia'},
    {rank: 15, player: 'Chris Olave', pos: 'WR', school: 'Ohio State'},
    {rank: 16, player: 'Daxton Hill', pos: 'S', school: 'Michigan'},
    {rank: 17, player: 'Jordan Davis', pos: 'DT', school: 'Georgia'},
    {rank: 18, player: 'Devin Lloyd', pos: 'LB', school: 'Utah'},
    {rank: 19, player: 'Tyler Linderbaum', pos: 'C', school: 'Iowa'},
    {rank: 20, player: 'Trent McDuffie', pos: 'CB', school: 'Washington'},
    {rank: 21, player: 'Malik Willis', pos: 'QB', school: 'Liberty'},
    {rank: 22, player: 'Treylon Burks', pos: 'WR', school: 'Arkansas'},
    {rank: 23, player: 'Nakobe Dean', pos: 'LB', school: 'Georgia'},
    {rank: 24, player: 'Breece Hall', pos: 'RB', school: 'Iowa State'},
    {rank: 25, player: 'Quay Walker', pos: 'LB', school: 'Georgia'},
    {rank: 26, player: 'George Karlaftis', pos: 'EDGE', school: 'Purdue'},
    {rank: 27, player: 'Christian Watson', pos: 'WR', school: 'North Dakota State'},
    {rank: 28, player: 'Trevor Penning', pos: 'OT', school: 'Northern Iowa'},
    {rank: 29, player: 'Kenyon Green', pos: 'OG', school: 'Texas A&M'},
    {rank: 30, player: 'Boye Mafe', pos: 'EDGE', school: 'Minnesota'},
    {rank: 31, player: 'Jaquan Brisker', pos: 'S', school: 'Penn State'},
    {rank: 32, player: 'Andrew Booth Jr.', pos: 'CB', school: 'Clemson'},
    {rank: 33, player: 'Kenny Pickett', pos: 'QB', school: 'Pittsburgh'},
    {rank: 34, player: 'Kyler Gordon', pos: 'CB', school: 'Washington'},
    {rank: 35, player: 'Zion Johnson', pos: 'OG', school: 'Boston College'},
    {rank: 36, player: 'Christian Harris', pos: 'LB', school: 'Alabama'},
    {rank: 37, player: 'Travis Jones', pos: 'DT', school: 'Connecticut'},
    {rank: 38, player: 'Matt Corral', pos: 'QB', school: 'Mississippi'},
    {rank: 39, player: 'Jalen Pitre', pos: 'S', school: 'Baylor'},
    {rank: 40, player: 'George Pickens', pos: 'WR', school: 'Georgia'},
    {rank: 41, player: 'Jahan Dotson', pos: 'WR', school: 'Penn State'},
    {rank: 42, player: 'Tyler Smith', pos: 'OT', school: 'Tulsa'},
    {rank: 43, player: 'Nik Bonitto', pos: 'EDGE', school: 'Oklahoma'},
    {rank: 44, player: 'Skyy Moore', pos: 'WR', school: 'Western Michigan'},
    {rank: 45, player: 'Bernhard Raimann', pos: 'OT', school: 'Central Michigan'},
    {rank: 46, player: 'Lewis Cine', pos: 'S', school: 'Georgia'},
    {rank: 47, player: 'David Ojabo', pos: 'EDGE', school: 'Michigan'},
    {rank: 48, player: 'Kenneth Walker III', pos: 'RB', school: 'Michigan State'},
    {rank: 49, player: 'Arnold Ebiketie', pos: 'EDGE', school: 'Penn State'},
    {rank: 50, player: 'Desmond Ridder', pos: 'QB', school: 'Cincinnati'},
  ],
};

const MILLER_2025: Board = {
  expertSlug: 'matt-miller',
  year: 2025,
  source:
    'https://www.espn.com/nfl/draft2025/insider/story/_/id/41981985/2025-nfl-draft-rankings-matt-miller-top-prospects-players-positions',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Abdul Carter', pos: 'EDGE', school: 'Penn State'},
    {rank: 2, player: 'Travis Hunter', pos: 'WR/CB', school: 'Colorado'},
    {rank: 3, player: 'Ashton Jeanty', pos: 'RB', school: 'Boise State'},
    {rank: 4, player: 'Mason Graham', pos: 'DT', school: 'Michigan'},
    {rank: 5, player: 'Jalon Walker', pos: 'EDGE', school: 'Georgia'},
    {rank: 6, player: 'Colston Loveland', pos: 'TE', school: 'Michigan'},
    {rank: 7, player: 'Will Johnson', pos: 'CB', school: 'Michigan'},
    {rank: 8, player: 'Kelvin Banks Jr.', pos: 'OT', school: 'Texas'},
    {rank: 9, player: 'Tyler Warren', pos: 'TE', school: 'Penn State'},
    {rank: 10, player: 'Armand Membou', pos: 'OT', school: 'Missouri'},
    {rank: 11, player: 'Jahdae Barron', pos: 'CB', school: 'Texas'},
    {rank: 12, player: 'Will Campbell', pos: 'OT', school: 'LSU'},
    {rank: 13, player: 'Luther Burden III', pos: 'WR', school: 'Missouri'},
    {rank: 14, player: 'Cam Ward', pos: 'QB', school: 'Miami'},
    {rank: 15, player: 'Jihaad Campbell', pos: 'LB', school: 'Alabama'},
    {rank: 16, player: 'Matthew Golden', pos: 'WR', school: 'Texas'},
    {rank: 17, player: 'Mike Green', pos: 'EDGE', school: 'Marshall'},
    {rank: 18, player: 'Nick Emmanwori', pos: 'S', school: 'South Carolina'},
    {rank: 19, player: 'Omarion Hampton', pos: 'RB', school: 'North Carolina'},
    {rank: 20, player: 'Walter Nolen', pos: 'DT', school: 'Mississippi'},
    {rank: 21, player: 'Malaki Starks', pos: 'S', school: 'Georgia'},
    {rank: 22, player: 'Tetairoa McMillan', pos: 'WR', school: 'Arizona'},
    {rank: 23, player: 'Emeka Egbuka', pos: 'WR', school: 'Ohio State'},
    {rank: 24, player: 'Tyler Booker', pos: 'OG', school: 'Alabama'},
    {rank: 25, player: 'Shedeur Sanders', pos: 'QB', school: 'Colorado'},
    {rank: 26, player: 'Derrick Harmon', pos: 'DT', school: 'Oregon'},
    {rank: 27, player: 'Shemar Stewart', pos: 'EDGE', school: 'Texas A&M'},
    {rank: 28, player: 'Mykel Williams', pos: 'EDGE', school: 'Georgia'},
    {rank: 29, player: 'Josh Simmons', pos: 'OT', school: 'Ohio State'},
    {rank: 30, player: 'Kenneth Grant', pos: 'DT', school: 'Michigan'},
    {rank: 31, player: 'Trey Amos', pos: 'CB', school: 'Mississippi'},
    {rank: 32, player: 'Grey Zabel', pos: 'OG', school: 'North Dakota State'},
    {rank: 33, player: 'Donovan Jackson', pos: 'OG', school: 'Ohio State'},
    {rank: 34, player: 'Mason Taylor', pos: 'TE', school: 'LSU'},
    {rank: 35, player: 'Josh Conerly Jr.', pos: 'OT', school: 'Oregon'},
    {rank: 36, player: 'Donovan Ezeiruaku', pos: 'EDGE', school: 'Boston College'},
    {rank: 37, player: 'Jaxson Dart', pos: 'QB', school: 'Mississippi'},
    {rank: 38, player: 'Quinshon Judkins', pos: 'RB', school: 'Ohio State'},
    {rank: 39, player: 'TreVeyon Henderson', pos: 'RB', school: 'Ohio State'},
    {rank: 40, player: 'Jaylin Noel', pos: 'WR', school: 'Iowa State'},
    {rank: 41, player: 'Jayden Higgins', pos: 'WR', school: 'Iowa State'},
    {rank: 42, player: 'Xavier Watts', pos: 'S', school: 'Notre Dame'},
    {rank: 43, player: 'Maxwell Hairston', pos: 'CB', school: 'Kentucky'},
    {rank: 44, player: 'Kaleb Johnson', pos: 'RB', school: 'Iowa'},
    {rank: 45, player: 'Carson Schwesinger', pos: 'LB', school: 'UCLA'},
    {rank: 46, player: 'Benjamin Morrison', pos: 'CB', school: 'Notre Dame'},
    {rank: 47, player: "Azareye'h Thomas", pos: 'CB', school: 'Florida State'},
    {rank: 48, player: 'Landon Jackson', pos: 'EDGE', school: 'Arkansas'},
    {rank: 49, player: 'Tyleik Williams', pos: 'DT', school: 'Ohio State'},
    {rank: 50, player: 'Alfred Collins', pos: 'DT', school: 'Texas'},
  ],
};

// ─────────────────────────────────────────────────────────────────
// Todd McShay (ESPN; partial — paywall) — top-10 only mostly
// ─────────────────────────────────────────────────────────────────

const MCSHAY_2019: Board = {
  expertSlug: 'mcshay',
  year: 2019,
  source:
    'https://www.espn.com/nfl/draft2019/insider/story/_/id/26581064/mcshay-final-rankings-top-300-prospects-2019-nfl-draft',
  confidence: 'low',
  note: 'Top 10 only. Ranks 11-32 paywalled at ESPN+ with no public reposts.',
  rankings: [
    {rank: 1, player: 'Nick Bosa', pos: 'EDGE', school: 'Ohio State'},
    {rank: 2, player: 'Quinnen Williams', pos: 'DT', school: 'Alabama'},
    {rank: 3, player: 'Josh Allen', pos: 'EDGE', school: 'Kentucky'},
    {rank: 4, player: 'Devin White', pos: 'LB', school: 'LSU'},
    {rank: 5, player: 'Christian Wilkins', pos: 'DT', school: 'Clemson'},
    {rank: 6, player: 'Rashan Gary', pos: 'EDGE', school: 'Michigan'},
    {rank: 7, player: 'T.J. Hockenson', pos: 'TE', school: 'Iowa'},
    {rank: 8, player: 'Ed Oliver', pos: 'DT', school: 'Houston'},
    {rank: 9, player: 'Jawaan Taylor', pos: 'OT', school: 'Florida'},
    {rank: 10, player: 'Devin Bush', pos: 'LB', school: 'Michigan'},
  ],
};

const MCSHAY_2020: Board = {
  expertSlug: 'mcshay',
  year: 2020,
  source:
    'https://bleacherreport.com/articles/2888161-todd-mcshay-2020-nfl-draft-big-board-final-rankings-released-before-round-1',
  confidence: 'low',
  note: 'Top 10 only. Ranks 11-32 paywalled.',
  rankings: [
    {rank: 1, player: 'Chase Young', pos: 'EDGE', school: 'Ohio State'},
    {rank: 2, player: 'Joe Burrow', pos: 'QB', school: 'LSU'},
    {rank: 3, player: 'Derrick Brown', pos: 'DT', school: 'Auburn'},
    {rank: 4, player: 'Isaiah Simmons', pos: 'LB', school: 'Clemson'},
    {rank: 5, player: 'Jeff Okudah', pos: 'CB', school: 'Ohio State'},
    {rank: 6, player: 'Jerry Jeudy', pos: 'WR', school: 'Alabama'},
    {rank: 7, player: 'Tua Tagovailoa', pos: 'QB', school: 'Alabama'},
    {rank: 8, player: 'Jedrick Wills Jr.', pos: 'OT', school: 'Alabama'},
    {rank: 9, player: 'Javon Kinlaw', pos: 'DT', school: 'South Carolina'},
    {rank: 10, player: 'CeeDee Lamb', pos: 'WR', school: 'Oklahoma'},
  ],
};

const MCSHAY_2021: Board = {
  expertSlug: 'mcshay',
  year: 2021,
  source:
    'https://bleacherreport.com/articles/2941428-todd-mcshay-2021-nfl-draft-big-board-trevor-lawrence-pitts-top-final-rankings',
  confidence: 'low',
  note: 'Top 10 only. Ranks 11-32 paywalled.',
  rankings: [
    {rank: 1, player: 'Trevor Lawrence', pos: 'QB', school: 'Clemson'},
    {rank: 2, player: 'Kyle Pitts', pos: 'TE', school: 'Florida'},
    {rank: 3, player: "Ja'Marr Chase", pos: 'WR', school: 'LSU'},
    {rank: 4, player: 'Zach Wilson', pos: 'QB', school: 'BYU'},
    {rank: 5, player: 'Penei Sewell', pos: 'OT', school: 'Oregon'},
    {rank: 6, player: 'DeVonta Smith', pos: 'WR', school: 'Alabama'},
    {rank: 7, player: 'Jaylen Waddle', pos: 'WR', school: 'Alabama'},
    {rank: 8, player: 'Rashawn Slater', pos: 'OT', school: 'Northwestern'},
    {rank: 9, player: 'Trey Lance', pos: 'QB', school: 'North Dakota State'},
    {rank: 10, player: 'Patrick Surtain II', pos: 'CB', school: 'Alabama'},
  ],
};

// ─────────────────────────────────────────────────────────────────
// Walter Football / Charlie Campbell
// ─────────────────────────────────────────────────────────────────

const WALTER_2018: Board = {
  expertSlug: 'walter-football',
  year: 2018,
  source: 'https://walterfootball.com/nfldraftbigboard2018.php',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Saquon Barkley', pos: 'RB', school: 'Penn State'},
    {rank: 2, player: 'Quenton Nelson', pos: 'OG', school: 'Notre Dame'},
    {rank: 3, player: 'Bradley Chubb', pos: 'EDGE', school: 'NC State'},
    {rank: 4, player: 'Sam Darnold', pos: 'QB', school: 'USC'},
    {rank: 5, player: 'Derwin James', pos: 'S', school: 'Florida State'},
    {rank: 6, player: 'Vita Vea', pos: 'DT', school: 'Washington'},
    {rank: 7, player: 'Tremaine Edmunds', pos: 'LB', school: 'Virginia Tech'},
    {rank: 8, player: "Da'Ron Payne", pos: 'DT', school: 'Alabama'},
    {rank: 9, player: 'Minkah Fitzpatrick', pos: 'S', school: 'Alabama'},
    {rank: 10, player: 'Roquan Smith', pos: 'LB', school: 'Georgia'},
    {rank: 11, player: 'Joshua Jackson', pos: 'CB', school: 'Iowa'},
    {rank: 12, player: 'Denzel Ward', pos: 'CB', school: 'Ohio State'},
    {rank: 13, player: 'Lamar Jackson', pos: 'QB', school: 'Louisville'},
    {rank: 14, player: 'Josh Rosen', pos: 'QB', school: 'UCLA'},
    {rank: 15, player: 'Mike McGlinchey', pos: 'OT', school: 'Notre Dame'},
    {rank: 16, player: 'Calvin Ridley', pos: 'WR', school: 'Alabama'},
    {rank: 17, player: 'Taven Bryan', pos: 'DT', school: 'Florida'},
    {rank: 18, player: 'Courtland Sutton', pos: 'WR', school: 'SMU'},
    {rank: 19, player: 'Arden Key', pos: 'EDGE', school: 'LSU'},
    {rank: 20, player: 'Billy Price', pos: 'C', school: 'Ohio State'},
    {rank: 21, player: 'Donte Jackson', pos: 'CB', school: 'LSU'},
    {rank: 22, player: 'Sony Michel', pos: 'RB', school: 'Georgia'},
    {rank: 23, player: 'Hayden Hurst', pos: 'TE', school: 'South Carolina'},
    {rank: 24, player: 'Josh Allen', pos: 'QB', school: 'Wyoming'},
    {rank: 25, player: 'Carlton Davis', pos: 'CB', school: 'Auburn'},
    {rank: 26, player: 'Mike Hughes', pos: 'CB', school: 'Central Florida'},
    {rank: 27, player: 'Jaire Alexander', pos: 'CB', school: 'Louisville'},
    {rank: 28, player: 'Rashaan Evans', pos: 'LB', school: 'Alabama'},
    {rank: 29, player: 'Derrius Guice', pos: 'RB', school: 'LSU'},
    {rank: 30, player: 'Terrell Edmunds', pos: 'S', school: 'Virginia Tech'},
    {rank: 31, player: 'Marcus Davenport', pos: 'EDGE', school: 'Texas-San Antonio'},
    {rank: 32, player: 'Baker Mayfield', pos: 'QB', school: 'Oklahoma'},
    {rank: 33, player: 'Christian Kirk', pos: 'WR', school: 'Texas A&M'},
    {rank: 34, player: 'Nick Chubb', pos: 'RB', school: 'Georgia'},
    {rank: 35, player: 'Tim Settle', pos: 'DT', school: 'Virginia Tech'},
    {rank: 36, player: 'James Daniels', pos: 'C', school: 'Iowa'},
    {rank: 37, player: 'Equanimeous St. Brown', pos: 'WR', school: 'Notre Dame'},
    {rank: 38, player: 'Justin Reid', pos: 'S', school: 'Stanford'},
    {rank: 39, player: 'Will Hernandez', pos: 'OG', school: 'UTEP'},
    {rank: 40, player: 'Kolton Miller', pos: 'OT', school: 'UCLA'},
    {rank: 41, player: 'Leighton Vander Esch', pos: 'LB', school: 'Boise State'},
    {rank: 42, player: 'D.J. Moore', pos: 'WR', school: 'Maryland'},
    {rank: 43, player: 'Harold Landry', pos: 'EDGE', school: 'Boston College'},
    {rank: 44, player: 'JC Jackson', pos: 'CB', school: 'Maryland'},
    {rank: 45, player: 'Dorance Armstrong Jr.', pos: 'EDGE', school: 'Kansas'},
    {rank: 46, player: 'Isaiah Wynn', pos: 'OT', school: 'Georgia'},
    {rank: 47, player: 'Kerryon Johnson', pos: 'RB', school: 'Auburn'},
    {rank: 48, player: 'Sam Hubbard', pos: 'EDGE', school: 'Ohio State'},
    {rank: 49, player: 'Ronnie Harrison', pos: 'S', school: 'Alabama'},
    {rank: 50, player: 'Jordan Whitehead', pos: 'S', school: 'Pittsburgh'},
  ],
};

const WALTER_2019: Board = {
  expertSlug: 'walter-football',
  year: 2019,
  source: 'https://walterfootball.com/nfldraftbigboard2019.php',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Quinnen Williams', pos: 'DT', school: 'Alabama'},
    {rank: 2, player: 'Nick Bosa', pos: 'EDGE', school: 'Ohio State'},
    {rank: 3, player: 'Devin White', pos: 'LB', school: 'LSU'},
    {rank: 4, player: 'Josh Allen', pos: 'LB', school: 'Kentucky'},
    {rank: 5, player: 'Montez Sweat', pos: 'EDGE', school: 'Mississippi State'},
    {rank: 6, player: 'Rashan Gary', pos: 'DT', school: 'Michigan'},
    {rank: 7, player: 'Christian Wilkins', pos: 'DT', school: 'Clemson'},
    {rank: 8, player: 'Jeffery Simmons', pos: 'DT', school: 'Mississippi State'},
    {rank: 9, player: 'Jawaan Taylor', pos: 'OT', school: 'Florida'},
    {rank: 10, player: 'Cody Ford', pos: 'OT', school: 'Oklahoma'},
    {rank: 11, player: 'Ed Oliver', pos: 'DT', school: 'Houston'},
    {rank: 12, player: 'DeAndre Baker', pos: 'CB', school: 'Georgia'},
    {rank: 13, player: "Dre'Mont Jones", pos: 'DT', school: 'Ohio State'},
    {rank: 14, player: 'Clelin Ferrell', pos: 'EDGE', school: 'Clemson'},
    {rank: 15, player: 'Josh Jacobs', pos: 'RB', school: 'Alabama'},
    {rank: 16, player: 'Daniel Jones', pos: 'QB', school: 'Duke'},
    {rank: 17, player: 'Drew Lock', pos: 'QB', school: 'Missouri'},
    {rank: 18, player: 'Johnathan Abram', pos: 'S', school: 'Mississippi State'},
    {rank: 19, player: 'Erik McCoy', pos: 'C', school: 'Texas A&M'},
    {rank: 20, player: 'Andre Dillard', pos: 'OT', school: 'Washington State'},
    {rank: 21, player: 'Jachai Polite', pos: 'EDGE', school: 'Florida'},
    {rank: 22, player: 'Greedy Williams', pos: 'CB', school: 'LSU'},
    {rank: 23, player: 'Byron Murphy', pos: 'CB', school: 'Washington'},
    {rank: 24, player: 'Greg Little', pos: 'OT', school: 'Mississippi'},
    {rank: 25, player: 'T.J. Hockenson', pos: 'TE', school: 'Iowa'},
    {rank: 26, player: 'Dwayne Haskins', pos: 'QB', school: 'Ohio State'},
    {rank: 27, player: 'Darnell Savage', pos: 'S', school: 'Maryland'},
    {rank: 28, player: 'Kyler Murray', pos: 'QB', school: 'Oklahoma'},
    {rank: 29, player: 'Jonah Williams', pos: 'OT', school: 'Alabama'},
    {rank: 30, player: 'D.K. Metcalf', pos: 'WR', school: 'Mississippi'},
    {rank: 31, player: 'Devin Bush', pos: 'LB', school: 'Michigan'},
    {rank: 32, player: 'Dexter Lawrence', pos: 'DT', school: 'Clemson'},
    {rank: 33, player: 'Juan Thornhill', pos: 'S', school: 'Virginia'},
    {rank: 34, player: 'Deebo Samuel', pos: 'WR', school: 'South Carolina'},
    {rank: 35, player: 'Damien Harris', pos: 'RB', school: 'Alabama'},
    {rank: 36, player: 'Ryan Finley', pos: 'QB', school: 'NC State'},
    {rank: 37, player: 'Brian Burns', pos: 'EDGE', school: 'Florida State'},
    {rank: 38, player: 'Zach Allen', pos: 'EDGE', school: 'Boston College'},
    {rank: 39, player: 'Marquise Brown', pos: 'WR', school: 'Oklahoma'},
    {rank: 40, player: 'Amani Oruwariye', pos: 'CB', school: 'Penn State'},
    {rank: 41, player: 'Mack Wilson', pos: 'LB', school: 'Alabama'},
    {rank: 42, player: 'Clayton Thorson', pos: 'QB', school: 'Northwestern'},
    {rank: 43, player: 'Elgton Jenkins', pos: 'C', school: 'Mississippi State'},
    {rank: 44, player: 'Tre Lamar', pos: 'LB', school: 'Clemson'},
    {rank: 45, player: 'Jerry Tillery', pos: 'DT', school: 'Notre Dame'},
    {rank: 46, player: 'Nasir Adderley', pos: 'S', school: 'Delaware'},
    {rank: 47, player: 'Noah Fant', pos: 'TE', school: 'Iowa'},
    {rank: 48, player: 'Chase Winovich', pos: 'EDGE', school: 'Michigan'},
    {rank: 49, player: 'Kelvin Harmon', pos: 'WR', school: 'NC State'},
    {rank: 50, player: 'Taylor Rapp', pos: 'S', school: 'Washington'},
  ],
};

const WALTER_2020: Board = {
  expertSlug: 'walter-football',
  year: 2020,
  source: 'https://walterfootball.com/nfldraftbigboard2020.php',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Chase Young', pos: 'EDGE', school: 'Ohio State'},
    {rank: 2, player: 'Derrick Brown', pos: 'DT', school: 'Auburn'},
    {rank: 3, player: 'Jeff Okudah', pos: 'CB', school: 'Ohio State'},
    {rank: 4, player: 'Andrew Thomas', pos: 'OT', school: 'Georgia'},
    {rank: 5, player: 'Mekhi Becton', pos: 'OT', school: 'Louisville'},
    {rank: 6, player: 'Tua Tagovailoa', pos: 'QB', school: 'Alabama'},
    {rank: 7, player: 'CeeDee Lamb', pos: 'WR', school: 'Oklahoma'},
    {rank: 8, player: 'Isaiah Simmons', pos: 'S', school: 'Clemson'},
    {rank: 9, player: 'Kenneth Murray', pos: 'LB', school: 'Oklahoma'},
    {rank: 10, player: 'C.J. Henderson', pos: 'CB', school: 'Florida'},
    {rank: 11, player: 'Jerry Jeudy', pos: 'WR', school: 'Alabama'},
    {rank: 12, player: 'Jedrick Wills', pos: 'OT', school: 'Alabama'},
    {rank: 13, player: 'Joe Burrow', pos: 'QB', school: 'LSU'},
    {rank: 14, player: "D'Andre Swift", pos: 'RB', school: 'Georgia'},
    {rank: 15, player: 'Javon Kinlaw', pos: 'DT', school: 'South Carolina'},
    {rank: 16, player: 'Xavier McKinney', pos: 'S', school: 'Alabama'},
    {rank: 17, player: 'Jonathan Taylor', pos: 'RB', school: 'Wisconsin'},
    {rank: 18, player: 'Tristan Wirfs', pos: 'OT', school: 'Iowa'},
    {rank: 19, player: 'Justin Herbert', pos: 'QB', school: 'Oregon'},
    {rank: 20, player: 'Austin Jackson', pos: 'OT', school: 'USC'},
    {rank: 21, player: 'Jalen Reagor', pos: 'WR', school: 'TCU'},
    {rank: 22, player: 'Laviska Shenault Jr.', pos: 'WR', school: 'Colorado'},
    {rank: 23, player: 'Yetur Gross-Matos', pos: 'EDGE', school: 'Penn State'},
    {rank: 24, player: 'A.J. Epenesa', pos: 'EDGE', school: 'Iowa'},
    {rank: 25, player: 'Henry Ruggs III', pos: 'WR', school: 'Alabama'},
    {rank: 26, player: 'Ross Blacklock', pos: 'DT', school: 'TCU'},
    {rank: 27, player: 'Prince Tega Wanogho', pos: 'OT', school: 'Auburn'},
    {rank: 28, player: "K'Lavon Chaisson", pos: 'LB', school: 'LSU'},
    {rank: 29, player: 'Damon Arnette', pos: 'CB', school: 'Ohio State'},
    {rank: 30, player: 'Tee Higgins', pos: 'WR', school: 'Clemson'},
    {rank: 31, player: 'Patrick Queen', pos: 'LB', school: 'LSU'},
    {rank: 32, player: 'Clyde Edwards-Helaire', pos: 'RB', school: 'LSU'},
    {rank: 33, player: 'Cameron Dantzler', pos: 'CB', school: 'Mississippi State'},
    {rank: 34, player: 'Noah Igbinoghene', pos: 'CB', school: 'Auburn'},
    {rank: 35, player: 'Isaiah Wilson', pos: 'OT', school: 'Georgia'},
    {rank: 36, player: 'Trevon Diggs', pos: 'CB', school: 'Alabama'},
    {rank: 37, player: 'Trey Adams', pos: 'OT', school: 'Washington'},
    {rank: 38, player: 'Zack Baun', pos: 'LB', school: 'Wisconsin'},
    {rank: 39, player: 'Justin Madubuike', pos: 'DT', school: 'Texas A&M'},
    {rank: 40, player: 'Kristian Fulton', pos: 'CB', school: 'LSU'},
    {rank: 41, player: 'Kyle Dugger', pos: 'S', school: 'Lenoir-Rhyne'},
    {rank: 42, player: 'Shane Lemieux', pos: 'OG', school: 'Oregon'},
    {rank: 43, player: 'Terrell Lewis', pos: 'LB', school: 'Alabama'},
    {rank: 44, player: 'A.J. Terrell', pos: 'CB', school: 'Clemson'},
    {rank: 45, player: 'Justin Jefferson', pos: 'WR', school: 'LSU'},
    {rank: 46, player: 'Cam Akers', pos: 'RB', school: 'Florida State'},
    {rank: 47, player: 'Jordyn Brooks', pos: 'LB', school: 'Texas Tech'},
    {rank: 48, player: 'Zack Moss', pos: 'RB', school: 'Utah'},
    {rank: 49, player: 'Chase Claypool', pos: 'WR', school: 'Notre Dame'},
    {rank: 50, player: 'J.K. Dobbins', pos: 'RB', school: 'Ohio State'},
  ],
};

const WALTER_2021: Board = {
  expertSlug: 'walter-football',
  year: 2021,
  source: 'https://walterfootball.com/nfldraftbigboard2021.php',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Trevor Lawrence', pos: 'QB', school: 'Clemson'},
    {rank: 2, player: 'Kyle Pitts', pos: 'TE', school: 'Florida'},
    {rank: 3, player: 'Penei Sewell', pos: 'OT', school: 'Oregon'},
    {rank: 4, player: "Ja'Marr Chase", pos: 'WR', school: 'LSU'},
    {rank: 5, player: 'Justin Fields', pos: 'QB', school: 'Ohio State'},
    {rank: 6, player: 'Jaylen Waddle', pos: 'WR', school: 'Alabama'},
    {rank: 7, player: 'DeVonta Smith', pos: 'WR', school: 'Alabama'},
    {rank: 8, player: 'Jaycee Horn', pos: 'CB', school: 'South Carolina'},
    {rank: 9, player: 'Jaelan Phillips', pos: 'EDGE', school: 'Miami'},
    {rank: 10, player: 'Alijah Vera-Tucker', pos: 'OT', school: 'USC'},
    {rank: 11, player: 'Patrick Surtain', pos: 'CB', school: 'Alabama'},
    {rank: 12, player: 'Kwity Paye', pos: 'DT', school: 'Michigan'},
    {rank: 13, player: 'Alex Leatherwood', pos: 'OT', school: 'Alabama'},
    {rank: 14, player: 'Zach Wilson', pos: 'QB', school: 'BYU'},
    {rank: 15, player: 'Jamin Davis', pos: 'LB', school: 'Kentucky'},
    {rank: 16, player: 'Travis Etienne', pos: 'RB', school: 'Clemson'},
    {rank: 17, player: 'Zaven Collins', pos: 'LB', school: 'Tulsa'},
    {rank: 18, player: 'Sam Cosmi', pos: 'OT', school: 'Texas'},
    {rank: 19, player: 'Trey Lance', pos: 'QB', school: 'North Dakota State'},
    {rank: 20, player: 'Jackson Carman', pos: 'OT', school: 'Clemson'},
    {rank: 21, player: 'Caleb Farley', pos: 'CB', school: 'Virginia Tech'},
    {rank: 22, player: 'Andre Cisco', pos: 'S', school: 'Syracuse'},
    {rank: 23, player: 'Micah Parsons', pos: 'LB', school: 'Penn State'},
    {rank: 24, player: 'Christian Barmore', pos: 'DT', school: 'Alabama'},
    {rank: 25, player: 'Aaron Robinson', pos: 'CB', school: 'Central Florida'},
    {rank: 26, player: 'Rashawn Slater', pos: 'OT', school: 'Northwestern'},
    {rank: 27, player: 'Daviyon Nixon', pos: 'EDGE', school: 'Iowa'},
    {rank: 28, player: 'Jeremiah Owusu-Koramoah', pos: 'LB', school: 'Notre Dame'},
    {rank: 29, player: 'Kadarius Toney', pos: 'WR', school: 'Florida'},
    {rank: 30, player: 'Christian Darrisaw', pos: 'OT', school: 'Virginia Tech'},
    {rank: 31, player: 'Jevon Holland', pos: 'S', school: 'Oregon'},
    {rank: 32, player: 'Najee Harris', pos: 'RB', school: 'Alabama'},
    {rank: 33, player: 'Trevon Moehrig', pos: 'S', school: 'TCU'},
    {rank: 34, player: 'Gregory Rousseau', pos: 'EDGE', school: 'Miami'},
    {rank: 35, player: 'Kyle Trask', pos: 'QB', school: 'Florida'},
    {rank: 36, player: 'Eric Stokes', pos: 'CB', school: 'Georgia'},
    {rank: 37, player: 'Jayson Oweh', pos: 'LB', school: 'Penn State'},
    {rank: 38, player: 'Trey Smith', pos: 'OG', school: 'Tennessee'},
    {rank: 39, player: 'Jalen Mayfield', pos: 'OT', school: 'Michigan'},
    {rank: 40, player: 'Dayo Odeyingbo', pos: 'EDGE', school: 'Vanderbilt'},
    {rank: 41, player: 'Greg Newsome II', pos: 'CB', school: 'Northwestern'},
    {rank: 42, player: 'Jay Tufele', pos: 'DT', school: 'USC'},
    {rank: 43, player: 'Joe Tryon', pos: 'EDGE', school: 'Washington'},
    {rank: 44, player: 'Levi Onwuzurike', pos: 'DT', school: 'Washington'},
    {rank: 45, player: 'Pat Freiermuth', pos: 'TE', school: 'Penn State'},
    {rank: 46, player: 'Rondale Moore', pos: 'WR', school: 'Purdue'},
    {rank: 47, player: 'Kenny Gainwell', pos: 'RB', school: 'Memphis'},
    {rank: 48, player: 'Rashod Bateman', pos: 'WR', school: 'Minnesota'},
    {rank: 49, player: 'Landon Dickerson', pos: 'C', school: 'Alabama'},
    {rank: 50, player: 'Javonte Williams', pos: 'RB', school: 'North Carolina'},
  ],
};

const WALTER_2022: Board = {
  expertSlug: 'walter-football',
  year: 2022,
  source: 'https://walterfootball.com/nfldraftbigboard2022.php',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Travon Walker', pos: 'EDGE', school: 'Georgia'},
    {rank: 2, player: 'Drake London', pos: 'WR', school: 'USC'},
    {rank: 3, player: 'Aidan Hutchinson', pos: 'EDGE', school: 'Michigan'},
    {rank: 4, player: 'Ahmad Gardner', pos: 'CB', school: 'Cincinnati'},
    {rank: 5, player: 'Derek Stingley', pos: 'CB', school: 'LSU'},
    {rank: 6, player: 'Charles Cross', pos: 'OT', school: 'Mississippi State'},
    {rank: 7, player: 'Garrett Wilson', pos: 'WR', school: 'Ohio State'},
    {rank: 8, player: 'Ikem Ekwonu', pos: 'OT', school: 'NC State'},
    {rank: 9, player: 'Evan Neal', pos: 'OT', school: 'Alabama'},
    {rank: 10, player: 'Jordan Davis', pos: 'DT', school: 'Georgia'},
    {rank: 11, player: 'Kyle Hamilton', pos: 'S', school: 'Notre Dame'},
    {rank: 12, player: 'Kayvon Thibodeaux', pos: 'EDGE', school: 'Oregon'},
    {rank: 13, player: 'Jermaine Johnson', pos: 'EDGE', school: 'Florida State'},
    {rank: 14, player: 'Jameson Williams', pos: 'WR', school: 'Alabama'},
    {rank: 15, player: 'Trent McDuffie', pos: 'CB', school: 'Washington'},
    {rank: 16, player: 'Kenny Pickett', pos: 'QB', school: 'Pittsburgh'},
    {rank: 17, player: 'Chris Olave', pos: 'WR', school: 'Ohio State'},
    {rank: 18, player: 'George Karlaftis', pos: 'EDGE', school: 'Purdue'},
    {rank: 19, player: 'Treylon Burks', pos: 'WR', school: 'Arkansas'},
    {rank: 20, player: 'Christian Watson', pos: 'WR', school: 'North Dakota State'},
    {rank: 21, player: 'David Ojabo', pos: 'EDGE', school: 'Michigan'},
    {rank: 22, player: 'Tyler Linderbaum', pos: 'C', school: 'Iowa'},
    {rank: 23, player: "Wan'Dale Robinson", pos: 'WR', school: 'Kentucky'},
    {rank: 24, player: 'Damone Clark', pos: 'LB', school: 'LSU'},
    {rank: 25, player: 'Alec Pierce', pos: 'WR', school: 'Cincinnati'},
    {rank: 26, player: 'Daxton Hill', pos: 'S', school: 'Michigan'},
    {rank: 27, player: 'Trevor Penning', pos: 'OT', school: 'Northern Iowa'},
    {rank: 28, player: 'Kenyon Green', pos: 'OG', school: 'Texas A&M'},
    {rank: 29, player: 'Jahan Dotson', pos: 'WR', school: 'Penn State'},
    {rank: 30, player: 'Nakobe Dean', pos: 'LB', school: 'Georgia'},
    {rank: 31, player: 'Lewis Cine', pos: 'S', school: 'Georgia'},
    {rank: 32, player: 'Devin Lloyd', pos: 'LB', school: 'Utah'},
    {rank: 33, player: 'Kyler Gordon', pos: 'CB', school: 'Washington'},
    {rank: 34, player: 'Roger McCreary', pos: 'CB', school: 'Auburn'},
    {rank: 35, player: 'Breece Hall', pos: 'RB', school: 'Iowa State'},
    {rank: 36, player: 'Nick Petit-Frere', pos: 'OT', school: 'Ohio State'},
    {rank: 37, player: 'Kaiir Elam', pos: 'CB', school: 'Florida'},
    {rank: 38, player: 'Logan Hall', pos: 'EDGE', school: 'Houston'},
    {rank: 39, player: 'Quay Walker', pos: 'LB', school: 'Georgia'},
    {rank: 40, player: 'Andrew Booth Jr.', pos: 'CB', school: 'Clemson'},
    {rank: 41, player: 'Malik Willis', pos: 'QB', school: 'Liberty'},
    {rank: 42, player: 'DeMarvin Leal', pos: 'DT', school: 'Texas A&M'},
    {rank: 43, player: 'George Pickens', pos: 'WR', school: 'Georgia'},
    {rank: 44, player: 'Zachary Carter', pos: 'DT', school: 'Florida'},
    {rank: 45, player: 'Akayleb Evans', pos: 'CB', school: 'Missouri'},
    {rank: 46, player: 'Drake Jackson', pos: 'EDGE', school: 'USC'},
    {rank: 47, player: 'Brian Robinson', pos: 'RB', school: 'Alabama'},
    {rank: 48, player: 'Ed Ingram', pos: 'OG', school: 'LSU'},
    {rank: 49, player: 'Sam Howell', pos: 'QB', school: 'North Carolina'},
    {rank: 50, player: 'Boye Mafe', pos: 'EDGE', school: 'Minnesota'},
  ],
};

const WALTER_2023: Board = {
  expertSlug: 'walter-football',
  year: 2023,
  source: 'https://walterfootball.com/nfldraftbigboard2023.php',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Bijan Robinson', pos: 'RB', school: 'Texas'},
    {rank: 2, player: 'Bryce Young', pos: 'QB', school: 'Alabama'},
    {rank: 3, player: 'Will Anderson', pos: 'EDGE', school: 'Alabama'},
    {rank: 4, player: 'C.J. Stroud', pos: 'QB', school: 'Ohio State'},
    {rank: 5, player: 'Peter Skoronski', pos: 'OT', school: 'Northwestern'},
    {rank: 6, player: 'Jalen Carter', pos: 'DT', school: 'Georgia'},
    {rank: 7, player: 'Jahmyr Gibbs', pos: 'RB', school: 'Alabama'},
    {rank: 8, player: 'Tyree Wilson', pos: 'EDGE', school: 'Texas Tech'},
    {rank: 9, player: 'Paris Johnson', pos: 'OT', school: 'Ohio State'},
    {rank: 10, player: 'Quentin Johnston', pos: 'WR', school: 'TCU'},
    {rank: 11, player: 'Jaxon Smith-Njigba', pos: 'WR', school: 'Ohio State'},
    {rank: 12, player: 'Christian Gonzalez', pos: 'CB', school: 'Oregon'},
    {rank: 13, player: 'Brian Branch', pos: 'S', school: 'Alabama'},
    {rank: 14, player: 'Devon Witherspoon', pos: 'CB', school: 'Illinois'},
    {rank: 15, player: 'Joey Porter Jr.', pos: 'CB', school: 'Penn State'},
    {rank: 16, player: 'Will McDonald IV', pos: 'EDGE', school: 'Iowa State'},
    {rank: 17, player: 'Calijah Kancey', pos: 'DT', school: 'Pittsburgh'},
    {rank: 18, player: 'Jack Campbell', pos: 'LB', school: 'Iowa'},
    {rank: 19, player: 'Jordan Addison', pos: 'WR', school: 'USC'},
    {rank: 20, player: 'Sam LaPorta', pos: 'TE', school: 'Iowa'},
    {rank: 21, player: 'Lukas Van Ness', pos: 'EDGE', school: 'Iowa'},
    {rank: 22, player: 'Myles Murphy', pos: 'EDGE', school: 'Clemson'},
    {rank: 23, player: 'Antonio Johnson', pos: 'S', school: 'Texas A&M'},
    {rank: 24, player: 'Michael Mayer', pos: 'TE', school: 'Notre Dame'},
    {rank: 25, player: 'Tuli Tuipulotu', pos: 'DT', school: 'USC'},
    {rank: 26, player: 'Dalton Kincaid', pos: 'TE', school: 'Utah'},
    {rank: 27, player: 'Anthony Richardson', pos: 'QB', school: 'Florida'},
    {rank: 28, player: 'Deonte Banks', pos: 'CB', school: 'Maryland'},
    {rank: 29, player: 'Drew Sanders', pos: 'LB', school: 'Arkansas'},
    {rank: 30, player: 'Anton Harrison', pos: 'OT', school: 'Oklahoma'},
    {rank: 31, player: 'Emmanuel Forbes', pos: 'CB', school: 'Mississippi State'},
    {rank: 32, player: 'Jartavius Martin', pos: 'CB', school: 'Illinois'},
    {rank: 33, player: 'Tyler Steen', pos: 'OT', school: 'Alabama'},
    {rank: 34, player: 'Darnell Washington', pos: 'TE', school: 'Georgia'},
    {rank: 35, player: 'Darnell Wright', pos: 'OT', school: 'Tennessee'},
    {rank: 36, player: 'Steve Avila', pos: 'C', school: 'TCU'},
    {rank: 37, player: 'Mazi Smith', pos: 'DT', school: 'Michigan'},
    {rank: 38, player: 'Cody Mauch', pos: 'OT', school: 'North Dakota State'},
    {rank: 39, player: 'Zach Charbonnet', pos: 'RB', school: 'UCLA'},
    {rank: 40, player: 'Zach Evans', pos: 'RB', school: 'Mississippi'},
    {rank: 41, player: 'Will Levis', pos: 'QB', school: 'Kentucky'},
    {rank: 42, player: "Henry To'o'To'o", pos: 'LB', school: 'Alabama'},
    {rank: 43, player: 'Kelee Ringo', pos: 'CB', school: 'Georgia'},
    {rank: 44, player: 'Zay Flowers', pos: 'WR', school: 'Boston College'},
    {rank: 45, player: 'Luke Musgrave', pos: 'TE', school: 'Oregon State'},
    {rank: 46, player: 'Matthew Bergeron', pos: 'OT', school: 'Syracuse'},
    {rank: 47, player: 'B.J. Ojulari', pos: 'EDGE', school: 'LSU'},
    {rank: 48, player: 'Clark Phillips', pos: 'CB', school: 'Utah'},
    {rank: 49, player: 'Devon Achane', pos: 'RB', school: 'Texas A&M'},
    {rank: 50, player: 'Isaiah Foskey', pos: 'EDGE', school: 'Notre Dame'},
  ],
};

const WALTER_2024: Board = {
  expertSlug: 'walter-football',
  year: 2024,
  source: 'https://walterfootball.com/nfldraftbigboard2024.php',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Drake Maye', pos: 'QB', school: 'North Carolina'},
    {rank: 2, player: 'Malik Nabers', pos: 'WR', school: 'LSU'},
    {rank: 3, player: 'Caleb Williams', pos: 'QB', school: 'USC'},
    {rank: 4, player: 'Jayden Daniels', pos: 'QB', school: 'LSU'},
    {rank: 5, player: 'Marvin Harrison Jr.', pos: 'WR', school: 'Ohio State'},
    {rank: 6, player: 'Laiatu Latu', pos: 'EDGE', school: 'UCLA'},
    {rank: 7, player: 'J.C. Latham', pos: 'OT', school: 'Alabama'},
    {rank: 8, player: 'Brock Bowers', pos: 'TE', school: 'Georgia'},
    {rank: 9, player: 'Amarius Mims', pos: 'OT', school: 'Georgia'},
    {rank: 10, player: 'Joe Alt', pos: 'OT', school: 'Notre Dame'},
    {rank: 11, player: 'Dallas Turner', pos: 'LB', school: 'Alabama'},
    {rank: 12, player: 'Rome Odunze', pos: 'WR', school: 'Washington'},
    {rank: 13, player: 'Cooper DeJean', pos: 'CB', school: 'Iowa'},
    {rank: 14, player: 'Terrion Arnold', pos: 'CB', school: 'Alabama'},
    {rank: 15, player: 'Byron Murphy II', pos: 'DT', school: 'Texas'},
    {rank: 16, player: 'Troy Fautanu', pos: 'OT', school: 'Washington'},
    {rank: 17, player: 'Jackson Powers-Johnson', pos: 'C', school: 'Oregon'},
    {rank: 18, player: 'Jared Verse', pos: 'EDGE', school: 'Florida State'},
    {rank: 19, player: 'Nate Wiggins', pos: 'CB', school: 'Clemson'},
    {rank: 20, player: 'Quinyon Mitchell', pos: 'CB', school: 'Toledo'},
    {rank: 21, player: 'Olu Fashanu', pos: 'OT', school: 'Penn State'},
    {rank: 22, player: 'Brian Thomas Jr.', pos: 'WR', school: 'LSU'},
    {rank: 23, player: 'Xavier Worthy', pos: 'WR', school: 'Texas'},
    {rank: 24, player: 'Kris Jenkins', pos: 'DT', school: 'Michigan'},
    {rank: 25, player: 'Tyler Guyton', pos: 'OT', school: 'Alabama'},
    {rank: 26, player: 'Taliese Fuaga', pos: 'OT', school: 'Oregon State'},
    {rank: 27, player: 'Johnny Newton', pos: 'DT', school: 'Illinois'},
    {rank: 28, player: 'Darius Robinson', pos: 'DT', school: 'Missouri'},
    {rank: 29, player: 'Kool-Aid McKinstry', pos: 'CB', school: 'Alabama'},
    {rank: 30, player: 'Xavier Legette', pos: 'WR', school: 'South Carolina'},
    {rank: 31, player: 'Adonai Mitchell', pos: 'WR', school: 'Texas'},
    {rank: 32, player: 'Jordan Morgan', pos: 'OT', school: 'Arizona'},
    {rank: 33, player: 'Graham Barton', pos: 'OT', school: 'Duke'},
    {rank: 34, player: 'Ennis Rakestraw', pos: 'CB', school: 'Missouri'},
    {rank: 35, player: 'Keon Coleman', pos: 'WR', school: 'Florida State'},
    {rank: 36, player: 'Kamari Lassiter', pos: 'CB', school: 'Georgia'},
    {rank: 37, player: 'Bo Nix', pos: 'QB', school: 'Oregon'},
    {rank: 38, player: 'J.J. McCarthy', pos: 'QB', school: 'Michigan'},
    {rank: 39, player: 'Chop Robinson', pos: 'EDGE', school: 'Penn State'},
    {rank: 40, player: 'Michael Hall Jr.', pos: 'DT', school: 'Ohio State'},
    {rank: 41, player: 'Kamren Kinchens', pos: 'S', school: 'Miami'},
    {rank: 42, player: 'Ricky Pearsall', pos: 'WR', school: 'Florida'},
    {rank: 43, player: 'Ladd McConkey', pos: 'WR', school: 'Georgia'},
    {rank: 44, player: "T'Vondre Sweat", pos: 'DT', school: 'Texas'},
    {rank: 45, player: 'Kingsley Suamataia', pos: 'OT', school: 'BYU'},
    {rank: 46, player: 'Javon Bullard', pos: 'S', school: 'Georgia'},
    {rank: 47, player: 'Layden Robinson', pos: 'OG', school: 'Texas A&M'},
    {rank: 48, player: 'Edgerrin Cooper', pos: 'LB', school: 'Texas A&M'},
    {rank: 49, player: 'Adisa Isaac', pos: 'EDGE', school: 'Penn State'},
    {rank: 50, player: 'Johnny Dixon', pos: 'CB', school: 'Penn State'},
  ],
};

// Note: Brugler 2018 (full top 100), PFF 2018-2024 boards, Trapasso 2018-2024
// boards, Josh Norris 2020 partial — kept in BOARDS_PART2 for file readability.
// See expert-rankings-data-part2.ts for those.

export const BOARDS_PART1: Board[] = [
  DJ_2019,
  DJ_2020,
  DJ_2021,
  DJ_2022,
  KIPER_2020,
  KIPER_2021,
  KIPER_2022,
  MILLER_2018,
  MILLER_2019,
  MILLER_2020,
  MILLER_2022,
  MILLER_2025,
  MCSHAY_2019,
  MCSHAY_2020,
  MCSHAY_2021,
  WALTER_2018,
  WALTER_2019,
  WALTER_2020,
  WALTER_2021,
  WALTER_2022,
  WALTER_2023,
  WALTER_2024,
];
