/**
 * Part 3: Bucky Brooks + Peter Schrager first-round mock drafts (2018-2023).
 *
 * Why mocks instead of big boards: Brooks publishes only "Top 5 by Position"
 * lists; Schrager publishes only mock drafts. Neither has a numbered Top 50
 * Big Board for any of these years. We treat the mock pick number as their
 * "rank" for that player — a fair proxy for the Oracle leaderboard since it
 * already compares predicted rank vs. actual draft pick.
 */

import type {Board} from './expert-rankings-data.js';

// ─── Bucky Brooks ─────────────────────────────────────────────────

const BROOKS_2018: Board = {
  expertSlug: 'bucky',
  year: 2018,
  source: 'https://www.nfl.com/news/bucky-brooks-mock-draft-5-0-baker-mayfield-slips-out-of-top-10-0ap3000000928662',
  confidence: 'high',
  note: 'Mock 5.0 final. Pick number used as rank.',
  rankings: [
    {rank: 1, player: 'Sam Darnold', pos: 'QB', school: 'USC'},
    {rank: 2, player: 'Bradley Chubb', pos: 'EDGE', school: 'NC State'},
    {rank: 3, player: 'Josh Rosen', pos: 'QB', school: 'UCLA'},
    {rank: 4, player: 'Saquon Barkley', pos: 'RB', school: 'Penn State'},
    {rank: 5, player: 'Denzel Ward', pos: 'CB', school: 'Ohio State'},
    {rank: 6, player: 'Roquan Smith', pos: 'LB', school: 'Georgia'},
    {rank: 7, player: 'Derwin James', pos: 'S', school: 'Florida State'},
    {rank: 8, player: 'Quenton Nelson', pos: 'OG', school: 'Notre Dame'},
    {rank: 9, player: 'Tremaine Edmunds', pos: 'LB', school: 'Virginia Tech'},
    {rank: 10, player: 'Vita Vea', pos: 'DT', school: 'Washington'},
    {rank: 11, player: 'Baker Mayfield', pos: 'QB', school: 'Oklahoma'},
    {rank: 12, player: 'Josh Allen', pos: 'QB', school: 'Wyoming'},
    {rank: 13, player: 'Minkah Fitzpatrick', pos: 'S', school: 'Alabama'},
    {rank: 14, player: 'Mike Hughes', pos: 'CB', school: 'UCF'},
    {rank: 15, player: 'Calvin Ridley', pos: 'WR', school: 'Alabama'},
    {rank: 16, player: 'Lamar Jackson', pos: 'QB', school: 'Louisville'},
    {rank: 17, player: "Da'Ron Payne", pos: 'DT', school: 'Alabama'},
    {rank: 18, player: 'Josh Jackson', pos: 'CB', school: 'Iowa'},
    {rank: 19, player: 'D.J. Moore', pos: 'WR', school: 'Maryland'},
    {rank: 20, player: 'Marcus Davenport', pos: 'EDGE', school: 'UTSA'},
    {rank: 21, player: 'Will Hernandez', pos: 'OG', school: 'UTEP'},
    {rank: 22, player: 'James Daniels', pos: 'C', school: 'Iowa'},
    {rank: 23, player: 'Kolton Miller', pos: 'OT', school: 'UCLA'},
    {rank: 24, player: 'Hayden Hurst', pos: 'TE', school: 'South Carolina'},
    {rank: 25, player: 'Harold Landry', pos: 'EDGE', school: 'Boston College'},
    {rank: 26, player: 'Taven Bryan', pos: 'DT', school: 'Florida'},
    {rank: 27, player: 'Dallas Goedert', pos: 'TE', school: 'South Dakota State'},
    {rank: 28, player: 'Rashaan Evans', pos: 'LB', school: 'Alabama'},
    {rank: 29, player: 'Jaire Alexander', pos: 'CB', school: 'Louisville'},
    {rank: 30, player: 'Isaiah Wynn', pos: 'OG', school: 'Georgia'},
    {rank: 31, player: 'Leighton Vander Esch', pos: 'LB', school: 'Boise State'},
    {rank: 32, player: 'Mike McGlinchey', pos: 'OT', school: 'Notre Dame'},
  ],
};

const BROOKS_2019: Board = {
  expertSlug: 'bucky',
  year: 2019,
  source: 'https://www.nfl.com/news/bucky-brooks-2019-nfl-mock-draft-4-0-packers-patriots-nab-qb-0ap3000001027870',
  confidence: 'high',
  note: 'Mock 4.0 final.',
  rankings: [
    {rank: 1, player: 'Kyler Murray', pos: 'QB', school: 'Oklahoma'},
    {rank: 2, player: 'Nick Bosa', pos: 'EDGE', school: 'Ohio State'},
    {rank: 3, player: 'Josh Allen', pos: 'EDGE', school: 'Kentucky'},
    {rank: 4, player: 'Ed Oliver', pos: 'DT', school: 'Houston'},
    {rank: 5, player: 'Quinnen Williams', pos: 'DT', school: 'Alabama'},
    {rank: 6, player: 'Jonah Williams', pos: 'OT', school: 'Alabama'},
    {rank: 7, player: 'Jawaan Taylor', pos: 'OT', school: 'Florida'},
    {rank: 8, player: 'T.J. Hockenson', pos: 'TE', school: 'Iowa'},
    {rank: 9, player: 'Noah Fant', pos: 'TE', school: 'Iowa'},
    {rank: 10, player: 'Devin White', pos: 'LB', school: 'LSU'},
    {rank: 11, player: 'Devin Bush', pos: 'LB', school: 'Michigan'},
    {rank: 12, player: 'Marquise Brown', pos: 'WR', school: 'Oklahoma'},
    {rank: 13, player: 'Cody Ford', pos: 'OG', school: 'Oklahoma'},
    {rank: 14, player: 'Andre Dillard', pos: 'OT', school: 'Washington State'},
    {rank: 15, player: 'Dwayne Haskins', pos: 'QB', school: 'Ohio State'},
    {rank: 16, player: 'Montez Sweat', pos: 'EDGE', school: 'Mississippi State'},
    {rank: 17, player: 'Clelin Ferrell', pos: 'EDGE', school: 'Clemson'},
    {rank: 18, player: 'Garrett Bradbury', pos: 'C', school: 'NC State'},
    {rank: 19, player: 'Christian Wilkins', pos: 'DT', school: 'Clemson'},
    {rank: 20, player: 'Byron Murphy', pos: 'CB', school: 'Washington'},
    {rank: 21, player: 'Rashan Gary', pos: 'DT', school: 'Michigan'},
    {rank: 22, player: 'Erik McCoy', pos: 'C', school: 'Texas A&M'},
    {rank: 23, player: 'Greedy Williams', pos: 'CB', school: 'LSU'},
    {rank: 24, player: 'Josh Jacobs', pos: 'RB', school: 'Alabama'},
    {rank: 25, player: 'Dexter Lawrence', pos: 'DT', school: 'Clemson'},
    {rank: 26, player: 'Jeffery Simmons', pos: 'DT', school: 'Mississippi State'},
    {rank: 27, player: 'Brian Burns', pos: 'EDGE', school: 'Florida State'},
    {rank: 28, player: 'Jerry Tillery', pos: 'DT', school: 'Notre Dame'},
    {rank: 29, player: 'Johnathan Abram', pos: 'S', school: 'Mississippi State'},
    {rank: 30, player: 'Drew Lock', pos: 'QB', school: 'Missouri'},
    {rank: 31, player: 'Elgton Jenkins', pos: 'OG', school: 'Mississippi State'},
    {rank: 32, player: 'Daniel Jones', pos: 'QB', school: 'Duke'},
  ],
};

const BROOKS_2020: Board = {
  expertSlug: 'bucky',
  year: 2020,
  source: 'https://www.nfl.com/news/bucky-brooks-2020-nfl-mock-draft-4-0-tua-tagovailoa-falls-to-9-0ap3000001109299',
  confidence: 'high',
  note: 'Mock 4.0 final.',
  rankings: [
    {rank: 1, player: 'Joe Burrow', pos: 'QB', school: 'LSU'},
    {rank: 2, player: 'Chase Young', pos: 'EDGE', school: 'Ohio State'},
    {rank: 3, player: 'Derrick Brown', pos: 'DT', school: 'Auburn'},
    {rank: 4, player: 'Tristan Wirfs', pos: 'OT', school: 'Iowa'},
    {rank: 5, player: 'Justin Herbert', pos: 'QB', school: 'Oregon'},
    {rank: 6, player: 'Isaiah Simmons', pos: 'LB', school: 'Clemson'},
    {rank: 7, player: 'Jeffrey Okudah', pos: 'CB', school: 'Ohio State'},
    {rank: 8, player: 'Jedrick Wills Jr.', pos: 'OT', school: 'Alabama'},
    {rank: 9, player: 'Tua Tagovailoa', pos: 'QB', school: 'Alabama'},
    {rank: 10, player: 'Mekhi Becton', pos: 'OT', school: 'Louisville'},
    {rank: 11, player: 'CeeDee Lamb', pos: 'WR', school: 'Oklahoma'},
    {rank: 12, player: 'Jerry Jeudy', pos: 'WR', school: 'Alabama'},
    {rank: 13, player: 'Javon Kinlaw', pos: 'DT', school: 'South Carolina'},
    {rank: 14, player: 'Andrew Thomas', pos: 'OT', school: 'Georgia'},
    {rank: 15, player: 'C.J. Henderson', pos: 'CB', school: 'Florida'},
    {rank: 16, player: 'A.J. Terrell', pos: 'CB', school: 'Clemson'},
    {rank: 17, player: "K'Lavon Chaisson", pos: 'EDGE', school: 'LSU'},
    {rank: 18, player: 'Austin Jackson', pos: 'OT', school: 'USC'},
    {rank: 19, player: 'Patrick Queen', pos: 'LB', school: 'LSU'},
    {rank: 20, player: 'A.J. Epenesa', pos: 'EDGE', school: 'Iowa'},
    {rank: 21, player: 'Henry Ruggs III', pos: 'WR', school: 'Alabama'},
    {rank: 22, player: 'Kristian Fulton', pos: 'CB', school: 'LSU'},
    {rank: 23, player: 'Xavier McKinney', pos: 'S', school: 'Alabama'},
    {rank: 24, player: 'Jordan Love', pos: 'QB', school: 'Utah State'},
    {rank: 25, player: 'Justin Jefferson', pos: 'WR', school: 'LSU'},
    {rank: 26, player: "D'Andre Swift", pos: 'RB', school: 'Georgia'},
    {rank: 27, player: 'Yetur Gross-Matos', pos: 'EDGE', school: 'Penn State'},
    {rank: 28, player: 'Zack Baun', pos: 'LB', school: 'Wisconsin'},
    {rank: 29, player: 'Marlon Davidson', pos: 'DT', school: 'Auburn'},
    {rank: 30, player: 'Josh Jones', pos: 'OT', school: 'Houston'},
    {rank: 31, player: 'Trevon Diggs', pos: 'CB', school: 'Alabama'},
    {rank: 32, player: 'J.K. Dobbins', pos: 'RB', school: 'Ohio State'},
  ],
};

const BROOKS_2021: Board = {
  expertSlug: 'bucky',
  year: 2021,
  source: 'https://www.nfl.com/news/bucky-brooks-2021-nfl-mock-draft-3-0-49ers-pick-trey-lance-najee-harris-to-cardi',
  confidence: 'high',
  note: 'Mock 3.0 final.',
  rankings: [
    {rank: 1, player: 'Trevor Lawrence', pos: 'QB', school: 'Clemson'},
    {rank: 2, player: 'Zach Wilson', pos: 'QB', school: 'BYU'},
    {rank: 3, player: 'Trey Lance', pos: 'QB', school: 'North Dakota State'},
    {rank: 4, player: 'Kyle Pitts', pos: 'TE', school: 'Florida'},
    {rank: 5, player: 'Penei Sewell', pos: 'OT', school: 'Oregon'},
    {rank: 6, player: "Ja'Marr Chase", pos: 'WR', school: 'LSU'},
    {rank: 7, player: 'Micah Parsons', pos: 'LB', school: 'Penn State'},
    {rank: 8, player: 'Rashawn Slater', pos: 'OT', school: 'Northwestern'},
    {rank: 9, player: 'Jaycee Horn', pos: 'CB', school: 'South Carolina'},
    {rank: 10, player: 'Patrick Surtain II', pos: 'CB', school: 'Alabama'},
    {rank: 11, player: 'Jaylen Waddle', pos: 'WR', school: 'Alabama'},
    {rank: 12, player: 'DeVonta Smith', pos: 'WR', school: 'Alabama'},
    {rank: 13, player: 'Kwity Paye', pos: 'EDGE', school: 'Michigan'},
    {rank: 14, player: 'Alijah Vera-Tucker', pos: 'OG', school: 'USC'},
    {rank: 15, player: 'Justin Fields', pos: 'QB', school: 'Ohio State'},
    {rank: 16, player: 'Najee Harris', pos: 'RB', school: 'Alabama'},
    {rank: 17, player: 'Jeremiah Owusu-Koramoah', pos: 'LB', school: 'Notre Dame'},
    {rank: 18, player: 'Zaven Collins', pos: 'LB', school: 'Tulsa'},
    {rank: 19, player: 'Mac Jones', pos: 'QB', school: 'Alabama'},
    {rank: 20, player: 'Christian Darrisaw', pos: 'OT', school: 'Virginia Tech'},
    {rank: 21, player: 'Jaelan Phillips', pos: 'EDGE', school: 'Miami'},
    {rank: 22, player: 'Trevon Moehrig', pos: 'S', school: 'TCU'},
    {rank: 23, player: 'Landon Dickerson', pos: 'C', school: 'Alabama'},
    {rank: 24, player: 'Jamin Davis', pos: 'LB', school: 'Kentucky'},
    {rank: 25, player: 'Christian Barmore', pos: 'DT', school: 'Alabama'},
    {rank: 26, player: 'Joe Tryon', pos: 'EDGE', school: 'Washington'},
    {rank: 27, player: 'Azeez Ojulari', pos: 'EDGE', school: 'Georgia'},
    {rank: 28, player: 'Levi Onwuzurike', pos: 'DT', school: 'Washington'},
    {rank: 29, player: 'Jalen Mayfield', pos: 'OT', school: 'Michigan'},
    {rank: 30, player: 'Caleb Farley', pos: 'CB', school: 'Virginia Tech'},
    {rank: 31, player: 'Teven Jenkins', pos: 'OT', school: 'Oklahoma State'},
    {rank: 32, player: 'Gregory Rousseau', pos: 'EDGE', school: 'Miami'},
  ],
};

const BROOKS_2022: Board = {
  expertSlug: 'bucky',
  year: 2022,
  source: 'https://www.nfl.com/news/bucky-brooks-2022-nfl-mock-draft-4-0-steelers-take-malik-willis-vikings-land-jam',
  confidence: 'high',
  note: 'Mock 4.0 final.',
  rankings: [
    {rank: 1, player: 'Ickey Ekwonu', pos: 'OT', school: 'NC State'},
    {rank: 2, player: 'Aidan Hutchinson', pos: 'EDGE', school: 'Michigan'},
    {rank: 3, player: 'Sauce Gardner', pos: 'CB', school: 'Cincinnati'},
    {rank: 4, player: 'Travon Walker', pos: 'EDGE', school: 'Georgia'},
    {rank: 5, player: 'Evan Neal', pos: 'OT', school: 'Alabama'},
    {rank: 6, player: 'Charles Cross', pos: 'OT', school: 'Mississippi State'},
    {rank: 7, player: 'Derek Stingley Jr.', pos: 'CB', school: 'LSU'},
    {rank: 8, player: 'Garrett Wilson', pos: 'WR', school: 'Ohio State'},
    {rank: 9, player: 'Kayvon Thibodeaux', pos: 'EDGE', school: 'Oregon'},
    {rank: 10, player: 'Drake London', pos: 'WR', school: 'USC'},
    {rank: 11, player: 'Kyle Hamilton', pos: 'S', school: 'Notre Dame'},
    {rank: 12, player: 'Jameson Williams', pos: 'WR', school: 'Alabama'},
    {rank: 13, player: 'Jermaine Johnson II', pos: 'EDGE', school: 'Florida State'},
    {rank: 14, player: 'Jordan Davis', pos: 'DT', school: 'Georgia'},
    {rank: 15, player: 'Chris Olave', pos: 'WR', school: 'Ohio State'},
    {rank: 16, player: 'Trevor Penning', pos: 'OT', school: 'Northern Iowa'},
    {rank: 17, player: 'Trent McDuffie', pos: 'CB', school: 'Washington'},
    {rank: 18, player: 'Devonte Wyatt', pos: 'DT', school: 'Georgia'},
    {rank: 19, player: 'Treylon Burks', pos: 'WR', school: 'Arkansas'},
    {rank: 20, player: 'Malik Willis', pos: 'QB', school: 'Liberty'},
    {rank: 21, player: 'Devin Lloyd', pos: 'LB', school: 'Utah'},
    {rank: 22, player: 'Bernhard Raimann', pos: 'OT', school: 'Central Michigan'},
    {rank: 23, player: 'George Karlaftis', pos: 'EDGE', school: 'Purdue'},
    {rank: 24, player: 'Zion Johnson', pos: 'OG', school: 'Boston College'},
    {rank: 25, player: 'Breece Hall', pos: 'RB', school: 'Iowa State'},
    {rank: 26, player: 'Kenyon Green', pos: 'OG', school: 'Texas A&M'},
    {rank: 27, player: 'Travis Jones', pos: 'DT', school: 'Connecticut'},
    {rank: 28, player: 'Quay Walker', pos: 'LB', school: 'Georgia'},
    {rank: 29, player: 'Daxton Hill', pos: 'S', school: 'Michigan'},
    {rank: 30, player: 'Boye Mafe', pos: 'EDGE', school: 'Minnesota'},
    {rank: 31, player: 'Logan Hall', pos: 'DT', school: 'Houston'},
    {rank: 32, player: 'Arnold Ebiketie', pos: 'EDGE', school: 'Penn State'},
  ],
};

const BROOKS_2023: Board = {
  expertSlug: 'bucky',
  year: 2023,
  source: 'https://www.nfl.com/news/bucky-brooks-2023-nfl-mock-draft-4-0-patriots-nab-bijan-robinson-ravens-select-a',
  confidence: 'high',
  note: 'Mock 4.0 final. 31 picks (Miami forfeited Round 1).',
  rankings: [
    {rank: 1, player: 'Bryce Young', pos: 'QB', school: 'Alabama'},
    {rank: 2, player: 'Tyree Wilson', pos: 'EDGE', school: 'Texas Tech'},
    {rank: 3, player: 'Will Anderson Jr.', pos: 'EDGE', school: 'Alabama'},
    {rank: 4, player: 'C.J. Stroud', pos: 'QB', school: 'Ohio State'},
    {rank: 5, player: 'Christian Gonzalez', pos: 'CB', school: 'Oregon'},
    {rank: 6, player: 'Jalen Carter', pos: 'DT', school: 'Georgia'},
    {rank: 7, player: 'Devon Witherspoon', pos: 'CB', school: 'Illinois'},
    {rank: 8, player: 'Lukas Van Ness', pos: 'EDGE', school: 'Iowa'},
    {rank: 9, player: 'Peter Skoronski', pos: 'OT', school: 'Northwestern'},
    {rank: 10, player: 'Myles Murphy', pos: 'EDGE', school: 'Clemson'},
    {rank: 11, player: 'Paris Johnson Jr.', pos: 'OT', school: 'Ohio State'},
    {rank: 12, player: 'Will Levis', pos: 'QB', school: 'Kentucky'},
    {rank: 13, player: 'Dalton Kincaid', pos: 'TE', school: 'Utah'},
    {rank: 14, player: 'Bijan Robinson', pos: 'RB', school: 'Texas'},
    {rank: 15, player: 'Broderick Jones', pos: 'OT', school: 'Georgia'},
    {rank: 16, player: 'Joey Porter Jr.', pos: 'CB', school: 'Penn State'},
    {rank: 17, player: 'Darnell Wright', pos: 'OT', school: 'Tennessee'},
    {rank: 18, player: 'Deonte Banks', pos: 'CB', school: 'Maryland'},
    {rank: 19, player: "O'Cyrus Torrence", pos: 'OG', school: 'Florida'},
    {rank: 20, player: 'Nolan Smith', pos: 'EDGE', school: 'Georgia'},
    {rank: 21, player: 'Michael Mayer', pos: 'TE', school: 'Notre Dame'},
    {rank: 22, player: 'Anthony Richardson', pos: 'QB', school: 'Florida'},
    {rank: 23, player: 'Jaxon Smith-Njigba', pos: 'WR', school: 'Ohio State'},
    {rank: 24, player: 'Brian Branch', pos: 'S', school: 'Alabama'},
    {rank: 25, player: 'Zay Flowers', pos: 'WR', school: 'Boston College'},
    {rank: 26, player: 'Steve Avila', pos: 'OG', school: 'TCU'},
    {rank: 27, player: 'Jordan Addison', pos: 'WR', school: 'USC'},
    {rank: 28, player: 'Anton Harrison', pos: 'OT', school: 'Oklahoma'},
    {rank: 29, player: 'Calijah Kancey', pos: 'DT', school: 'Pittsburgh'},
    {rank: 30, player: 'Keion White', pos: 'EDGE', school: 'Georgia Tech'},
    {rank: 31, player: 'Will McDonald IV', pos: 'EDGE', school: 'Iowa State'},
  ],
};

// ─── Peter Schrager ───────────────────────────────────────────────

const SCHRAGER_2018: Board = {
  expertSlug: 'peter-schrager',
  year: 2018,
  source: 'https://www.nfl.com/news/peter-schrager-2018-three-round-nfl-mock-draft-round-1-0ap3000000928404',
  confidence: 'high',
  note: 'Final pre-draft three-round mock; Round 1 only.',
  rankings: [
    {rank: 1, player: 'Sam Darnold', pos: 'QB', school: 'USC'},
    {rank: 2, player: 'Bradley Chubb', pos: 'EDGE', school: 'NC State'},
    {rank: 3, player: 'Baker Mayfield', pos: 'QB', school: 'Oklahoma'},
    {rank: 4, player: 'Saquon Barkley', pos: 'RB', school: 'Penn State'},
    {rank: 5, player: 'Josh Allen', pos: 'QB', school: 'Wyoming'},
    {rank: 6, player: 'Quenton Nelson', pos: 'OG', school: 'Notre Dame'},
    {rank: 7, player: 'Derwin James', pos: 'S', school: 'Florida State'},
    {rank: 8, player: 'Denzel Ward', pos: 'CB', school: 'Ohio State'},
    {rank: 9, player: 'Mike McGlinchey', pos: 'OT', school: 'Notre Dame'},
    {rank: 10, player: 'Josh Rosen', pos: 'QB', school: 'UCLA'},
    {rank: 11, player: 'Minkah Fitzpatrick', pos: 'S', school: 'Alabama'},
    {rank: 12, player: 'Roquan Smith', pos: 'LB', school: 'Georgia'},
    {rank: 13, player: 'Vita Vea', pos: 'DT', school: 'Washington'},
    {rank: 14, player: 'Tremaine Edmunds', pos: 'LB', school: 'Virginia Tech'},
    {rank: 15, player: 'Harold Landry', pos: 'EDGE', school: 'Boston College'},
    {rank: 16, player: 'Lamar Jackson', pos: 'QB', school: 'Louisville'},
    {rank: 17, player: 'Kolton Miller', pos: 'OT', school: 'UCLA'},
    {rank: 18, player: 'Marcus Davenport', pos: 'EDGE', school: 'UTSA'},
    {rank: 19, player: 'Taven Bryan', pos: 'DT', school: 'Florida'},
    {rank: 20, player: "Da'Ron Payne", pos: 'DT', school: 'Alabama'},
    {rank: 21, player: 'James Daniels', pos: 'C', school: 'Iowa'},
    {rank: 22, player: 'D.J. Moore', pos: 'WR', school: 'Maryland'},
    {rank: 23, player: 'Rashaan Evans', pos: 'LB', school: 'Alabama'},
    {rank: 24, player: 'Will Hernandez', pos: 'OG', school: 'UTEP'},
    {rank: 25, player: 'Maurice Hurst', pos: 'DT', school: 'Michigan'},
    {rank: 26, player: 'Jaire Alexander', pos: 'CB', school: 'Louisville'},
    {rank: 27, player: 'Calvin Ridley', pos: 'WR', school: 'Alabama'},
    {rank: 28, player: 'Josh Jackson', pos: 'CB', school: 'Iowa'},
    {rank: 29, player: 'Dallas Goedert', pos: 'TE', school: 'South Dakota State'},
    {rank: 30, player: 'Leighton Vander Esch', pos: 'LB', school: 'Boise State'},
    {rank: 31, player: 'Frank Ragnow', pos: 'C', school: 'Arkansas'},
    {rank: 32, player: 'Isaiah Oliver', pos: 'CB', school: 'Colorado'},
  ],
};

const SCHRAGER_2019: Board = {
  expertSlug: 'peter-schrager',
  year: 2019,
  source: 'https://www.nfl.com/news/peter-schrager-2019-nfl-mock-draft-3-0-texans-move-into-top-10-0ap3000001027789',
  confidence: 'high',
  note: 'Mock 3.0 final.',
  rankings: [
    {rank: 1, player: 'Kyler Murray', pos: 'QB', school: 'Oklahoma'},
    {rank: 2, player: 'Nick Bosa', pos: 'EDGE', school: 'Ohio State'},
    {rank: 3, player: 'Quinnen Williams', pos: 'DT', school: 'Alabama'},
    {rank: 4, player: 'Ed Oliver', pos: 'DT', school: 'Houston'},
    {rank: 5, player: 'Devin White', pos: 'LB', school: 'LSU'},
    {rank: 6, player: 'Josh Allen', pos: 'EDGE', school: 'Kentucky'},
    {rank: 7, player: 'Jawaan Taylor', pos: 'OT', school: 'Florida'},
    {rank: 8, player: 'Andre Dillard', pos: 'OT', school: 'Washington State'},
    {rank: 9, player: 'Jonah Williams', pos: 'OT', school: 'Alabama'},
    {rank: 10, player: 'Devin Bush', pos: 'LB', school: 'Michigan'},
    {rank: 11, player: 'T.J. Hockenson', pos: 'TE', school: 'Iowa'},
    {rank: 12, player: 'Marquise Brown', pos: 'WR', school: 'Oklahoma'},
    {rank: 13, player: 'Christian Wilkins', pos: 'DT', school: 'Clemson'},
    {rank: 14, player: 'Clelin Ferrell', pos: 'EDGE', school: 'Clemson'},
    {rank: 15, player: 'Dwayne Haskins', pos: 'QB', school: 'Ohio State'},
    {rank: 16, player: 'Brian Burns', pos: 'EDGE', school: 'Florida State'},
    {rank: 17, player: 'Daniel Jones', pos: 'QB', school: 'Duke'},
    {rank: 18, player: 'Garrett Bradbury', pos: 'C', school: 'NC State'},
    {rank: 19, player: 'Dexter Lawrence', pos: 'DT', school: 'Clemson'},
    {rank: 20, player: 'Rock Ya-Sin', pos: 'CB', school: 'Temple'},
    {rank: 21, player: 'Rashan Gary', pos: 'DT', school: 'Michigan'},
    {rank: 22, player: 'Cody Ford', pos: 'OG', school: 'Oklahoma'},
    {rank: 23, player: 'Byron Murphy', pos: 'CB', school: 'Washington'},
    {rank: 24, player: 'Josh Jacobs', pos: 'RB', school: 'Alabama'},
    {rank: 25, player: 'Greedy Williams', pos: 'CB', school: 'LSU'},
    {rank: 26, player: 'Jeffery Simmons', pos: 'DT', school: 'Mississippi State'},
    {rank: 27, player: 'Noah Fant', pos: 'TE', school: 'Iowa'},
    {rank: 28, player: 'Deandre Baker', pos: 'CB', school: 'Georgia'},
    {rank: 29, player: "N'Keal Harry", pos: 'WR', school: 'Arizona State'},
    {rank: 30, player: 'Elgton Jenkins', pos: 'OG', school: 'Mississippi State'},
    {rank: 31, player: 'Drew Lock', pos: 'QB', school: 'Missouri'},
    {rank: 32, player: 'Joejuan Williams', pos: 'CB', school: 'Vanderbilt'},
  ],
};

const SCHRAGER_2020: Board = {
  expertSlug: 'peter-schrager',
  year: 2020,
  source: 'https://www.nfl.com/news/peter-schrager-2020-nfl-mock-draft-3-0-tua-tagovailoa-slides-0ap3000001110606',
  confidence: 'high',
  note: 'Mock 3.0 final.',
  rankings: [
    {rank: 1, player: 'Joe Burrow', pos: 'QB', school: 'LSU'},
    {rank: 2, player: 'Chase Young', pos: 'EDGE', school: 'Ohio State'},
    {rank: 3, player: 'Justin Herbert', pos: 'QB', school: 'Oregon'},
    {rank: 4, player: 'Jedrick Wills Jr.', pos: 'OT', school: 'Alabama'},
    {rank: 5, player: 'Jeffrey Okudah', pos: 'CB', school: 'Ohio State'},
    {rank: 6, player: 'Tristan Wirfs', pos: 'OT', school: 'Iowa'},
    {rank: 7, player: 'Derrick Brown', pos: 'DT', school: 'Auburn'},
    {rank: 8, player: 'Isaiah Simmons', pos: 'LB', school: 'Clemson'},
    {rank: 9, player: 'C.J. Henderson', pos: 'CB', school: 'Florida'},
    {rank: 10, player: 'Andrew Thomas', pos: 'OT', school: 'Georgia'},
    {rank: 11, player: 'Mekhi Becton', pos: 'OT', school: 'Louisville'},
    {rank: 12, player: 'CeeDee Lamb', pos: 'WR', school: 'Oklahoma'},
    {rank: 13, player: 'Jerry Jeudy', pos: 'WR', school: 'Alabama'},
    {rank: 14, player: 'Josh Jones', pos: 'OT', school: 'Houston'},
    {rank: 15, player: 'Henry Ruggs III', pos: 'WR', school: 'Alabama'},
    {rank: 16, player: 'Tua Tagovailoa', pos: 'QB', school: 'Alabama'},
    {rank: 17, player: 'Javon Kinlaw', pos: 'DT', school: 'South Carolina'},
    {rank: 18, player: 'Xavier McKinney', pos: 'S', school: 'Alabama'},
    {rank: 19, player: 'Jaylon Johnson', pos: 'CB', school: 'Utah'},
    {rank: 20, player: 'A.J. Terrell', pos: 'CB', school: 'Clemson'},
    {rank: 21, player: "K'Lavon Chaisson", pos: 'EDGE', school: 'LSU'},
    {rank: 22, player: 'Justin Jefferson', pos: 'WR', school: 'LSU'},
    {rank: 23, player: 'Patrick Queen', pos: 'LB', school: 'LSU'},
    {rank: 24, player: 'Brandon Aiyuk', pos: 'WR', school: 'Arizona State'},
    {rank: 25, player: 'Kristian Fulton', pos: 'CB', school: 'LSU'},
    {rank: 26, player: 'Cesar Ruiz', pos: 'C', school: 'Michigan'},
    {rank: 27, player: 'Kenneth Murray', pos: 'LB', school: 'Oklahoma'},
    {rank: 28, player: "D'Andre Swift", pos: 'RB', school: 'Georgia'},
    {rank: 29, player: 'Noah Igbinoghene', pos: 'CB', school: 'Auburn'},
    {rank: 30, player: 'Darrell Taylor', pos: 'EDGE', school: 'Tennessee'},
    {rank: 31, player: 'Austin Jackson', pos: 'OT', school: 'USC'},
    {rank: 32, player: 'Trevon Diggs', pos: 'CB', school: 'Alabama'},
  ],
};

const SCHRAGER_2021: Board = {
  expertSlug: 'peter-schrager',
  year: 2021,
  source: 'https://www.nfl.com/news/peter-schrager-2021-nfl-mock-draft-3-0-eagles-patriots-trade-into-top-10',
  confidence: 'high',
  note: 'Mock 3.0 final.',
  rankings: [
    {rank: 1, player: 'Trevor Lawrence', pos: 'QB', school: 'Clemson'},
    {rank: 2, player: 'Zach Wilson', pos: 'QB', school: 'BYU'},
    {rank: 3, player: 'Mac Jones', pos: 'QB', school: 'Alabama'},
    {rank: 4, player: 'Kyle Pitts', pos: 'TE', school: 'Florida'},
    {rank: 5, player: 'Penei Sewell', pos: 'OT', school: 'Oregon'},
    {rank: 6, player: "Ja'Marr Chase", pos: 'WR', school: 'LSU'},
    {rank: 7, player: 'Patrick Surtain II', pos: 'CB', school: 'Alabama'},
    {rank: 8, player: 'Justin Fields', pos: 'QB', school: 'Ohio State'},
    {rank: 9, player: 'Trey Lance', pos: 'QB', school: 'North Dakota State'},
    {rank: 10, player: 'Jaycee Horn', pos: 'CB', school: 'South Carolina'},
    {rank: 11, player: 'Jaylen Waddle', pos: 'WR', school: 'Alabama'},
    {rank: 12, player: 'Rashawn Slater', pos: 'OT', school: 'Northwestern'},
    {rank: 13, player: 'Alijah Vera-Tucker', pos: 'OG', school: 'USC'},
    {rank: 14, player: 'Jaelan Phillips', pos: 'EDGE', school: 'Miami'},
    {rank: 15, player: 'DeVonta Smith', pos: 'WR', school: 'Alabama'},
    {rank: 16, player: 'Zaven Collins', pos: 'LB', school: 'Tulsa'},
    {rank: 17, player: 'Micah Parsons', pos: 'LB', school: 'Penn State'},
    {rank: 18, player: 'Kwity Paye', pos: 'EDGE', school: 'Michigan'},
    {rank: 19, player: 'Christian Darrisaw', pos: 'OT', school: 'Virginia Tech'},
    {rank: 20, player: 'Teven Jenkins', pos: 'OT', school: 'Oklahoma State'},
    {rank: 21, player: 'Azeez Ojulari', pos: 'EDGE', school: 'Georgia'},
    {rank: 22, player: 'Najee Harris', pos: 'RB', school: 'Alabama'},
    {rank: 23, player: 'Travis Etienne', pos: 'RB', school: 'Clemson'},
    {rank: 24, player: 'Greg Newsome II', pos: 'CB', school: 'Northwestern'},
    {rank: 25, player: 'Jayson Oweh', pos: 'EDGE', school: 'Penn State'},
    {rank: 26, player: 'Tyson Campbell', pos: 'CB', school: 'Georgia'},
    {rank: 27, player: 'Trevon Moehrig', pos: 'S', school: 'TCU'},
    {rank: 28, player: 'Kadarius Toney', pos: 'WR', school: 'Florida'},
    {rank: 29, player: 'Elijah Moore', pos: 'WR', school: 'Mississippi'},
    {rank: 30, player: 'Levi Onwuzurike', pos: 'DT', school: 'Washington'},
    {rank: 31, player: 'Gregory Rousseau', pos: 'EDGE', school: 'Miami'},
    {rank: 32, player: 'Jamin Davis', pos: 'LB', school: 'Kentucky'},
  ],
};

const SCHRAGER_2022: Board = {
  expertSlug: 'peter-schrager',
  year: 2022,
  source: 'https://www.nfl.com/news/peter-schrager-2022-nfl-mock-draft-3-0-eagles-packers-trade-up-for-wide-receiver',
  confidence: 'high',
  note: 'Mock 3.0 final.',
  rankings: [
    {rank: 1, player: 'Travon Walker', pos: 'EDGE', school: 'Georgia'},
    {rank: 2, player: 'Aidan Hutchinson', pos: 'EDGE', school: 'Michigan'},
    {rank: 3, player: 'Ickey Ekwonu', pos: 'OT', school: 'NC State'},
    {rank: 4, player: 'Sauce Gardner', pos: 'CB', school: 'Cincinnati'},
    {rank: 5, player: 'Charles Cross', pos: 'OT', school: 'Mississippi State'},
    {rank: 6, player: 'Evan Neal', pos: 'OT', school: 'Alabama'},
    {rank: 7, player: 'Derek Stingley Jr.', pos: 'CB', school: 'LSU'},
    {rank: 8, player: 'Kayvon Thibodeaux', pos: 'EDGE', school: 'Oregon'},
    {rank: 9, player: 'Jermaine Johnson II', pos: 'EDGE', school: 'Florida State'},
    {rank: 10, player: 'Garrett Wilson', pos: 'WR', school: 'Ohio State'},
    {rank: 11, player: 'Drake London', pos: 'WR', school: 'USC'},
    {rank: 12, player: 'Kyle Hamilton', pos: 'S', school: 'Notre Dame'},
    {rank: 13, player: 'Jameson Williams', pos: 'WR', school: 'Alabama'},
    {rank: 14, player: 'Chris Olave', pos: 'WR', school: 'Ohio State'},
    {rank: 15, player: 'Jordan Davis', pos: 'DT', school: 'Georgia'},
    {rank: 16, player: 'Trevor Penning', pos: 'OT', school: 'Northern Iowa'},
    {rank: 17, player: 'Kenyon Green', pos: 'OG', school: 'Texas A&M'},
    {rank: 18, player: 'Trent McDuffie', pos: 'CB', school: 'Washington'},
    {rank: 19, player: 'Jahan Dotson', pos: 'WR', school: 'Penn State'},
    {rank: 20, player: 'Malik Willis', pos: 'QB', school: 'Liberty'},
    {rank: 21, player: 'Quay Walker', pos: 'LB', school: 'Georgia'},
    {rank: 22, player: 'Daxton Hill', pos: 'S', school: 'Michigan'},
    {rank: 23, player: 'Zion Johnson', pos: 'OG', school: 'Boston College'},
    {rank: 24, player: 'Tyler Linderbaum', pos: 'C', school: 'Iowa'},
    {rank: 25, player: 'Breece Hall', pos: 'RB', school: 'Iowa State'},
    {rank: 26, player: 'Tyler Smith', pos: 'OT', school: 'Tulsa'},
    {rank: 27, player: 'Lewis Cine', pos: 'S', school: 'Georgia'},
    {rank: 28, player: 'Devin Lloyd', pos: 'LB', school: 'Utah'},
    {rank: 29, player: 'Kaiir Elam', pos: 'CB', school: 'Florida'},
    {rank: 30, player: 'Treylon Burks', pos: 'WR', school: 'Arkansas'},
    {rank: 31, player: 'Trey McBride', pos: 'TE', school: 'Colorado State'},
    {rank: 32, player: 'Kenny Pickett', pos: 'QB', school: 'Pittsburgh'},
  ],
};

const SCHRAGER_2023: Board = {
  expertSlug: 'peter-schrager',
  year: 2023,
  source: 'https://www.nfl.com/news/peter-schrager-2023-nfl-mock-draft-2-0-titans-trade-up-for-c-j-stroud-vikings-gi',
  confidence: 'high',
  note: 'Mock 2.0 final. 31 picks (Miami forfeited).',
  rankings: [
    {rank: 1, player: 'Bryce Young', pos: 'QB', school: 'Alabama'},
    {rank: 2, player: 'Will Anderson Jr.', pos: 'EDGE', school: 'Alabama'},
    {rank: 3, player: 'C.J. Stroud', pos: 'QB', school: 'Ohio State'},
    {rank: 4, player: 'Will Levis', pos: 'QB', school: 'Kentucky'},
    {rank: 5, player: 'Jalen Carter', pos: 'DT', school: 'Georgia'},
    {rank: 6, player: 'Devon Witherspoon', pos: 'CB', school: 'Illinois'},
    {rank: 7, player: 'Tyree Wilson', pos: 'EDGE', school: 'Texas Tech'},
    {rank: 8, player: 'Christian Gonzalez', pos: 'CB', school: 'Oregon'},
    {rank: 9, player: 'Paris Johnson Jr.', pos: 'OT', school: 'Ohio State'},
    {rank: 10, player: 'Peter Skoronski', pos: 'OT', school: 'Northwestern'},
    {rank: 11, player: 'Broderick Jones', pos: 'OT', school: 'Georgia'},
    {rank: 12, player: 'Anthony Richardson', pos: 'QB', school: 'Florida'},
    {rank: 13, player: 'Jaxon Smith-Njigba', pos: 'WR', school: 'Ohio State'},
    {rank: 14, player: 'Zay Flowers', pos: 'WR', school: 'Boston College'},
    {rank: 15, player: 'Lukas Van Ness', pos: 'EDGE', school: 'Iowa'},
    {rank: 16, player: 'Dalton Kincaid', pos: 'TE', school: 'Utah'},
    {rank: 17, player: 'Darnell Wright', pos: 'OT', school: 'Tennessee'},
    {rank: 18, player: 'Myles Murphy', pos: 'EDGE', school: 'Clemson'},
    {rank: 19, player: 'Nolan Smith', pos: 'EDGE', school: 'Georgia'},
    {rank: 20, player: 'Jordan Addison', pos: 'WR', school: 'USC'},
    {rank: 21, player: 'Michael Mayer', pos: 'TE', school: 'Notre Dame'},
    {rank: 22, player: 'Emmanuel Forbes', pos: 'CB', school: 'Mississippi State'},
    {rank: 23, player: 'Bijan Robinson', pos: 'RB', school: 'Texas'},
    {rank: 24, player: 'Deonte Banks', pos: 'CB', school: 'Maryland'},
    {rank: 25, player: 'Jahmyr Gibbs', pos: 'RB', school: 'Alabama'},
    {rank: 26, player: 'Will McDonald IV', pos: 'EDGE', school: 'Iowa State'},
    {rank: 27, player: 'Bryan Bresee', pos: 'DT', school: 'Clemson'},
    {rank: 28, player: 'Hendon Hooker', pos: 'QB', school: 'Tennessee'},
    {rank: 29, player: 'Sam LaPorta', pos: 'TE', school: 'Iowa'},
    {rank: 30, player: 'Joey Porter Jr.', pos: 'CB', school: 'Penn State'},
    {rank: 31, player: 'Jalin Hyatt', pos: 'WR', school: 'Tennessee'},
  ],
};

export const BOARDS_PART3: Board[] = [
  BROOKS_2018,
  BROOKS_2019,
  BROOKS_2020,
  BROOKS_2021,
  BROOKS_2022,
  BROOKS_2023,
  SCHRAGER_2018,
  SCHRAGER_2019,
  SCHRAGER_2020,
  SCHRAGER_2021,
  SCHRAGER_2022,
  SCHRAGER_2023,
];
