/**
 * Part 2 of historical big board data — Brugler 2018, PFF, Trapasso, Norris.
 * Split from part 1 only for file-size readability.
 */

import type {Board} from './expert-rankings-data.js';

// ─────────────────────────────────────────────────────────────────
// Dane Brugler — 2018 only (2019-2022 paywalled at The Athletic)
// ─────────────────────────────────────────────────────────────────

const BRUGLER_2018: Board = {
  expertSlug: 'brugler',
  year: 2018,
  source: 'https://web.archive.org/web/20180710235430/http://www.profootballhof.com/brugler-big-board-30/',
  confidence: 'high',
  note: 'Big Board 3.0 final pre-draft Top 100. Originally on NFLDraftScout.com 2018-04-03; republished by Pro Football Hall of Fame 2018-04-10.',
  rankings: [
    {rank: 1, player: 'Quenton Nelson', pos: 'OG', school: 'Notre Dame'},
    {rank: 2, player: 'Minkah Fitzpatrick', pos: 'CB/S', school: 'Alabama'},
    {rank: 3, player: 'Bradley Chubb', pos: 'DE', school: 'NC State'},
    {rank: 4, player: 'Saquon Barkley', pos: 'RB', school: 'Penn State'},
    {rank: 5, player: 'Denzel Ward', pos: 'CB', school: 'Ohio State'},
    {rank: 6, player: 'Sam Darnold', pos: 'QB', school: 'USC'},
    {rank: 7, player: 'Roquan Smith', pos: 'LB', school: 'Georgia'},
    {rank: 8, player: 'Derwin James', pos: 'S', school: 'Florida State'},
    {rank: 9, player: 'Josh Rosen', pos: 'QB', school: 'UCLA'},
    {rank: 10, player: 'Baker Mayfield', pos: 'QB', school: 'Oklahoma'},
    {rank: 11, player: 'Calvin Ridley', pos: 'WR', school: 'Alabama'},
    {rank: 12, player: 'Marcus Davenport', pos: 'DE', school: 'UTSA'},
    {rank: 13, player: 'Harold Landry', pos: 'DE', school: 'Boston College'},
    {rank: 14, player: 'D.J. Moore', pos: 'WR', school: 'Maryland'},
    {rank: 15, player: 'Tremaine Edmunds', pos: 'LB', school: 'Virginia Tech'},
    {rank: 16, player: 'Jaire Alexander', pos: 'CB', school: 'Louisville'},
    {rank: 17, player: 'James Daniels', pos: 'C', school: 'Iowa'},
    {rank: 18, player: 'Maurice Hurst', pos: 'DT', school: 'Michigan'},
    {rank: 19, player: 'Isaiah Wynn', pos: 'OG', school: 'Georgia'},
    {rank: 20, player: 'Will Hernandez', pos: 'OG', school: 'UTEP'},
    {rank: 21, player: 'Derrius Guice', pos: 'RB', school: 'LSU'},
    {rank: 22, player: 'Ronald Jones', pos: 'RB', school: 'USC'},
    {rank: 23, player: 'Mike Hughes', pos: 'CB', school: 'UCF'},
    {rank: 24, player: 'Billy Price', pos: 'C', school: 'Ohio State'},
    {rank: 25, player: 'Rashaan Evans', pos: 'LB', school: 'Alabama'},
    {rank: 26, player: 'Leighton Vander Esch', pos: 'LB', school: 'Boise State'},
    {rank: 27, player: 'Vita Vea', pos: 'DT', school: 'Washington'},
    {rank: 28, player: 'Mike McGlinchey', pos: 'OT', school: 'Notre Dame'},
    {rank: 29, player: 'Taven Bryan', pos: 'DT', school: 'Florida'},
    {rank: 30, player: 'Josh Allen', pos: 'QB', school: 'Wyoming'},
    {rank: 31, player: 'Josh Jackson', pos: 'CB', school: 'Iowa'},
    {rank: 32, player: 'Lamar Jackson', pos: 'QB', school: 'Louisville'},
    {rank: 33, player: "Da'Ron Payne", pos: 'DT', school: 'Alabama'},
    {rank: 34, player: 'Dallas Goedert', pos: 'TE', school: 'South Dakota State'},
    {rank: 35, player: 'Isaiah Oliver', pos: 'CB', school: 'Colorado'},
    {rank: 36, player: 'Anthony Miller', pos: 'WR', school: 'Memphis'},
    {rank: 37, player: 'Courtland Sutton', pos: 'WR', school: 'SMU'},
    {rank: 38, player: 'Connor Williams', pos: 'OT', school: 'Texas'},
    {rank: 39, player: 'Hayden Hurst', pos: 'TE', school: 'South Carolina'},
    {rank: 40, player: 'Kerryon Johnson', pos: 'RB', school: 'Auburn'},
    {rank: 41, player: 'Ronnie Harrison', pos: 'S', school: 'Alabama'},
    {rank: 42, player: 'Harrison Phillips', pos: 'DT', school: 'Stanford'},
    {rank: 43, player: 'Carlton Davis', pos: 'CB', school: 'Auburn'},
    {rank: 44, player: 'Sam Hubbard', pos: 'DE', school: 'Ohio State'},
    {rank: 45, player: 'Equanimeous St. Brown', pos: 'WR', school: 'Notre Dame'},
    {rank: 46, player: 'Tyrell Crosby', pos: 'OT', school: 'Oregon'},
    {rank: 47, player: 'Sony Michel', pos: 'RB', school: 'Georgia'},
    {rank: 48, player: 'Christian Kirk', pos: 'WR', school: 'Texas A&M'},
    {rank: 49, player: 'Nick Chubb', pos: 'RB', school: 'Georgia'},
    {rank: 50, player: 'Nathan Shepherd', pos: 'DT', school: 'Fort Hays State'},
    {rank: 51, player: 'Mike Gesicki', pos: 'TE', school: 'Penn State'},
    {rank: 52, player: 'Ogbonnia Okoronkwo', pos: 'DE', school: 'Oklahoma'},
    {rank: 53, player: 'Kemoko Turay', pos: 'DE', school: 'Rutgers'},
    {rank: 54, player: "Brian O'Neill", pos: 'OT', school: 'Pittsburgh'},
    {rank: 55, player: 'Rashaan Gaulden', pos: 'S', school: 'Tennessee'},
    {rank: 56, player: 'Fred Warner', pos: 'LB', school: 'BYU'},
    {rank: 57, player: 'Jessie Bates', pos: 'S', school: 'Wake Forest'},
    {rank: 58, player: 'Rashaad Penny', pos: 'RB', school: 'San Diego State'},
    {rank: 59, player: 'Michael Gallup', pos: 'WR', school: 'Colorado State'},
    {rank: 60, player: 'Deadrin Senat', pos: 'DT', school: 'South Florida'},
    {rank: 61, player: 'Josey Jewell', pos: 'LB', school: 'Iowa'},
    {rank: 62, player: 'Orlando Brown', pos: 'OT', school: 'Oklahoma'},
    {rank: 63, player: 'Justin Reid', pos: 'S', school: 'Stanford'},
    {rank: 64, player: 'DJ Chark', pos: 'WR', school: 'LSU'},
    {rank: 65, player: 'James Washington', pos: 'WR', school: 'Oklahoma State'},
    {rank: 66, player: 'Josh Sweat', pos: 'DE/OLB', school: 'Florida State'},
    {rank: 67, player: 'Ian Thomas', pos: 'TE', school: 'Indiana'},
    {rank: 68, player: 'Arden Key', pos: 'DE/OLB', school: 'LSU'},
    {rank: 69, player: 'Martinas Rankin', pos: 'OT', school: 'Mississippi State'},
    {rank: 70, player: 'Braden Smith', pos: 'OG', school: 'Auburn'},
    {rank: 71, player: 'Rasheem Green', pos: 'DL', school: 'USC'},
    {rank: 72, player: 'B.J. Hill', pos: 'DT', school: 'NC State'},
    {rank: 73, player: "Da'Shawn Hand", pos: 'DT', school: 'Alabama'},
    {rank: 74, player: 'Austin Corbett', pos: 'OG', school: 'Nevada'},
    {rank: 75, player: 'Donte Jackson', pos: 'CB', school: 'LSU'},
    {rank: 76, player: 'Dante Pettis', pos: 'WR', school: 'Washington'},
    {rank: 77, player: 'Anthony Averett', pos: 'CB', school: 'Alabama'},
    {rank: 78, player: 'Duke Ejiofor', pos: 'DE', school: 'Wake Forest'},
    {rank: 79, player: 'Nyheim Hines', pos: 'RB', school: 'NC State'},
    {rank: 80, player: "Tre'Quan Smith", pos: 'WR', school: 'UCF'},
    {rank: 81, player: 'Malik Jefferson', pos: 'LB', school: 'Texas'},
    {rank: 82, player: 'Duke Dawson', pos: 'CB', school: 'Florida'},
    {rank: 83, player: 'M.J. Stewart', pos: 'CB', school: 'North Carolina'},
    {rank: 84, player: 'Mark Andrews', pos: 'TE', school: 'Oklahoma'},
    {rank: 85, player: 'DaeSean Hamilton', pos: 'WR', school: 'Penn State'},
    {rank: 86, player: 'Lorenzo Carter', pos: 'LB', school: 'Georgia'},
    {rank: 87, player: 'Jordan Whitehead', pos: 'S', school: 'Pittsburgh'},
    {rank: 88, player: 'Jamarco Jones', pos: 'OT', school: 'Ohio State'},
    {rank: 89, player: 'Uchenna Nwosu', pos: 'DE/OLB', school: 'USC'},
    {rank: 90, player: 'Terrell Edmunds', pos: 'S', school: 'Virginia Tech'},
    {rank: 91, player: 'Isaac Yiadom', pos: 'CB', school: 'Boston College'},
    {rank: 92, player: 'Derrick Nnadi', pos: 'DT', school: 'Florida State'},
    {rank: 93, player: 'Deon Cain', pos: 'WR', school: 'Clemson'},
    {rank: 94, player: 'Kolton Miller', pos: 'OT', school: 'UCLA'},
    {rank: 95, player: 'Frank Ragnow', pos: 'C', school: 'Arkansas'},
    {rank: 96, player: 'Dorance Armstrong', pos: 'DE/OLB', school: 'Kansas'},
    {rank: 97, player: 'Marcus Allen', pos: 'S', school: 'Penn State'},
    {rank: 98, player: 'Folorunso Fatukasi', pos: 'DT', school: 'Connecticut'},
    {rank: 99, player: 'Tracy Walker', pos: 'S', school: 'Louisiana'},
    {rank: 100, player: 'Darius Leonard', pos: 'LB', school: 'South Carolina State'},
  ],
};

// ─────────────────────────────────────────────────────────────────
// PFF Big Board (annual PFF draft team)
// ─────────────────────────────────────────────────────────────────

const PFF_2018: Board = {
  expertSlug: 'pff',
  year: 2018,
  source: 'https://www.pff.com/news/draft-pff-big-board-top-250-players-for-the-2018-nfl-draft',
  confidence: 'low',
  note: 'Article preview only exposed top 25 publicly. Ranks 26+ paywalled.',
  rankings: [
    {rank: 1, player: 'Baker Mayfield', pos: 'QB', school: 'Oklahoma'},
    {rank: 2, player: 'Sam Darnold', pos: 'QB', school: 'USC'},
    {rank: 3, player: 'Maurice Hurst', pos: 'DT', school: 'Michigan'},
    {rank: 4, player: 'Quenton Nelson', pos: 'OG', school: 'Notre Dame'},
    {rank: 5, player: 'Derwin James', pos: 'S', school: 'Florida State'},
    {rank: 6, player: 'Josh Rosen', pos: 'QB', school: 'UCLA'},
    {rank: 7, player: 'Roquan Smith', pos: 'LB', school: 'Georgia'},
    {rank: 8, player: 'Josh Jackson', pos: 'CB', school: 'Iowa'},
    {rank: 9, player: 'Denzel Ward', pos: 'CB', school: 'Ohio State'},
    {rank: 10, player: 'Minkah Fitzpatrick', pos: 'CB', school: 'Alabama'},
    {rank: 11, player: 'Saquon Barkley', pos: 'RB', school: 'Penn State'},
    {rank: 12, player: 'Harold Landry', pos: 'EDGE', school: 'Boston College'},
    {rank: 13, player: 'Bradley Chubb', pos: 'EDGE', school: 'NC State'},
    {rank: 14, player: 'Frank Ragnow', pos: 'C', school: 'Arkansas'},
    {rank: 15, player: 'Mike McGlinchey', pos: 'OT', school: 'Notre Dame'},
    {rank: 16, player: 'Isaiah Wynn', pos: 'OG', school: 'Georgia'},
    {rank: 17, player: 'Will Hernandez', pos: 'OG', school: 'UTEP'},
    {rank: 18, player: 'Connor Williams', pos: 'OT', school: 'Texas'},
    {rank: 19, player: 'Lamar Jackson', pos: 'QB', school: 'Louisville'},
    {rank: 20, player: 'Vita Vea', pos: 'DT', school: 'Washington'},
    {rank: 21, player: 'Dallas Goedert', pos: 'TE', school: 'South Dakota State'},
    {rank: 22, player: 'Jaire Alexander', pos: 'CB', school: 'Louisville'},
    {rank: 23, player: 'Calvin Ridley', pos: 'WR', school: 'Alabama'},
    {rank: 24, player: 'James Washington', pos: 'WR', school: 'Oklahoma State'},
    {rank: 25, player: 'Mason Rudolph', pos: 'QB', school: 'Oklahoma State'},
  ],
};

const PFF_2019: Board = {
  expertSlug: 'pff',
  year: 2019,
  source: 'https://www.pff.com/news/draft-pffs-top-250-big-board-for-the-2019-nfl-draft',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Kyler Murray', pos: 'QB', school: 'Oklahoma'},
    {rank: 2, player: 'Nick Bosa', pos: 'EDGE', school: 'Ohio State'},
    {rank: 3, player: 'Quinnen Williams', pos: 'DT', school: 'Alabama'},
    {rank: 4, player: 'Jonah Williams', pos: 'OT', school: 'Alabama'},
    {rank: 5, player: 'Josh Allen', pos: 'EDGE', school: 'Kentucky'},
    {rank: 6, player: 'Byron Murphy', pos: 'CB', school: 'Washington'},
    {rank: 7, player: 'Jerry Tillery', pos: 'DT', school: 'Notre Dame'},
    {rank: 8, player: 'Jeffery Simmons', pos: 'DT', school: 'Mississippi State'},
    {rank: 9, player: 'Greedy Williams', pos: 'CB', school: 'LSU'},
    {rank: 10, player: 'Dwayne Haskins', pos: 'QB', school: 'Ohio State'},
    {rank: 11, player: 'Ed Oliver', pos: 'DT', school: 'Houston'},
    {rank: 12, player: 'Devin White', pos: 'LB', school: 'LSU'},
    {rank: 13, player: 'Andre Dillard', pos: 'OT', school: 'Washington State'},
    {rank: 14, player: 'Brian Burns', pos: 'EDGE', school: 'Florida State'},
    {rank: 15, player: 'Jawaan Taylor', pos: 'OT', school: 'Florida'},
    {rank: 16, player: 'DeAndre Baker', pos: 'CB', school: 'Georgia'},
    {rank: 17, player: 'D.K. Metcalf', pos: 'WR', school: 'Mississippi'},
    {rank: 18, player: 'Devin Bush', pos: 'LB', school: 'Michigan'},
    {rank: 19, player: 'Dalton Risner', pos: 'OT', school: 'Kansas State'},
    {rank: 20, player: 'A.J. Brown', pos: 'WR', school: 'Mississippi'},
    {rank: 21, player: 'T.J. Hockenson', pos: 'TE', school: 'Iowa'},
    {rank: 22, player: 'Cody Ford', pos: 'OT', school: 'Oklahoma'},
    {rank: 23, player: 'J.J. Arcega-Whiteside', pos: 'WR', school: 'Stanford'},
    {rank: 24, player: 'Will Grier', pos: 'QB', school: 'West Virginia'},
    {rank: 25, player: 'Christian Wilkins', pos: 'DT', school: 'Clemson'},
    {rank: 26, player: 'Elgton Jenkins', pos: 'C', school: 'Mississippi State'},
    {rank: 27, player: 'Nasir Adderley', pos: 'S', school: 'Delaware'},
    {rank: 28, player: 'Darnell Savage', pos: 'S', school: 'Maryland'},
    {rank: 29, player: 'Chase Winovich', pos: 'EDGE', school: 'Michigan'},
    {rank: 30, player: 'Andy Isabella', pos: 'WR', school: 'Massachusetts'},
    {rank: 31, player: 'Marquise Brown', pos: 'WR', school: 'Oklahoma'},
    {rank: 32, player: 'Dexter Lawrence', pos: 'DT', school: 'Clemson'},
    {rank: 33, player: 'David Long', pos: 'CB', school: 'Michigan'},
    {rank: 34, player: 'Greg Little', pos: 'OT', school: 'Mississippi'},
    {rank: 35, player: 'Clelin Ferrell', pos: 'EDGE', school: 'Clemson'},
    {rank: 36, player: 'Amani Oruwariye', pos: 'CB', school: 'Penn State'},
    {rank: 37, player: 'Drew Lock', pos: 'QB', school: 'Missouri'},
    {rank: 38, player: 'Taylor Rapp', pos: 'S', school: 'Washington'},
    {rank: 39, player: 'Justin Layne', pos: 'CB', school: 'Michigan State'},
    {rank: 40, player: 'Zach Allen', pos: 'EDGE', school: 'Boston College'},
    {rank: 41, player: 'Garrett Bradbury', pos: 'C', school: 'NC State'},
    {rank: 42, player: 'Hakeem Butler', pos: 'WR', school: 'Iowa State'},
    {rank: 43, player: 'Noah Fant', pos: 'TE', school: 'Iowa'},
    {rank: 44, player: 'Amani Hooker', pos: 'S', school: 'Iowa'},
    {rank: 45, player: 'Julian Love', pos: 'CB', school: 'Notre Dame'},
    {rank: 46, player: 'Montez Sweat', pos: 'EDGE', school: 'Mississippi State'},
    {rank: 47, player: 'Khalen Saunders', pos: 'DT', school: 'Western Illinois'},
    {rank: 48, player: 'Rashan Gary', pos: 'EDGE', school: 'Michigan'},
    {rank: 49, player: 'Chauncey Gardner-Johnson', pos: 'S', school: 'Florida'},
    {rank: 50, player: 'Max Scharping', pos: 'OT', school: 'Northern Illinois'},
  ],
};

const PFF_2021: Board = {
  expertSlug: 'pff',
  year: 2021,
  source: 'https://www.pff.com/news/draft-final-2021-nfl-draft-board-big-board-draft-rankings',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Trevor Lawrence', pos: 'QB', school: 'Clemson'},
    {rank: 2, player: 'Zach Wilson', pos: 'QB', school: 'BYU'},
    {rank: 3, player: 'Justin Fields', pos: 'QB', school: 'Ohio State'},
    {rank: 4, player: 'Penei Sewell', pos: 'OT', school: 'Oregon'},
    {rank: 5, player: 'Kyle Pitts', pos: 'TE', school: 'Florida'},
    {rank: 6, player: "Ja'Marr Chase", pos: 'WR', school: 'LSU'},
    {rank: 7, player: 'DeVonta Smith', pos: 'WR', school: 'Alabama'},
    {rank: 8, player: 'Jaylen Waddle', pos: 'WR', school: 'Alabama'},
    {rank: 9, player: 'Micah Parsons', pos: 'LB', school: 'Penn State'},
    {rank: 10, player: 'Trey Lance', pos: 'QB', school: 'North Dakota State'},
    {rank: 11, player: 'Rashawn Slater', pos: 'OT', school: 'Northwestern'},
    {rank: 12, player: 'Christian Barmore', pos: 'DT', school: 'Alabama'},
    {rank: 13, player: 'Patrick Surtain', pos: 'CB', school: 'Alabama'},
    {rank: 14, player: 'Mac Jones', pos: 'QB', school: 'Alabama'},
    {rank: 15, player: 'Christian Darrisaw', pos: 'OT', school: 'Virginia Tech'},
    {rank: 16, player: 'Trevon Moehrig', pos: 'S', school: 'TCU'},
    {rank: 17, player: 'Rashod Bateman', pos: 'WR', school: 'Minnesota'},
    {rank: 18, player: 'Jaycee Horn', pos: 'CB', school: 'South Carolina'},
    {rank: 19, player: 'Jeremiah Owusu-Koramoah', pos: 'LB', school: 'Notre Dame'},
    {rank: 20, player: 'Greg Newsome', pos: 'CB', school: 'Northwestern'},
    {rank: 21, player: 'Alijah Vera-Tucker', pos: 'OG', school: 'USC'},
    {rank: 22, player: 'Elijah Moore', pos: 'WR', school: 'Mississippi'},
    {rank: 23, player: 'Caleb Farley', pos: 'CB', school: 'Virginia Tech'},
    {rank: 24, player: 'Kwity Paye', pos: 'EDGE', school: 'Michigan'},
    {rank: 25, player: 'Jayson Oweh', pos: 'EDGE', school: 'Penn State'},
    {rank: 26, player: 'Walker Little', pos: 'OT', school: 'Stanford'},
    {rank: 27, player: 'Jaelan Phillips', pos: 'EDGE', school: 'Miami'},
    {rank: 28, player: 'Terrace Marshall', pos: 'WR', school: 'LSU'},
    {rank: 29, player: 'Asante Samuel Jr.', pos: 'CB', school: 'Florida State'},
    {rank: 30, player: 'Azeez Ojulari', pos: 'EDGE', school: 'Georgia'},
    {rank: 31, player: 'Teven Jenkins', pos: 'OT', school: 'Oklahoma State'},
    {rank: 32, player: 'Dillon Radunz', pos: 'OT', school: 'North Dakota State'},
    {rank: 33, player: 'Rondale Moore', pos: 'WR', school: 'Purdue'},
    {rank: 34, player: 'Nick Bolton', pos: 'LB', school: 'Missouri'},
    {rank: 35, player: 'Elijah Molden', pos: 'S', school: 'Washington'},
    {rank: 36, player: 'Zaven Collins', pos: 'LB', school: 'Tulsa'},
    {rank: 37, player: 'Gregory Rousseau', pos: 'EDGE', school: 'Miami'},
    {rank: 38, player: 'Samuel Cosmi', pos: 'OT', school: 'Texas'},
    {rank: 39, player: 'Kadarius Toney', pos: 'WR', school: 'Florida'},
    {rank: 40, player: 'Alex Leatherwood', pos: 'OT', school: 'Alabama'},
    {rank: 41, player: 'Jamin Davis', pos: 'LB', school: 'Kentucky'},
    {rank: 42, player: 'Carlos Basham Jr.', pos: 'EDGE', school: 'Wake Forest'},
    {rank: 43, player: 'Ronnie Perkins', pos: 'EDGE', school: 'Oklahoma'},
    {rank: 44, player: 'Landon Dickerson', pos: 'C', school: 'Alabama'},
    {rank: 45, player: 'Dyami Brown', pos: 'WR', school: 'North Carolina'},
    {rank: 46, player: 'Jabril Cox', pos: 'LB', school: 'LSU'},
    {rank: 47, player: 'Jamar Johnson', pos: 'S', school: 'Indiana'},
    {rank: 48, player: 'Jackson Carman', pos: 'OT', school: 'Clemson'},
    {rank: 49, player: 'Richie Grant', pos: 'S', school: 'UCF'},
    {rank: 50, player: 'Jevon Holland', pos: 'S', school: 'Oregon'},
  ],
};

const PFF_2022: Board = {
  expertSlug: 'pff',
  year: 2022,
  source: 'https://www.pff.com/news/draft-final-2022-nfl-draft-top-100-big-board-sikkema',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Derek Stingley Jr.', pos: 'CB', school: 'LSU'},
    {rank: 2, player: 'Kayvon Thibodeaux', pos: 'EDGE', school: 'Oregon'},
    {rank: 3, player: 'Charles Cross', pos: 'OT', school: 'Mississippi State'},
    {rank: 4, player: 'Kyle Hamilton', pos: 'S', school: 'Notre Dame'},
    {rank: 5, player: 'Evan Neal', pos: 'OT', school: 'Alabama'},
    {rank: 6, player: 'Ikem Ekwonu', pos: 'OT', school: 'NC State'},
    {rank: 7, player: 'Aidan Hutchinson', pos: 'EDGE', school: 'Michigan'},
    {rank: 8, player: 'Jameson Williams', pos: 'WR', school: 'Alabama'},
    {rank: 9, player: 'Ahmad Gardner', pos: 'CB', school: 'Cincinnati'},
    {rank: 10, player: 'Devonte Wyatt', pos: 'DT', school: 'Georgia'},
    {rank: 11, player: 'Jordan Davis', pos: 'DT', school: 'Georgia'},
    {rank: 12, player: 'George Karlaftis', pos: 'EDGE', school: 'Purdue'},
    {rank: 13, player: 'Drake London', pos: 'WR', school: 'USC'},
    {rank: 14, player: 'Jermaine Johnson II', pos: 'EDGE', school: 'Florida State'},
    {rank: 15, player: 'Travon Walker', pos: 'EDGE', school: 'Georgia'},
    {rank: 16, player: 'George Pickens', pos: 'WR', school: 'Georgia'},
    {rank: 17, player: 'Daxton Hill', pos: 'S', school: 'Michigan'},
    {rank: 18, player: 'Trent McDuffie', pos: 'CB', school: 'Washington'},
    {rank: 19, player: 'Chris Olave', pos: 'WR', school: 'Ohio State'},
    {rank: 20, player: 'Tyler Linderbaum', pos: 'C', school: 'Iowa'},
    {rank: 21, player: 'Garrett Wilson', pos: 'WR', school: 'Ohio State'},
    {rank: 22, player: 'Devin Lloyd', pos: 'LB', school: 'Utah'},
    {rank: 23, player: 'Zion Johnson', pos: 'OG', school: 'Boston College'},
    {rank: 24, player: 'Nakobe Dean', pos: 'LB', school: 'Georgia'},
    {rank: 25, player: 'Lewis Cine', pos: 'S', school: 'Georgia'},
    {rank: 26, player: 'Roger McCreary', pos: 'CB', school: 'Auburn'},
    {rank: 27, player: 'David Ojabo', pos: 'EDGE', school: 'Michigan'},
    {rank: 28, player: 'Andrew Booth', pos: 'CB', school: 'Clemson'},
    {rank: 29, player: 'Drake Jackson', pos: 'EDGE', school: 'USC'},
    {rank: 30, player: 'Arnold Ebiketie', pos: 'EDGE', school: 'Penn State'},
    {rank: 31, player: 'Treylon Burks', pos: 'WR', school: 'Arkansas'},
    {rank: 32, player: 'Skyy Moore', pos: 'WR', school: 'Western Michigan'},
    {rank: 33, player: 'Travis Jones', pos: 'DT', school: 'Connecticut'},
    {rank: 34, player: 'Kenyon Green', pos: 'OG', school: 'Texas A&M'},
    {rank: 35, player: 'Logan Hall', pos: 'DT', school: 'Houston'},
    {rank: 36, player: 'Chad Muma', pos: 'LB', school: 'Wyoming'},
    {rank: 37, player: 'Boye Mafe', pos: 'EDGE', school: 'Minnesota'},
    {rank: 38, player: 'Breece Hall', pos: 'RB', school: 'Iowa State'},
    {rank: 39, player: 'Jaquan Brisker', pos: 'S', school: 'Penn State'},
    {rank: 40, player: 'Bernhard Raimann', pos: 'OT', school: 'Central Michigan'},
    {rank: 41, player: 'Jahan Dotson', pos: 'WR', school: 'Penn State'},
    {rank: 42, player: 'Kaiir Elam', pos: 'CB', school: 'Florida'},
    {rank: 43, player: 'Desmond Ridder', pos: 'QB', school: 'Cincinnati'},
    {rank: 44, player: 'Tyler Smith', pos: 'OT', school: 'Tulsa'},
    {rank: 45, player: 'Kyler Gordon', pos: 'CB', school: 'Washington'},
    {rank: 46, player: 'Trevor Penning', pos: 'OT', school: 'Northern Iowa'},
    {rank: 47, player: 'Malik Willis', pos: 'QB', school: 'Liberty'},
    {rank: 48, player: 'Leo Chenal', pos: 'LB', school: 'Wisconsin'},
    {rank: 49, player: 'Kenneth Walker III', pos: 'RB', school: 'Michigan State'},
    {rank: 50, player: 'Sam Howell', pos: 'QB', school: 'North Carolina'},
  ],
};

const PFF_2023: Board = {
  expertSlug: 'pff',
  year: 2023,
  source: 'https://www.pff.com/news/draft-2023-nfl-draft-sikkema-top-150-prospects-big-board',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Bryce Young', pos: 'QB', school: 'Alabama'},
    {rank: 2, player: 'Bijan Robinson', pos: 'RB', school: 'Texas'},
    {rank: 3, player: 'Will Anderson Jr.', pos: 'EDGE', school: 'Alabama'},
    {rank: 4, player: 'Jalen Carter', pos: 'DT', school: 'Georgia'},
    {rank: 5, player: 'Peter Skoronski', pos: 'OT', school: 'Northwestern'},
    {rank: 6, player: 'Devon Witherspoon', pos: 'CB', school: 'Illinois'},
    {rank: 7, player: 'Christian Gonzalez', pos: 'CB', school: 'Oregon'},
    {rank: 8, player: 'C.J. Stroud', pos: 'QB', school: 'Ohio State'},
    {rank: 9, player: 'Paris Johnson Jr.', pos: 'OT', school: 'Ohio State'},
    {rank: 10, player: 'Anthony Richardson', pos: 'QB', school: 'Florida'},
    {rank: 11, player: 'Darnell Wright', pos: 'OT', school: 'Tennessee'},
    {rank: 12, player: 'Will Levis', pos: 'QB', school: 'Kentucky'},
    {rank: 13, player: 'Nolan Smith', pos: 'EDGE', school: 'Georgia'},
    {rank: 14, player: 'Deonte Banks', pos: 'CB', school: 'Maryland'},
    {rank: 15, player: 'Broderick Jones', pos: 'OT', school: 'Georgia'},
    {rank: 16, player: 'Darnell Washington', pos: 'TE', school: 'Georgia'},
    {rank: 17, player: 'Joey Porter Jr.', pos: 'CB', school: 'Penn State'},
    {rank: 18, player: 'Brian Branch', pos: 'S', school: 'Alabama'},
    {rank: 19, player: 'Anton Harrison', pos: 'OT', school: 'Oklahoma'},
    {rank: 20, player: 'Jahmyr Gibbs', pos: 'RB', school: 'Alabama'},
    {rank: 21, player: 'Dalton Kincaid', pos: 'TE', school: 'Utah'},
    {rank: 22, player: 'Jaxon Smith-Njigba', pos: 'WR', school: 'Ohio State'},
    {rank: 23, player: 'Calijah Kancey', pos: 'DT', school: 'Pittsburgh'},
    {rank: 24, player: 'Michael Mayer', pos: 'TE', school: 'Notre Dame'},
    {rank: 25, player: 'Myles Murphy', pos: 'EDGE', school: 'Clemson'},
    {rank: 26, player: 'Matthew Bergeron', pos: 'OT', school: 'Syracuse'},
    {rank: 27, player: 'Quentin Johnston', pos: 'WR', school: 'TCU'},
    {rank: 28, player: 'Drew Sanders', pos: 'LB', school: 'Arkansas'},
    {rank: 29, player: 'BJ Ojulari', pos: 'EDGE', school: 'LSU'},
    {rank: 30, player: 'Emmanuel Forbes', pos: 'CB', school: 'Mississippi State'},
    {rank: 31, player: 'Zay Flowers', pos: 'WR', school: 'Boston College'},
    {rank: 32, player: 'Lukas Van Ness', pos: 'EDGE', school: 'Iowa'},
    {rank: 33, player: 'Tyree Wilson', pos: 'EDGE', school: 'Texas Tech'},
    {rank: 34, player: 'Josh Downs', pos: 'WR', school: 'North Carolina'},
    {rank: 35, player: 'Will McDonald IV', pos: 'EDGE', school: 'Iowa State'},
    {rank: 36, player: 'Tyrique Stevenson', pos: 'CB', school: 'Miami'},
    {rank: 37, player: 'Felix Anudike-Uzomah', pos: 'EDGE', school: 'Kansas State'},
    {rank: 38, player: 'DJ Turner', pos: 'CB', school: 'Michigan'},
    {rank: 39, player: 'Dawand Jones', pos: 'OT', school: 'Ohio State'},
    {rank: 40, player: 'Bryan Bresee', pos: 'DT', school: 'Clemson'},
    {rank: 41, player: 'Steve Avila', pos: 'OG', school: 'TCU'},
    {rank: 42, player: 'Mazi Smith', pos: 'DT', school: 'Michigan'},
    {rank: 43, player: "O'Cyrus Torrence", pos: 'OG', school: 'Florida'},
    {rank: 44, player: 'Jartavius Martin', pos: 'CB', school: 'Illinois'},
    {rank: 45, player: 'John Michael Schmitz', pos: 'C', school: 'Minnesota'},
    {rank: 46, player: 'Sydney Brown', pos: 'S', school: 'Illinois'},
    {rank: 47, player: 'Sam LaPorta', pos: 'TE', school: 'Iowa'},
    {rank: 48, player: 'Jordan Addison', pos: 'WR', school: 'USC'},
    {rank: 49, player: 'Jack Campbell', pos: 'LB', school: 'Iowa'},
    {rank: 50, player: 'Kelee Ringo', pos: 'CB', school: 'Georgia'},
  ],
};

const PFF_2024: Board = {
  expertSlug: 'pff',
  year: 2024,
  source: 'https://www.pff.com/news/draft-2024-nfl-draft-board-big-board',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Caleb Williams', pos: 'QB', school: 'USC'},
    {rank: 2, player: 'Marvin Harrison Jr.', pos: 'WR', school: 'Ohio State'},
    {rank: 3, player: 'Drake Maye', pos: 'QB', school: 'North Carolina'},
    {rank: 4, player: 'Malik Nabers', pos: 'WR', school: 'LSU'},
    {rank: 5, player: 'Joe Alt', pos: 'OT', school: 'Notre Dame'},
    {rank: 6, player: 'Rome Odunze', pos: 'WR', school: 'Washington'},
    {rank: 7, player: 'Brock Bowers', pos: 'TE', school: 'Georgia'},
    {rank: 8, player: 'Cooper DeJean', pos: 'CB', school: 'Iowa'},
    {rank: 9, player: 'Quinyon Mitchell', pos: 'CB', school: 'Toledo'},
    {rank: 10, player: 'Laiatu Latu', pos: 'EDGE', school: 'UCLA'},
    {rank: 11, player: "Jer'Zhan Newton", pos: 'DT', school: 'Illinois'},
    {rank: 12, player: 'Byron Murphy II', pos: 'DT', school: 'Texas'},
    {rank: 13, player: 'Taliese Fuaga', pos: 'OT', school: 'Oregon State'},
    {rank: 14, player: 'Terrion Arnold', pos: 'CB', school: 'Alabama'},
    {rank: 15, player: 'Troy Fautanu', pos: 'OT', school: 'Washington'},
    {rank: 16, player: 'Dallas Turner', pos: 'EDGE', school: 'Alabama'},
    {rank: 17, player: 'Olumuyiwa Fashanu', pos: 'OT', school: 'Penn State'},
    {rank: 18, player: 'JC Latham', pos: 'OT', school: 'Alabama'},
    {rank: 19, player: 'Jared Verse', pos: 'EDGE', school: 'Florida State'},
    {rank: 20, player: 'Amarius Mims', pos: 'OT', school: 'Georgia'},
    {rank: 21, player: 'Jayden Daniels', pos: 'QB', school: 'LSU'},
    {rank: 22, player: 'Adonai Mitchell', pos: 'WR', school: 'Texas'},
    {rank: 23, player: 'Graham Barton', pos: 'OT', school: 'Duke'},
    {rank: 24, player: 'Nate Wiggins', pos: 'CB', school: 'Clemson'},
    {rank: 25, player: 'Brian Thomas Jr.', pos: 'WR', school: 'LSU'},
    {rank: 26, player: 'Kool-Aid McKinstry', pos: 'CB', school: 'Alabama'},
    {rank: 27, player: 'Jackson Powers-Johnson', pos: 'C', school: 'Oregon'},
    {rank: 28, player: 'J.J. McCarthy', pos: 'QB', school: 'Michigan'},
    {rank: 29, player: 'Troy Franklin', pos: 'WR', school: 'Oregon'},
    {rank: 30, player: 'Payton Wilson', pos: 'LB', school: 'NC State'},
    {rank: 31, player: 'Tyler Nubin', pos: 'S', school: 'Minnesota'},
    {rank: 32, player: 'Ladd McConkey', pos: 'WR', school: 'Georgia'},
    {rank: 33, player: 'Zach Frazier', pos: 'C', school: 'West Virginia'},
    {rank: 34, player: 'Mike Sainristil', pos: 'CB', school: 'Michigan'},
    {rank: 35, player: 'Bo Nix', pos: 'QB', school: 'Oregon'},
    {rank: 36, player: 'Michael Penix Jr.', pos: 'QB', school: 'Washington'},
    {rank: 37, player: 'Jordan Morgan', pos: 'OT', school: 'Arizona'},
    {rank: 38, player: 'Adisa Isaac', pos: 'EDGE', school: 'Penn State'},
    {rank: 39, player: 'Tyler Guyton', pos: 'OT', school: 'Oklahoma'},
    {rank: 40, player: 'Chop Robinson', pos: 'EDGE', school: 'Penn State'},
    {rank: 41, player: 'Keon Coleman', pos: 'WR', school: 'Florida State'},
    {rank: 42, player: 'Roman Wilson', pos: 'WR', school: 'Michigan'},
    {rank: 43, player: "Ja'Tavion Sanders", pos: 'TE', school: 'Texas'},
    {rank: 44, player: 'Braden Fiske', pos: 'DT', school: 'Florida State'},
    {rank: 45, player: 'Ricky Pearsall', pos: 'WR', school: 'Florida'},
    {rank: 46, player: 'Ennis Rakestraw Jr.', pos: 'CB', school: 'Missouri'},
    {rank: 47, player: 'Javon Bullard', pos: 'S', school: 'Georgia'},
    {rank: 48, player: "Ja'Lynn Polk", pos: 'WR', school: 'Washington'},
    {rank: 49, player: 'Jonathon Brooks', pos: 'RB', school: 'Texas'},
    {rank: 50, player: 'Kris Jenkins', pos: 'DT', school: 'Michigan'},
  ],
};

// ─────────────────────────────────────────────────────────────────
// Chris Trapasso (CBS Sports)
// ─────────────────────────────────────────────────────────────────

const TRAPASSO_2018: Board = {
  expertSlug: 'trapasso',
  year: 2018,
  source:
    'https://www.cbssports.com/nfl/draft/news/2018-nfl-draft-prospect-rankings-top-150-overall-plus-breaking-down-first-round-locks/',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Bradley Chubb', pos: 'EDGE', school: 'NC State'},
    {rank: 2, player: 'Derwin James', pos: 'S', school: 'Florida State'},
    {rank: 3, player: 'Quenton Nelson', pos: 'OG', school: 'Notre Dame'},
    {rank: 4, player: 'Roquan Smith', pos: 'LB', school: 'Georgia'},
    {rank: 5, player: 'Courtland Sutton', pos: 'WR', school: 'SMU'},
    {rank: 6, player: 'Saquon Barkley', pos: 'RB', school: 'Penn State'},
    {rank: 7, player: 'Maurice Hurst', pos: 'DT', school: 'Michigan'},
    {rank: 8, player: 'Joshua Jackson', pos: 'CB', school: 'Iowa'},
    {rank: 9, player: 'Minkah Fitzpatrick', pos: 'S', school: 'Alabama'},
    {rank: 10, player: 'Mason Rudolph', pos: 'QB', school: 'Oklahoma State'},
    {rank: 11, player: 'Jaire Alexander', pos: 'CB', school: 'Louisville'},
    {rank: 12, player: 'Derrius Guice', pos: 'RB', school: 'LSU'},
    {rank: 13, player: 'Denzel Ward', pos: 'CB', school: 'Ohio State'},
    {rank: 14, player: 'Lamar Jackson', pos: 'QB', school: 'Louisville'},
    {rank: 15, player: 'Ogbonnia Okoronkwo', pos: 'LB', school: 'Oklahoma'},
    {rank: 16, player: 'Josh Rosen', pos: 'QB', school: 'UCLA'},
    {rank: 17, player: 'Taven Bryan', pos: 'DT', school: 'Florida'},
    {rank: 18, player: 'James Washington', pos: 'WR', school: 'Oklahoma State'},
    {rank: 19, player: 'Vita Vea', pos: 'DT', school: 'Washington'},
    {rank: 20, player: 'Marcus Davenport', pos: 'EDGE', school: 'UTSA'},
    {rank: 21, player: 'Isaiah Wynn', pos: 'OT', school: 'Georgia'},
    {rank: 22, player: 'Sam Darnold', pos: 'QB', school: 'USC'},
    {rank: 23, player: 'Will Hernandez', pos: 'OG', school: 'UTEP'},
    {rank: 24, player: "Da'Ron Payne", pos: 'DT', school: 'Alabama'},
    {rank: 25, player: 'Tremaine Edmunds', pos: 'LB', school: 'Virginia Tech'},
    {rank: 26, player: 'Orlando Brown', pos: 'OT', school: 'Oklahoma'},
    {rank: 27, player: 'Leighton Vander Esch', pos: 'LB', school: 'Boise State'},
    {rank: 28, player: 'Kolton Miller', pos: 'OT', school: 'UCLA'},
    {rank: 29, player: 'Isaiah Oliver', pos: 'CB', school: 'Colorado'},
    {rank: 30, player: 'Connor Williams', pos: 'OT', school: 'Texas'},
    {rank: 31, player: "Dorian O'Daniel", pos: 'LB', school: 'Clemson'},
    {rank: 32, player: 'Michael Gallup', pos: 'WR', school: 'Colorado State'},
    {rank: 33, player: 'Frank Ragnow', pos: 'C', school: 'Arkansas'},
    {rank: 34, player: 'Baker Mayfield', pos: 'QB', school: 'Oklahoma'},
    {rank: 35, player: 'Mike McGlinchey', pos: 'OT', school: 'Notre Dame'},
    {rank: 36, player: 'Ronald Jones II', pos: 'RB', school: 'USC'},
    {rank: 37, player: 'Chukwuma Okorafor', pos: 'OT', school: 'Western Michigan'},
    {rank: 38, player: 'Marcell Ateman', pos: 'WR', school: 'Oklahoma State'},
    {rank: 39, player: 'Braden Smith', pos: 'OG', school: 'Auburn'},
    {rank: 40, player: 'Tyrell Crosby', pos: 'OT', school: 'Oregon'},
    {rank: 41, player: 'Holton Hill', pos: 'CB', school: 'Texas'},
    {rank: 42, player: 'James Daniels', pos: 'C', school: 'Iowa'},
    {rank: 43, player: 'Harrison Phillips', pos: 'DT', school: 'Stanford'},
    {rank: 44, player: 'Anthony Miller', pos: 'WR', school: 'Memphis'},
    {rank: 45, player: 'Nick Chubb', pos: 'RB', school: 'Georgia'},
    {rank: 46, player: 'Calvin Ridley', pos: 'WR', school: 'Alabama'},
    {rank: 47, player: 'Billy Price', pos: 'OG', school: 'Ohio State'},
    {rank: 48, player: 'Darius Leonard', pos: 'LB', school: 'South Carolina State'},
    {rank: 49, player: 'Josh Sweat', pos: 'EDGE', school: 'Florida State'},
    {rank: 50, player: 'Rashaan Evans', pos: 'LB', school: 'Alabama'},
  ],
};

const TRAPASSO_2019: Board = {
  expertSlug: 'trapasso',
  year: 2019,
  source:
    'https://www.cbssports.com/nfl/draft/news/nfl-draft-2019-prospect-rankings-my-final-top-200-big-board-with-no-quarterbacks-in-the-top-15/',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Nick Bosa', pos: 'EDGE', school: 'Ohio State'},
    {rank: 2, player: 'Ed Oliver', pos: 'DT', school: 'Houston'},
    {rank: 3, player: 'Jonah Williams', pos: 'OT', school: 'Alabama'},
    {rank: 4, player: 'Quinnen Williams', pos: 'DT', school: 'Alabama'},
    {rank: 5, player: 'Jeffery Simmons', pos: 'DT', school: 'Mississippi State'},
    {rank: 6, player: 'Greedy Williams', pos: 'CB', school: 'LSU'},
    {rank: 7, player: 'Jerry Tillery', pos: 'DT', school: 'Notre Dame'},
    {rank: 8, player: 'Deandre Baker', pos: 'CB', school: 'Georgia'},
    {rank: 9, player: 'Dalton Risner', pos: 'OT', school: 'Kansas State'},
    {rank: 10, player: 'A.J. Brown', pos: 'WR', school: 'Mississippi'},
    {rank: 11, player: 'Zach Allen', pos: 'EDGE', school: 'Boston College'},
    {rank: 12, player: 'Christian Wilkins', pos: 'DT', school: 'Clemson'},
    {rank: 13, player: 'Ben Burr-Kirven', pos: 'LB', school: 'Washington'},
    {rank: 14, player: 'Montez Sweat', pos: 'EDGE', school: 'Mississippi State'},
    {rank: 15, player: 'Devin White', pos: 'LB', school: 'LSU'},
    {rank: 16, player: 'Dexter Lawrence', pos: 'DT', school: 'Clemson'},
    {rank: 17, player: 'Clelin Ferrell', pos: 'EDGE', school: 'Clemson'},
    {rank: 18, player: 'Byron Murphy', pos: 'CB', school: 'Washington'},
    {rank: 19, player: 'Drew Lock', pos: 'QB', school: 'Missouri'},
    {rank: 20, player: 'Hakeem Butler', pos: 'WR', school: 'Iowa State'},
    {rank: 21, player: 'Josh Allen', pos: 'EDGE', school: 'Kentucky'},
    {rank: 22, player: 'JJ Arcega-Whiteside', pos: 'WR', school: 'Stanford'},
    {rank: 23, player: 'Kyler Murray', pos: 'QB', school: 'Oklahoma'},
    {rank: 24, player: "N'Keal Harry", pos: 'WR', school: 'Arizona State'},
    {rank: 25, player: 'Brian Burns', pos: 'EDGE', school: 'Florida State'},
    {rank: 26, player: 'Jawaan Taylor', pos: 'OT', school: 'Florida'},
    {rank: 27, player: 'Andre Dillard', pos: 'OT', school: 'Washington State'},
    {rank: 28, player: 'Julian Love', pos: 'CB', school: 'Notre Dame'},
    {rank: 29, player: 'D.K. Metcalf', pos: 'WR', school: 'Mississippi'},
    {rank: 30, player: 'Devin Bush Jr.', pos: 'LB', school: 'Michigan'},
    {rank: 31, player: 'Juan Thornhill', pos: 'S', school: 'Virginia'},
    {rank: 32, player: 'Justin Layne', pos: 'CB', school: 'Michigan State'},
    {rank: 33, player: 'Kelvin Harmon', pos: 'WR', school: 'NC State'},
    {rank: 34, player: 'T.J. Hockenson', pos: 'TE', school: 'Iowa'},
    {rank: 35, player: 'David Long', pos: 'CB', school: 'Michigan'},
    {rank: 36, player: 'Amani Oruwariye', pos: 'CB', school: 'Penn State'},
    {rank: 37, player: 'Noah Fant', pos: 'TE', school: 'Iowa'},
    {rank: 38, player: 'Anthony Nelson', pos: 'EDGE', school: 'Iowa'},
    {rank: 39, player: 'Yodny Cajuste', pos: 'OT', school: 'West Virginia'},
    {rank: 40, player: 'Marquise Brown', pos: 'WR', school: 'Oklahoma'},
    {rank: 41, player: 'Greg Little', pos: 'OT', school: 'Mississippi'},
    {rank: 42, player: 'Chris Lindstrom', pos: 'OG', school: 'Boston College'},
    {rank: 43, player: "Dre'Mont Jones", pos: 'DT', school: 'Ohio State'},
    {rank: 44, player: 'Lonnie Johnson', pos: 'CB', school: 'Kentucky'},
    {rank: 45, player: 'Elgton Jenkins', pos: 'C', school: 'Mississippi State'},
    {rank: 46, player: 'Kris Boyd', pos: 'CB', school: 'Texas'},
    {rank: 47, player: 'Amani Hooker', pos: 'S', school: 'Iowa'},
    {rank: 48, player: 'Cody Ford', pos: 'OG', school: 'Oklahoma'},
    {rank: 49, player: 'Oshane Ximines', pos: 'EDGE', school: 'Old Dominion'},
    {rank: 50, player: 'Nasir Adderley', pos: 'S', school: 'Delaware'},
  ],
};

const TRAPASSO_2021: Board = {
  expertSlug: 'trapasso',
  year: 2021,
  source:
    'https://www.cbssports.com/nfl/draft/news/2021-nfl-draft-big-board-georgias-azeez-ojulari-as-edge1-asante-samuel-jr-in-top-20-plenty-of-receivers/',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Trevor Lawrence', pos: 'QB', school: 'Clemson'},
    {rank: 2, player: 'Zach Wilson', pos: 'QB', school: 'BYU'},
    {rank: 3, player: 'Justin Fields', pos: 'QB', school: 'Ohio State'},
    {rank: 4, player: 'Jaylen Waddle', pos: 'WR', school: 'Alabama'},
    {rank: 5, player: "Ja'Marr Chase", pos: 'WR', school: 'LSU'},
    {rank: 6, player: 'Kyle Pitts', pos: 'TE', school: 'Florida'},
    {rank: 7, player: 'DeVonta Smith', pos: 'WR', school: 'Alabama'},
    {rank: 8, player: 'Penei Sewell', pos: 'OT', school: 'Oregon'},
    {rank: 9, player: 'Trey Lance', pos: 'QB', school: 'North Dakota State'},
    {rank: 10, player: 'Jeremiah Owusu-Koramoah', pos: 'LB', school: 'Notre Dame'},
    {rank: 11, player: 'Christian Darrisaw', pos: 'OT', school: 'Virginia Tech'},
    {rank: 12, player: 'Trevon Moehrig', pos: 'S', school: 'TCU'},
    {rank: 13, player: 'Azeez Ojulari', pos: 'EDGE', school: 'Georgia'},
    {rank: 14, player: 'Richie Grant', pos: 'S', school: 'UCF'},
    {rank: 15, player: 'Caleb Farley', pos: 'CB', school: 'Virginia Tech'},
    {rank: 16, player: 'Andre Cisco', pos: 'S', school: 'Syracuse'},
    {rank: 17, player: 'Kwity Paye', pos: 'EDGE', school: 'Michigan'},
    {rank: 18, player: 'Rondale Moore', pos: 'WR', school: 'Purdue'},
    {rank: 19, player: 'Asante Samuel Jr.', pos: 'CB', school: 'Florida State'},
    {rank: 20, player: 'Teven Jenkins', pos: 'OT', school: 'Oklahoma State'},
    {rank: 21, player: 'Greg Newsome II', pos: 'CB', school: 'Northwestern'},
    {rank: 22, player: 'Micah Parsons', pos: 'LB', school: 'Penn State'},
    {rank: 23, player: 'Rashod Bateman', pos: 'WR', school: 'Minnesota'},
    {rank: 24, player: 'Rashawn Slater', pos: 'OT', school: 'Northwestern'},
    {rank: 25, player: 'Jaelan Phillips', pos: 'EDGE', school: 'Miami'},
    {rank: 26, player: 'Levi Onwuzurike', pos: 'DT', school: 'Washington'},
    {rank: 27, player: 'Carlos Basham Jr.', pos: 'EDGE', school: 'Wake Forest'},
    {rank: 28, player: 'Joseph Ossai', pos: 'EDGE', school: 'Texas'},
    {rank: 29, player: 'Patrick Surtain II', pos: 'CB', school: 'Alabama'},
    {rank: 30, player: 'Elijah Moore', pos: 'WR', school: 'Mississippi'},
    {rank: 31, player: 'Ifeatu Melifonwu', pos: 'CB', school: 'Syracuse'},
    {rank: 32, player: 'Terrace Marshall Jr.', pos: 'WR', school: 'LSU'},
    {rank: 33, player: 'Kadarius Toney', pos: 'WR', school: 'Florida'},
    {rank: 34, player: 'Christian Barmore', pos: 'DT', school: 'Alabama'},
    {rank: 35, player: 'Jaycee Horn', pos: 'CB', school: 'South Carolina'},
    {rank: 36, player: 'Eric Stokes', pos: 'CB', school: 'Georgia'},
    {rank: 37, player: 'Zaven Collins', pos: 'LB', school: 'Tulsa'},
    {rank: 38, player: 'Alex Leatherwood', pos: 'OT', school: 'Alabama'},
    {rank: 39, player: 'Alijah Vera-Tucker', pos: 'OG', school: 'USC'},
    {rank: 40, player: 'Mac Jones', pos: 'QB', school: 'Alabama'},
    {rank: 41, player: 'Josh Palmer', pos: 'WR', school: 'Tennessee'},
    {rank: 42, player: 'Najee Harris', pos: 'RB', school: 'Alabama'},
    {rank: 43, player: 'Payton Turner', pos: 'EDGE', school: 'Houston'},
    {rank: 44, player: 'Adetokunbo Ogundeji', pos: 'EDGE', school: 'Notre Dame'},
    {rank: 45, player: "Ar'Darius Washington", pos: 'S', school: 'TCU'},
    {rank: 46, player: 'Jayson Oweh', pos: 'EDGE', school: 'Penn State'},
    {rank: 47, player: 'Tyson Campbell', pos: 'CB', school: 'Georgia'},
    {rank: 48, player: 'Milton Williams', pos: 'DT', school: 'Louisiana Tech'},
    {rank: 49, player: 'Kary Vincent Jr.', pos: 'CB', school: 'LSU'},
    {rank: 50, player: 'Wyatt Davis', pos: 'OG', school: 'Ohio State'},
  ],
};

const TRAPASSO_2022: Board = {
  expertSlug: 'trapasso',
  year: 2022,
  source:
    'https://www.cbssports.com/nfl/draft/news/2022-nfl-draft-final-top-300-big-board-malik-willis-as-qb1-skyy-moore-cracks-top-20-plenty-of-edge-rushers/',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Kyle Hamilton', pos: 'S', school: 'Notre Dame'},
    {rank: 2, player: 'Derek Stingley Jr.', pos: 'CB', school: 'LSU'},
    {rank: 3, player: 'Aidan Hutchinson', pos: 'EDGE', school: 'Michigan'},
    {rank: 4, player: 'Kayvon Thibodeaux', pos: 'EDGE', school: 'Oregon'},
    {rank: 5, player: 'Evan Neal', pos: 'OT', school: 'Alabama'},
    {rank: 6, player: 'Charles Cross', pos: 'OT', school: 'Mississippi State'},
    {rank: 7, player: 'Ahmad Gardner', pos: 'CB', school: 'Cincinnati'},
    {rank: 8, player: 'Malik Willis', pos: 'QB', school: 'Liberty'},
    {rank: 9, player: 'Drake London', pos: 'WR', school: 'USC'},
    {rank: 10, player: 'Arnold Ebiketie', pos: 'EDGE', school: 'Penn State'},
    {rank: 11, player: 'Andrew Booth Jr.', pos: 'CB', school: 'Clemson'},
    {rank: 12, player: 'Ikem Ekwonu', pos: 'OT', school: 'NC State'},
    {rank: 13, player: 'Jameson Williams', pos: 'WR', school: 'Alabama'},
    {rank: 14, player: 'Kenny Pickett', pos: 'QB', school: 'Pittsburgh'},
    {rank: 15, player: 'Garrett Wilson', pos: 'WR', school: 'Ohio State'},
    {rank: 16, player: 'Roger McCreary', pos: 'CB', school: 'Auburn'},
    {rank: 17, player: 'Daxton Hill', pos: 'CB', school: 'Michigan'},
    {rank: 18, player: 'Skyy Moore', pos: 'WR', school: 'Western Michigan'},
    {rank: 19, player: 'Treylon Burks', pos: 'WR', school: 'Arkansas'},
    {rank: 20, player: 'Tyler Linderbaum', pos: 'C', school: 'Iowa'},
    {rank: 21, player: 'Jalen Pitre', pos: 'CB', school: 'Baylor'},
    {rank: 22, player: 'Zion Johnson', pos: 'OG', school: 'Boston College'},
    {rank: 23, player: 'Chris Olave', pos: 'WR', school: 'Ohio State'},
    {rank: 24, player: 'George Pickens', pos: 'WR', school: 'Georgia'},
    {rank: 25, player: 'Lewis Cine', pos: 'S', school: 'Georgia'},
    {rank: 26, player: 'Nakobe Dean', pos: 'LB', school: 'Georgia'},
    {rank: 27, player: 'George Karlaftis', pos: 'EDGE', school: 'Purdue'},
    {rank: 28, player: 'Desmond Ridder', pos: 'QB', school: 'Cincinnati'},
    {rank: 29, player: 'Bernhard Raimann', pos: 'OT', school: 'Central Michigan'},
    {rank: 30, player: 'Trevor Penning', pos: 'OT', school: 'Northern Iowa'},
    {rank: 31, player: 'Jaquan Brisker', pos: 'S', school: 'Penn State'},
    {rank: 32, player: 'Boye Mafe', pos: 'EDGE', school: 'Minnesota'},
    {rank: 33, player: 'Kaiir Elam', pos: 'CB', school: 'Florida'},
    {rank: 34, player: 'Jahan Dotson', pos: 'WR', school: 'Penn State'},
    {rank: 35, player: 'Logan Hall', pos: 'DT', school: 'Houston'},
    {rank: 36, player: 'Devonte Wyatt', pos: 'DT', school: 'Georgia'},
    {rank: 37, player: 'Kyler Gordon', pos: 'CB', school: 'Washington'},
    {rank: 38, player: 'Kerby Joseph', pos: 'S', school: 'Illinois'},
    {rank: 39, player: 'Chad Muma', pos: 'LB', school: 'Wyoming'},
    {rank: 40, player: 'Daniel Faalele', pos: 'OT', school: 'Minnesota'},
    {rank: 41, player: 'Zyon McCollum', pos: 'CB', school: 'Sam Houston State'},
    {rank: 42, player: 'Jermaine Johnson', pos: 'EDGE', school: 'Florida State'},
    {rank: 43, player: 'Matt Corral', pos: 'QB', school: 'Mississippi'},
    {rank: 44, player: 'David Ojabo', pos: 'EDGE', school: 'Michigan'},
    {rank: 45, player: 'Travon Walker', pos: 'EDGE', school: 'Georgia'},
    {rank: 46, player: 'Myjai Sanders', pos: 'EDGE', school: 'Cincinnati'},
    {rank: 47, player: 'Marquis Hayes', pos: 'OG', school: 'Oklahoma'},
    {rank: 48, player: 'Jordan Davis', pos: 'DT', school: 'Georgia'},
    {rank: 49, player: 'Trent McDuffie', pos: 'CB', school: 'Washington'},
    {rank: 50, player: 'Sam Williams', pos: 'EDGE', school: 'Mississippi'},
  ],
};

const TRAPASSO_2023: Board = {
  expertSlug: 'trapasso',
  year: 2023,
  source:
    'https://www.cbssports.com/nfl/draft/news/2023-nfl-draft-top-100-big-board-anthony-richardson-no-1-four-cbs-in-top-16-darnell-washington-as-te1/',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Anthony Richardson', pos: 'QB', school: 'Florida'},
    {rank: 2, player: 'C.J. Stroud', pos: 'QB', school: 'Ohio State'},
    {rank: 3, player: 'Will Anderson Jr.', pos: 'EDGE', school: 'Alabama'},
    {rank: 4, player: 'Bryce Young', pos: 'QB', school: 'Alabama'},
    {rank: 5, player: 'Jalen Carter', pos: 'DT', school: 'Georgia'},
    {rank: 6, player: 'Lukas Van Ness', pos: 'EDGE', school: 'Iowa'},
    {rank: 7, player: 'Quentin Johnston', pos: 'WR', school: 'TCU'},
    {rank: 8, player: 'Darnell Wright', pos: 'OT', school: 'Tennessee'},
    {rank: 9, player: 'Tyree Wilson', pos: 'EDGE', school: 'Texas Tech'},
    {rank: 10, player: 'Cam Smith', pos: 'CB', school: 'South Carolina'},
    {rank: 11, player: 'Joey Porter Jr.', pos: 'CB', school: 'Penn State'},
    {rank: 12, player: 'Calijah Kancey', pos: 'DT', school: 'Pittsburgh'},
    {rank: 13, player: 'Nolan Smith', pos: 'EDGE', school: 'Georgia'},
    {rank: 14, player: 'Christian Gonzalez', pos: 'CB', school: 'Oregon'},
    {rank: 15, player: 'Will Levis', pos: 'QB', school: 'Kentucky'},
    {rank: 16, player: 'Devon Witherspoon', pos: 'CB', school: 'Illinois'},
    {rank: 17, player: 'Bryan Bresee', pos: 'DT', school: 'Clemson'},
    {rank: 18, player: 'Paris Johnson Jr.', pos: 'OT', school: 'Ohio State'},
    {rank: 19, player: 'Jack Campbell', pos: 'LB', school: 'Iowa'},
    {rank: 20, player: 'Jaxon Smith-Njigba', pos: 'WR', school: 'Ohio State'},
    {rank: 21, player: 'Deonte Banks', pos: 'CB', school: 'Maryland'},
    {rank: 22, player: 'Brian Branch', pos: 'S', school: 'Alabama'},
    {rank: 23, player: 'Olusegun Oluwatimi', pos: 'C', school: 'Michigan'},
    {rank: 24, player: 'Darnell Washington', pos: 'TE', school: 'Georgia'},
    {rank: 25, player: 'Derick Hall', pos: 'EDGE', school: 'Auburn'},
    {rank: 26, player: 'Michael Mayer', pos: 'TE', school: 'Notre Dame'},
    {rank: 27, player: 'Broderick Jones', pos: 'OT', school: 'Georgia'},
    {rank: 28, player: 'Jakorian Bennett', pos: 'CB', school: 'Maryland'},
    {rank: 29, player: 'Anton Harrison', pos: 'OT', school: 'Oklahoma'},
    {rank: 30, player: 'Sam LaPorta', pos: 'TE', school: 'Iowa'},
    {rank: 31, player: 'John Michael Schmitz', pos: 'C', school: 'Minnesota'},
    {rank: 32, player: 'Felix Anudike-Uzomah', pos: 'EDGE', school: 'Kansas State'},
    {rank: 33, player: 'Zay Flowers', pos: 'WR', school: 'Boston College'},
    {rank: 34, player: 'Will McDonald IV', pos: 'EDGE', school: 'Iowa State'},
    {rank: 35, player: 'Peter Skoronski', pos: 'OT', school: 'Northwestern'},
    {rank: 36, player: 'Dalton Kincaid', pos: 'TE', school: 'Utah'},
    {rank: 37, player: 'Steve Avila', pos: 'OG', school: 'TCU'},
    {rank: 38, player: 'Bijan Robinson', pos: 'RB', school: 'Texas'},
    {rank: 39, player: 'Sidy Sow', pos: 'OG', school: 'Eastern Michigan'},
    {rank: 40, player: "O'Cyrus Torrence", pos: 'OG', school: 'Florida'},
    {rank: 41, player: 'Rashee Rice', pos: 'WR', school: 'SMU'},
    {rank: 42, player: 'Cory Trice', pos: 'CB', school: 'Purdue'},
    {rank: 43, player: 'Myles Murphy', pos: 'EDGE', school: 'Clemson'},
    {rank: 44, player: 'Darius Rush', pos: 'CB', school: 'South Carolina'},
    {rank: 45, player: 'Jordan Addison', pos: 'WR', school: 'USC'},
    {rank: 46, player: 'JL Skinner', pos: 'S', school: 'Boise State'},
    {rank: 47, player: 'Jalen Redmond', pos: 'DT', school: 'Oklahoma'},
    {rank: 48, player: 'Jahmyr Gibbs', pos: 'RB', school: 'Alabama'},
    {rank: 49, player: 'Daiyan Henley', pos: 'LB', school: 'Washington State'},
    {rank: 50, player: 'Adetomiwa Adebawore', pos: 'DT', school: 'Northwestern'},
  ],
};

const TRAPASSO_2024: Board = {
  expertSlug: 'trapasso',
  year: 2024,
  source:
    'https://www.cbssports.com/nfl/draft/news/2024-nfl-draft-final-big-board-malik-nabers-as-wr1-6-cbs-in-the-top-32-chop-robinson-holds-edge1-and-more/',
  confidence: 'high',
  rankings: [
    {rank: 1, player: 'Caleb Williams', pos: 'QB', school: 'USC'},
    {rank: 2, player: 'Drake Maye', pos: 'QB', school: 'North Carolina'},
    {rank: 3, player: 'Malik Nabers', pos: 'WR', school: 'LSU'},
    {rank: 4, player: 'Jayden Daniels', pos: 'QB', school: 'LSU'},
    {rank: 5, player: 'Marvin Harrison Jr.', pos: 'WR', school: 'Ohio State'},
    {rank: 6, player: 'Quinyon Mitchell', pos: 'CB', school: 'Toledo'},
    {rank: 7, player: 'Olu Fashanu', pos: 'OT', school: 'Penn State'},
    {rank: 8, player: 'Taliese Fuaga', pos: 'OT', school: 'Oregon State'},
    {rank: 9, player: 'Chop Robinson', pos: 'EDGE', school: 'Penn State'},
    {rank: 10, player: 'Brian Thomas Jr.', pos: 'WR', school: 'LSU'},
    {rank: 11, player: 'Laiatu Latu', pos: 'EDGE', school: 'UCLA'},
    {rank: 12, player: 'Terrion Arnold', pos: 'CB', school: 'Alabama'},
    {rank: 13, player: 'Byron Murphy II', pos: 'DT', school: 'Texas'},
    {rank: 14, player: 'Jared Verse', pos: 'EDGE', school: 'Florida State'},
    {rank: 15, player: 'Rome Odunze', pos: 'WR', school: 'Washington'},
    {rank: 16, player: 'Kris Abrams-Draine', pos: 'CB', school: 'Missouri'},
    {rank: 17, player: 'Dallas Turner', pos: 'EDGE', school: 'Alabama'},
    {rank: 18, player: 'Amarius Mims', pos: 'OT', school: 'Georgia'},
    {rank: 19, player: 'Ladd McConkey', pos: 'WR', school: 'Georgia'},
    {rank: 20, player: 'Joe Alt', pos: 'OT', school: 'Notre Dame'},
    {rank: 21, player: 'J.J. McCarthy', pos: 'QB', school: 'Michigan'},
    {rank: 22, player: 'JC Latham', pos: 'OT', school: 'Alabama'},
    {rank: 23, player: 'Kool-Aid McKinstry', pos: 'CB', school: 'Alabama'},
    {rank: 24, player: 'Brock Bowers', pos: 'TE', school: 'Georgia'},
    {rank: 25, player: 'Cooper DeJean', pos: 'CB', school: 'Iowa'},
    {rank: 26, player: 'Nate Wiggins', pos: 'CB', school: 'Clemson'},
    {rank: 27, player: 'Jackson Powers-Johnson', pos: 'C', school: 'Oregon'},
    {rank: 28, player: 'Johnny Newton', pos: 'DT', school: 'Illinois'},
    {rank: 29, player: 'Michael Penix Jr.', pos: 'QB', school: 'Washington'},
    {rank: 30, player: 'Xavier Worthy', pos: 'WR', school: 'Texas'},
    {rank: 31, player: 'Ruke Orhorhoro', pos: 'DT', school: 'Clemson'},
    {rank: 32, player: 'Darius Robinson', pos: 'DT', school: 'Missouri'},
    {rank: 33, player: 'Bo Nix', pos: 'QB', school: 'Oregon'},
    {rank: 34, player: 'Adonai Mitchell', pos: 'WR', school: 'Texas'},
    {rank: 35, player: 'Chris Braswell', pos: 'EDGE', school: 'Alabama'},
    {rank: 36, player: 'Javon Baker', pos: 'WR', school: 'UCF'},
    {rank: 37, player: 'Elijah Jones', pos: 'CB', school: 'Boston College'},
    {rank: 38, player: 'Troy Franklin', pos: 'WR', school: 'Oregon'},
    {rank: 39, player: 'Jaden Hicks', pos: 'S', school: 'Washington State'},
    {rank: 40, player: 'Sataoa Laumea', pos: 'OG', school: 'Utah'},
    {rank: 41, player: 'Malik Washington', pos: 'WR', school: 'Virginia'},
    {rank: 42, player: 'Roger Rosengarten', pos: 'OT', school: 'Washington'},
    {rank: 43, player: 'Calen Bullock', pos: 'S', school: 'USC'},
    {rank: 44, player: 'Braden Fiske', pos: 'DT', school: 'Florida State'},
    {rank: 45, player: 'Michael Hall Jr.', pos: 'DT', school: 'Ohio State'},
    {rank: 46, player: 'Trey Benson', pos: 'RB', school: 'Florida State'},
    {rank: 47, player: 'Payton Wilson', pos: 'LB', school: 'NC State'},
    {rank: 48, player: 'Mason McCormick', pos: 'OG', school: 'South Dakota State'},
    {rank: 49, player: 'Xavier Legette', pos: 'WR', school: 'South Carolina'},
    {rank: 50, player: 'DJ James', pos: 'CB', school: 'Auburn'},
  ],
};

// ─────────────────────────────────────────────────────────────────
// Josh Norris (Underdog Fantasy → Rotoworld)
// ─────────────────────────────────────────────────────────────────

const NORRIS_2020: Board = {
  expertSlug: 'josh-norris',
  year: 2020,
  source: 'https://www.nbcsports.com/fantasy/football/news/article-nfl-draft-preview-norris-top-150-nfl-draft-board',
  confidence: 'medium',
  note: 'Top 44 only; ranks 45+ truncated in extraction.',
  rankings: [
    {rank: 1, player: 'Joe Burrow', pos: 'QB', school: 'LSU'},
    {rank: 2, player: 'Tua Tagovailoa', pos: 'QB', school: 'Alabama'},
    {rank: 3, player: 'Chase Young', pos: 'EDGE', school: 'Ohio State'},
    {rank: 4, player: 'Jeffrey Okudah', pos: 'CB', school: 'Ohio State'},
    {rank: 5, player: 'CeeDee Lamb', pos: 'WR', school: 'Oklahoma'},
    {rank: 6, player: 'Isaiah Simmons', pos: 'S', school: 'Clemson'},
    {rank: 7, player: 'Jerry Jeudy', pos: 'WR', school: 'Alabama'},
    {rank: 8, player: 'Andrew Thomas', pos: 'OT', school: 'Georgia'},
    {rank: 9, player: 'Jedrick Wills', pos: 'OT', school: 'Alabama'},
    {rank: 10, player: 'Tristan Wirfs', pos: 'OT', school: 'Iowa'},
    {rank: 11, player: 'Javon Kinlaw', pos: 'DT', school: 'South Carolina'},
    {rank: 12, player: 'Denzel Mims', pos: 'WR', school: 'Baylor'},
    {rank: 13, player: 'Justin Jefferson', pos: 'WR', school: 'LSU'},
    {rank: 14, player: 'Patrick Queen', pos: 'LB', school: 'LSU'},
    {rank: 15, player: 'Henry Ruggs', pos: 'WR', school: 'Alabama'},
    {rank: 16, player: 'Derrick Brown', pos: 'DT', school: 'Auburn'},
    {rank: 17, player: 'C.J. Henderson', pos: 'CB', school: 'Florida'},
    {rank: 18, player: 'Antoine Winfield Jr.', pos: 'S', school: 'Minnesota'},
    {rank: 19, player: 'Mekhi Becton', pos: 'OT', school: 'Louisville'},
    {rank: 20, player: 'Yetur Gross-Matos', pos: 'EDGE', school: 'Penn State'},
    {rank: 21, player: "K'Lavon Chaisson", pos: 'EDGE', school: 'LSU'},
    {rank: 22, player: 'Xavier McKinney', pos: 'S', school: 'Alabama'},
    {rank: 23, player: 'Josh Jones', pos: 'OT', school: 'Houston'},
    {rank: 24, player: 'Jaylon Johnson', pos: 'CB', school: 'Utah'},
    {rank: 25, player: 'Justin Herbert', pos: 'QB', school: 'Oregon'},
    {rank: 26, player: 'Clyde Edwards-Helaire', pos: 'RB', school: 'LSU'},
    {rank: 27, player: 'Jonathan Taylor', pos: 'RB', school: 'Wisconsin'},
    {rank: 28, player: 'Michael Pittman', pos: 'WR', school: 'USC'},
    {rank: 29, player: 'Ezra Cleveland', pos: 'OT', school: 'Boise State'},
    {rank: 30, player: 'A.J. Terrell', pos: 'CB', school: 'Clemson'},
    {rank: 31, player: 'Zack Baun', pos: 'LB', school: 'Wisconsin'},
    {rank: 32, player: 'Ashtyn Davis', pos: 'S', school: 'Cal'},
    {rank: 33, player: 'Jordan Love', pos: 'QB', school: 'Utah State'},
    {rank: 34, player: 'Grant Delpit', pos: 'S', school: 'LSU'},
    {rank: 35, player: 'Jeremy Chinn', pos: 'S', school: 'Southern Illinois'},
    {rank: 36, player: 'Robert Hunt', pos: 'OG', school: 'Louisiana'},
    {rank: 37, player: 'Kenneth Murray', pos: 'LB', school: 'Oklahoma'},
    {rank: 38, player: 'Jalen Reagor', pos: 'WR', school: 'TCU'},
    {rank: 39, player: 'Cesar Ruiz', pos: 'C', school: 'Michigan'},
    {rank: 40, player: 'Josh Uche', pos: 'EDGE', school: 'Michigan'},
    {rank: 41, player: 'Jordan Elliott', pos: 'DT', school: 'Missouri'},
    {rank: 42, player: 'Justin Madubuike', pos: 'DT', school: 'Texas A&M'},
    {rank: 43, player: 'Kristian Fulton', pos: 'CB', school: 'LSU'},
    {rank: 44, player: 'J.K. Dobbins', pos: 'RB', school: 'Ohio State'},
  ],
};

export const BOARDS_PART2: Board[] = [
  BRUGLER_2018,
  PFF_2018,
  PFF_2019,
  PFF_2021,
  PFF_2022,
  PFF_2023,
  PFF_2024,
  TRAPASSO_2018,
  TRAPASSO_2019,
  TRAPASSO_2021,
  TRAPASSO_2022,
  TRAPASSO_2023,
  TRAPASSO_2024,
  NORRIS_2020,
];
